### ISSUE TITLE
Update LICENSE to reflect project reality

### ISSUE THREAD

**Issue by licaon-kter** [diasurgical/devilutionX#3338] opened 2021-10-31 13:52 UTC
As pointed in several places (eg.  https://github.com/diasurgical/devilutionX/issues/3290#issuecomment-953489940 ) the LICENSE file contradicts the actual license terms as stated in the Readme.

It would be good to have it clear that DevilutionX is not licensed as Free Software nor as Open Source.

Hopefully once the file is updated the Github info is updated too, so it does not say Unlicensed.

**Comment by AJenbo** [comment] 2021-10-31 14:23
Duplicate of https://github.com/diasurgical/devilution/issues/2208

**Closed by AJenbo** 2021-10-31 14:23 UTC
Labels: duplicate

**Comment by licaon-kter** [comment] 2021-10-31 14:32
Oh, that's on a different repo, and locked, hence this one...


Anyway, is this on the TODO for 1.3.0?

**Comment by AJenbo** [comment] 2021-10-31 15:18
We inherit this from upstream. I suggest joining the chat if you want to brainstorm about things.

**Comment by licaon-kter** [comment] 2021-10-31 15:25
I find it odd for FOSS projects to use proprietary closed source siloed communications systems that locks information away from (possible) contributors.

Or maybe I've missed the IRC or XMPP groups where project chat is ongoing?

**Comment by qndel** [comment] 2021-10-31 15:41
@licaon-kter it's 2021, nobody is using irc/xmpp/whatever ;)
https://discord.gg/YQKCAYQ

**Comment by StephenCWills** [comment] 2021-10-31 15:43
> I find it odd for FOSS projects to use proprietary closed source siloed communications systems that lock information away from (possible) contributors.
> 
> Or maybe I've missed the IRC or XMPP groups where project chat is ongoing?

I thought you didn't consider this a FOSS project so that standard shouldn't apply. Furthermore, many of our contributors are gamers, so Discord is a natural choice.

**Comment by maciek134** [comment] 2022-05-09 11:25
I find it odd that you refuse to change the license which is clearly wrong and the readme that contradicts itself (you give up your right to restrict usage by putting something in public domain, so either the public domain part is invalid, or the commercial restriction).

CC-BY-NC would solve your "no commercial use" problem if you need a license text written by someone else.

**Comment by AJenbo** [comment] 2022-08-27 02:02
This has now been resolved, see the following for details: https://github.com/diasurgical/devilution/pull/2279
