### ISSUE TITLE
64bit build issues 

### ISSUE THREAD

**Issue by CubeTheThird** [diasurgical/devilutionX#53] opened 2019-03-23 04:56 UTC
Issues left before we can mark 64bit builds as stable
- [x] Save games are not compatible with 32bit builds
- [x] Swapping items in belt corrupt them
- [x] Moving gold converts it to a broken full mana potion
- [x] Number of scrolls is off by -2

**Comment by AJenbo** [comment] 2019-03-23 13:54
You have compiled a 64bit build, currently they are not playable. Please see the readme on how to build a 32bit version on 64bit systems.

https://github.com/diasurgical/devilutionX/blob/master/README.md#building-deviltuionx-32-bit-on-64-bit-linux-multilib-platforms

Your MPQ is from EU/Mac/GoG and so should work excellently.

Glad you are excited about the project :)

**Comment by CubeTheThird** [comment] 2019-03-23 19:01
You are exactly right, and thankfully the AUR package just got updated to allow for multilib installs. The game seems to run normally now, as expected.

Also, interesting to see the MPQ has falling under that category, since this one was taken from the original game disc purchased in NA.

**Comment by AJenbo** [comment] 2019-03-23 19:42
I'm not sure I understand what you are referring to in terms of the mpq failing?

**Comment by CubeTheThird** [comment] 2019-03-23 20:07
Looking at the files in the ISO I made, the mpq itself is dated Dec. 4th 1997, however there are also newer items on the disc (most notably the patch) dated Aug. 29th 2001. I'll have to dig up the physical disc and case to find more details.

**Comment by AJenbo** [comment] 2019-04-06 04:02
The 64bit builds are now much improved, the game is somewhat playable, known issues are:
- DRLG_L3PlaceRndSet crashes the game when entering caves
- Monsters and players using lightning causes the game to crash in MI_Lightctrl
- Item data is scrambled, this causes items to initially be unequipped, stores sell random garbage (also true for pickups) and books and potions cannot be used

**Comment by AJenbo** [comment] 2019-05-13 17:54
The game is now mostly playable in 64bit builds. I have updated the original description with the current known issues.

**Comment by AJenbo** [comment] 2019-05-19 13:42
Just fixed the random crashes on startup, this has been a release blocker for 0.4.0 since the issue wasn't full understood, but it turned out to only affect 64bit builds so shoudn't actually have blocked releases.

**Comment by Khyota** [comment] 2019-05-23 06:11
In 64bit multiplayer, clicking New Game will cause the game to freeze after fading to black.

**Comment by AJenbo** [comment] 2019-05-23 16:16
@Predelnik just cleaned up CheckInvPaste which fixed the two issues with moving items in the inventory.

**Comment by AJenbo** [comment] 2019-05-26 16:46
And now DrawSpellList has been fixed. I'm almost sure that the issue with Wirth also applies for 32bit builds, so all that is missing is getting the 64bit builds compatible with 32bit builds :rabbit:

**Comment by MaddTheSane** [comment] 2019-07-01 19:50
In regards to save games: In another project I worked on, the person wrote a pointer to the file that caused loading issues when porting to 64-bit. The pointer itself was unused in the file, but the increase in size of the pointer caused issues when saving/loading a file.

Perhaps something similar is happening in the save code?

**Comment by AJenbo** [comment] 2019-07-01 20:14
Yeah, pointers might be the issue but from what I have looked at so fare the issue is mostly about structure alignment. Wrapping `structs.h` in `#pragma pack(push, 4)` get the thing much further.

**Closed** 2019-08-07 14:21 UTC
Labels: bug
