### ISSUE TITLE
Cancel resurrect/heal other by right clicking

### ISSUE THREAD

**Issue by AJenbo** [diasurgical/devilutionX#4185] opened 2022-03-20 00:47 UTC
When casting heal other/resurrect there is no way to obvious way to cancel it if you don't have anyone to apply the spell to.

Right-clicking should cause the spell to be canceled by resetting the cursor to the normal hand.

**Comment by ephphatha** [comment] 2022-05-15 10:03
I believe this is a duplicate of #4252 and was fixed by #4256

**Closed by ephphatha** 2022-05-15 10:03 UTC
