### ISSUE TITLE
Restarts the system on Old 2DS

### ISSUE THREAD

**Issue by Tescu48** [diasurgical/devilutionX#3454] opened 2021-11-09 15:36 UTC
**Important information**
I downloaded the 3DS release, on my Old 2DS.

**Describe**
On boot, turns off the system, reboots the screen, then shuts down. Pressing X, Y, A and B will bring you back to the HOME Menu. Pressing START will bring you to the FIRM Menu, or Godmode9, and pressing SELECT will bring you to the Luma Menu. Basically a complete restart in each case. The circle pad, shoulder buttons and the D-Pad don't do anything.

**To Reproduce**
1. Launch the game from the HOME Menu

**Expected behavior**
To run as advertised and intended.

**Screenshots**
I don't have any.

**Additional context**
Maybe I am missing files, I only have DIABDAT.MPQ.

**Comment by StephenCWills** [comment] 2021-11-09 16:30
The title says Old 3DS, but your description says Old 2DS. Did you test with 3DS or 2DS?

**Comment by Tescu48** [comment] 2021-11-09 20:25
> The title says Old 3DS, but your description says Old 2DS. Did you test with 3DS or 2DS?

I used a 2DS. And it's the same thing besides the 3D. The specs and features are the same.

**Comment by StephenCWills** [comment] 2021-11-09 20:35
> I used a 2DS. And it's the same thing besides the 3D. The specs and features are the same.

FYI, the game works fine on my Old 3DS so either there were multiple revisions with different specs or the 2DS actually doesn't have the exact same specs. Regardless, there is another issue reported here that seems to be exclusive to the Old 2DS, and I had a suspicion that it might be relevant so I needed clarification. Can you please try using the build from #3455?
https://70551-143324737-gh.circle-artifacts.com/0/devilutionx.cia

**Comment by Tescu48** [comment] 2021-11-09 21:29
> > I used a 2DS. And it's the same thing besides the 3D. The specs and features are the same.
> 
> FYI, the game works fine on my Old 3DS so either there were multiple revisions with different specs or the 2DS actually doesn't have the exact same specs. Regardless, there is another issue reported here that seems to be exclusive to the Old 2DS, and I had a suspicion that it might be relevant so I needed clarification. Can you please try using the build from #3455? https://70551-143324737-gh.circle-artifacts.com/0/devilutionx.cia

All spec sheets list both as having the same specs and all 3ds games (apart from ones exclusive to the new category) function properly. And no there were no revisions. But I'll try tomorrow the build to see if it works.

**Comment by StephenCWills** [comment] 2021-11-09 22:55
> All spec sheets list both as having the same specs and all 3ds games (apart from ones exclusive to the new category) function properly. And no there were no revisions.

I think I see what you're talking about. Apart from the obvious, they do indeed appear to have nearly the same specs.

> https://en.wikipedia.org/wiki/Nintendo_2DS#Hardware
> The Nintendo 2DS's hardware specifications are almost identical to those of the Nintendo 3DS; retaining features such as its GPU, CPU and memory, along with compatibility with games designed for the Nintendo DS and Nintendo 3DS.

However, as far as this is discussion's relevance to DevilutionX, I feel the point about o2DS having a single LCD screen to be a rather important distinction as far as #3444 is concerned.

> Unlike the Nintendo 3DS, which uses two display panels, with a lower touchscreen panel and a top dual-layered screen panel capable of displaying autostereoscopic 3D, the Nintendo 2DS uses a single, non-stereoscopic LCD touchscreen, which is overlaid with a frame mimicking the screen dimensions of the 3DS.

I do have a strong suspicion that the game is indeed crashing your console, and I don't think that has anything to do with any distinction between o2DS and o3DS. However, you cannot see what's happening on screen during the crash because of the aforementioned screen issue (#3444) that seems to apply only to o2DS. Note that the user who reported that issue also reported that the game otherwise plays fine on o2DS. So, given what you've said about there having been no hardware revisions, there's a good chance we can resolve your issue if we can figure out what's going on with the screen.

Also, to be clear, I do not own an o2DS so I can't reproduce your issue at all. The build from #3455 is a rather blind attempt at solving #3444. I don't expect this to solve the crash, although there is a chance that it might. All I'm really hoping for is that you'll be able to see the screen so we can actually troubleshoot the crash.

**Comment by AJenbo** [comment] 2021-11-10 00:30
Is the device firmware up to date?

**Comment by Tescu48** [comment] 2021-11-10 07:24
> Is the device firmware up to date?

Yep 11.15

**Comment by Tescu48** [comment] 2021-11-10 07:25
> > All spec sheets list both as having the same specs and all 3ds games (apart from ones exclusive to the new category) function properly. And no there were no revisions.
> 
> I think I see what you're talking about. Apart from the obvious, they do indeed appear to have nearly the same specs.
> 
> > https://en.wikipedia.org/wiki/Nintendo_2DS#Hardware
> > The Nintendo 2DS's hardware specifications are almost identical to those of the Nintendo 3DS; retaining features such as its GPU, CPU and memory, along with compatibility with games designed for the Nintendo DS and Nintendo 3DS.
> 
> However, as far as this discussion's relevance to DevilutionX, I feel the point about o2DS having a single LCD screen to be a rather important distinction as far as #3444 is concerned.
> 
> > Unlike the Nintendo 3DS, which uses two display panels, with a lower touchscreen panel and a top dual-layered screen panel capable of displaying autostereoscopic 3D, the Nintendo 2DS uses a single, non-stereoscopic LCD touchscreen, which is overlaid with a frame mimicking the screen dimensions of the 3DS.
> 
> I do have a strong suspicion that the game is indeed crashing your console, and I don't think that has anything to do with any distinction between o2DS and o3DS. However, you cannot see what's happening on screen during the crash because of the aforementioned screen issue (#3444) that seems to apply only to o2DS. Note that the user who reported that issue also reported that the game otherwise plays fine on o2DS. So, given what you've said about there having been no hardware revisions, there's a good chance we can resolve your issue if we can figure out what's going on with the screen.
> 
> Also, to be clear, I do not own an o2DS so I can't reproduce your issue at all. The build from #3455 is a rather blind attempt at solving #3444. I don't expect this to solve the crash, although there is a chance that it might. All I'm really hoping for is that you'll be able to see the screen so we can actually troubleshoot the crash.

Kudos to you, it boots. The problem now is that it doesn't read diabdat.mpq neither spawn.mpq.

**Comment by StephenCWills** [comment] 2021-11-10 13:13
I'm assuming, based on discussions on Discord, that you were able to get the game working with a bit more troubleshooting. I'm closing this issue now, but keep in mind that #3444 is still open because it hasn't been fixed in master so I would definitely not recommend trying any other test builds at this time.

**Closed by StephenCWills** 2021-11-10 13:13 UTC
