### ISSUE TITLE
Since #1314 was merged windows 32-bit no longer launches.

### ISSUE THREAD

**Issue by Trihedraf** [diasurgical/devilutionX#1399] opened 2021-04-07 11:01 UTC
Since #1314 was merged windows 32-bit no longer launches. I tried 64-bit and it launches just fine but 32-bit doesn't even pop-up a window and when ran in a terminal it doesn't saying anything it just immediately goes back to the prompt.

**Comment by AJenbo** [comment] 2021-04-07 11:14
How do you build it?

@glebm might want to look at this.

**Comment by Trihedraf** [comment] 2021-04-07 11:16
My Ubuntu server with mingw and also downloaded the circleci builds

**Comment by AJenbo** [comment] 2021-04-07 11:20
This might be related, this is from MSVC 2019 trying to build for 32bit:```

Severity    Code    Description    Project    File    Line    Suppression State
Error    LNK2001    unresolved external symbol _SFileSetFilePointer    H:\DiabloHD\devilutionX\build\x86-Release\devilutionX    H:\DiabloHD\devilutionX\build\x86-Release\storm_sdl_rw.cpp.obj    1    
Error    LNK1120    1 unresolved externals    H:\DiabloHD\devilutionX\build\x86-Release\devilutionX    H:\DiabloHD\devilutionX\build\x86-Release\devilutionx.exe    1    
```

**Comment by AJenbo** [comment] 2021-04-07 14:04
Alright the problem is definitely related to the use of SFileSetFilePointer, if I comment everything related to that it gets up and running on W32

**Comment by glebm** [comment] 2021-04-07 18:48
Should be fixed by the PR above

**Closed** 2021-04-07 18:48 UTC
