### ISSUE TITLE
Use a selfhostable service for multiplayer

### ISSUE THREAD

**Issue by ata-star** [diasurgical/devilutionX#3899] opened 2022-01-05 20:57 UTC
**Important information**
Operating system Any / DevilutionX version 1.3.0

**Describe**
It it still impossible to use this game in a private network (VPN) or avoid 3rd public services (Zero Tier)
Currently the TCP protocoll is unable to use a VPN and thats why ZeroTier (a proprietary service that is hardcoded to the mastersver of ZeroTier, Inc.)

**Expected behavior**
Use a "master server" or something sefhostable to use multiplayer, jeez

**Comment by sniffingsugar** [comment] 2022-01-05 21:04
We definitely need this feature!

**Comment by StephenCWills** [comment] 2022-01-05 21:31
It's unclear what the issue is here.

Multiplayer is peer-to-peer. TCP is already "self-hostable" in the sense that peers connect directly to each other and all traffic is routed through the host. This can be used through a VPN, although it might be tricky or impossible to set it up if you're using a third-party VPN service.

ZeroTier only hosts the network hypervisor over which peers communicate. There is no "mastersver". Games are all peer-to-peer on the ZeroTier network and are therefore fundamentally "unhostable".

I suppose what you're hoping for is that we'll create a game hosting service that can run on a server somewhere so that all game clients can connect out to the game server so I'll answer based on that assumption. I'm sorry to say that I think we're fairly satisfied with the functionality of the ZeroTier network so I don't believe this is on the roadmap for this project. But several people have mentioned this before so maybe someone will eventually be convinced to pour the effort in to making it happen.

**Comment by AJenbo** [comment] 2022-01-05 22:02
I'm not exactly sure what you are referring to here, but it is actually possible to selfhost a ZeroTier network, so that should for fill the request.

> It it still impossible to use this game in a private network (VPN) or avoid 3rd public services (Zero Tier)

TCP games should work perfectly fine with in a VPN

> Currently the TCP protocoll is unable to use a VPN and thats why ZeroTier

This is not a full sentience. Are you having issues with getting some VPN working for you?

Closing since it's rather unclear what the issue is about, feel free to update it with the full information.

**Closed by AJenbo** 2022-01-05 22:02 UTC

**Comment by ata-star** [comment] 2022-01-09 12:04
thanks for nothing i guess
