### ISSUE TITLE
spell cost are too low

### ISSUE THREAD

**Issue by Hellman6969** [diasurgical/devilutionX#1698] opened 2021-04-25 17:16 UTC
**Important information**
Operating system / DevilutionX version / did you download a release or did you compile yourself?
w10 x64 / 1.2.1 / download a release

**Describe**
when i play my magician (diablo 1 without hellfire) my spell cost not a lot of mana. I means, i very low cost.
I try my savegame on vanilla diablo 1 from my CD (v1.09) and all spell cost a lot of more mana.
For exemple, "heal" lvl 11 cost 4 mana, heal lvl 12 cost 3 in 1.2.1.
In diablo 1.09 it's "heal" lvl 11 = 18 mana, lvl 12 = 12 mana.
Same problem for all spells.
suddenly the game becomes much easier lol

i play in "normal" difficulty, so it's should be like diablo 1.09, no ?

And i saw a lot of spell who make the same damage to lvl 1 to lvl 4-5-6 (where i'm actually in the game) i think it's strange but when i use my savegame on diablo 1.09 the damages dont change so maybe it's ok...

**Comment by StephenCWills** [comment] 2021-04-25 17:25
I believe this was fixed in master recently. #1613

**Comment by AJenbo** [comment] 2021-04-25 18:15
@Hellman6969 could you check the latest beta: https://35066-143324737-gh.circle-artifacts.com/0/devilutionx_x64.zip

**Comment by Hellman6969** [comment] 2021-04-25 18:35
> 
> 
> @Hellman6969 could you check the latest beta: https://35066-143324737-gh.circle-artifacts.com/0/devilutionx_x64.zip

I just tested, everything seems OK in the beta, good job

**Comment by julealgon** [comment] 2021-04-28 00:31
Is this a duplicate of #1611?

**Comment by AJenbo** [comment] 2021-04-28 00:59
> Is this a duplicate of #1611?

Yeah it was fixed by #1613.

**Closed by AJenbo** 2021-04-28 00:59 UTC
