### ISSUE TITLE
Default controller scheme does not match layout in wiki

### ISSUE THREAD

**Issue by and00r** [diasurgical/devilutionX#5438] opened 2022-10-26 18:06 UTC
### Operating System

Windows x64

### DevilutionX version

1.4.1 (latest release)

### Describe

Title of this issue says it all.

The A/B/X/Y buttons seem to be completely rearranged. 
And on further testing it seems many other bindings are also different.

Im using a standard Xbox Series X controller

### To Reproduce

Play the game

**Comment by StephenCWills** [comment] 2022-10-26 18:23
I am unable to reproduce. FYI, the wiki says it uses Nintendo layout.

![image](https://user-images.githubusercontent.com/9203145/198105561-67c21f91-e07e-433f-a61c-3f54b598fb6f.png)

I'm going to assume "completely rearranged" means A is swapped with B and X is swapped with Y and close this issue. Please provide more details if you still think there is an issue.

**Closed by StephenCWills** 2022-10-26 18:23 UTC

**Comment by StephenCWills** [comment] 2022-10-26 18:52
> This is not exactly intuitive for an xbox controller

The Xbox control scheme wouldn't really be intuitive for handheld devices with button layouts based on GameBoy or Switch so this is what we went with. You may be interested to know that we're actively working to improve this situation for 1.5.0.
