### ISSUE TITLE
It costs 39 gold to repair nothing

### ISSUE THREAD

**Issue by bvs23bkv33** [diasurgical/devilutionX#4918] opened 2022-07-08 18:35 UTC
Debian 11.4 / DevilutionX 1.4 / downloaded devilutionx-linux-x86_64.appimage
![Знімок з 2022-07-08 21-16-14](https://user-images.githubusercontent.com/7599687/178050775-313098c9-b60b-40a8-aae9-1b4b85b21863.png)
press enter
![Знімок з 2022-07-08 21-16-20](https://user-images.githubusercontent.com/7599687/178051215-535177d5-f75c-45ac-8762-f5f0262a7ba2.png)
press enter again
![Знімок з 2022-07-08 21-16-24](https://user-images.githubusercontent.com/7599687/178051251-11252675-ae3f-4b62-b058-c861d40305cd.png)

**Comment by tsunamistate** [comment] 2022-07-08 19:57
Hello, is your inventory empty when you reproduce this?
In the main menu, in bottom left corner, there's a DevilutionX version, could you please post it here?
Could you please provide a save?

**Comment by bvs23bkv33** [comment] 2022-07-08 20:08
I think, my inventory was empty then
v1.4.0
[multi_0.zip](https://github.com/diasurgical/devilutionX/files/9074799/multi_0.zip)
It is not reproducing now, in this save, it only happened twice earlier, a couple of hours ago

**Comment by ephphatha** [comment] 2022-07-09 02:00
Did you have a cursed item equipped or in your inventory? https://github.com/diasurgical/devilutionX/issues/4575 will be fixed when the 1.4.1 release comes out and my be the cause of this one.

**Comment by bvs23bkv33** [comment] 2022-07-09 05:55
Maybe, but i said it happened twice, maybe first time i had cursed item but second case was without it

**Comment by kphoenix137** [comment] 2023-08-25 21:58
Issue was fixed by https://github.com/diasurgical/devilutionX/pull/4576

**Closed by kphoenix137** 2023-08-25 21:58 UTC

**Comment by AJenbo** [comment] 2023-08-25 22:18
Good catch :)
