### ISSUE TITLE
Cursor disappears while playing Diablo/Devilution on Debian 10 with QEMU emulator

### ISSUE THREAD

**Issue by SugarRayLua** [diasurgical/devilutionX#2553] opened 2021-08-10 05:32 UTC
**Important information**
Operating system Debian 10
DevilutionX version 1.2.1  
ARM64 emulated using QEMU 6.1
Compiled from source

**Describe**
Game runs fine except for major bug that cursor never appears during start of Diablo play. Game seems to sense mouse movement since character moves when move mouse but unable to see cursor on screen to help aim movement or adequately fight monsters. Notably cursor appears offscreen in Debian desktop if move off of Diablo/DevilutionX game screen.

Doesn't seem to be a Debian or QEMU ARM64 emulator issue since other games display the mouse cursor fine during play on the same system. 

**To Reproduce**
Start game. No cursor appears during the entire game play. However, game still responds to mouse movement. 

**Expected behavior**
Expect cursor to appear on the screen to help guide fighting and movement as it did in the originally released Diablo game on PC. 

**Screenshots**
N/a

**Additional context**
May be something unique to ARM64 or QEMU. I apologize if there is a known patch or fix that I didn't see online. 

Thanks!

**Comment by StephenCWills** [comment] 2021-08-10 05:44
This sounds like a duplicate of #2445. Can you share what commit you were on when you compiled?

**Comment by AJenbo** [comment] 2021-08-10 05:45
>  DevilutionX version 1.2.1

did you compile theactual 1.2.1 version (3e61cb82696345a0cf5cc80123940854f79e672d) or some more recent development version?

**Comment by ThomasChr** [comment] 2021-08-10 05:55
Did you try to disable Hardware Cursor in diablo.ini?

**Comment by SugarRayLua** [comment] 2021-08-11 02:27
Wow, I am so impressed with the promptness of everyone’s response!

ThomasChr’s solution actually worked perfectly! I disabled the Hardware Cursor in diablo.ini, and the cursor appeared and the game plays perfectly :-) Perhaps you might want to mention that as a suggestion to others on the documentation?

To answer everyone else’s questions:

I believe I compiled the actual 1.2.1. version. (I apologize, I am new to Linux and don’t know how specifically to determine the exact version I compiled. I used git clone from the DevilutionX to build from source site on 7/31/2021, and the screen says 1.2.1 version when I play the game.)

Of note, in regards to issue #2445, my Debian 10 institution also uses the older SDL2 version (2.0.9), and, as mentioned with ThomasChr’s fix, work fine.

Thank you all and the Devilution team for your hard work on this project. I played the original Diablo for hours when it first came out on PC. However, due to my mobile work schedule, I now primarily use an iPad Pro, and now again can play Diablo on my iPad Pro using Devilution! (UTM app port of QEMU sideloaded to my iPad Pro running Debian 10 on ARM64 framework and recently patched to be able to use iPad’s graphic acceleration). :-) 

Please feel free to close if you have now further questions of me and each of you have a great rest of your week.

**Comment by StephenCWills** [comment] 2021-08-11 03:01
> I believe I compiled the actual 1.2.1. version. (I apologize, I am new to Linux and don’t know how specifically to determine the exact version I compiled. I used git clone from the DevilutionX to build from source site on 7/31/2021, and the screen says 1.2.1 version when I play the game.)

FYI, the version number 1.2.1 is typically used around here to refer to the release version rather than the latest master. When building from source, it's better to go by the commit ID or else we won't be able to determine what version of the codebase you tested. The fix for #2445 was merged Aug 5, so on Jul 31 you would still have been subject to the bug. The code fix just changes the default value in diablo.ini, so by changing the value manually, you should be in good shape.

I'm closing this issue as a duplicate of #2445.

**Closed by StephenCWills** 2021-08-11 03:01 UTC

**Comment by ThomasChr** [comment] 2021-08-11 06:17
@SugarRayLua I had the same problem a few days ago. So that was a no-brainer :-)
Yes, the community here does seem to be very helpfull and kind. I like that very much.
Unfortunately I'm not a big contributer at the moment but I like that to change. If you have any questions I would gladly try to answer them.

**Comment by AJenbo** [comment] 2021-08-11 10:10
> I used git clone

That would give you the latest test version of that time, to get 1.2.1 specifically you will need to also do `git checkout 1.2.1`, 1.2.1 did not even have a hardware cursor so we can be sure that is not what you where running :) It's understandable that it can be a bit misleading since develop versions still show the version number from the most recent release.

**Comment by SugarRayLua** [comment] 2021-08-11 14:08
Thank you very much! 

Have a good rest of your week.

Sincerely,

Mike

**Comment by SugarRayLua** [comment] 2021-08-11 14:09
Thank you for clarifying,

Mike
