### ISSUE TITLE
[Issue Report]: Incorrect hero alignment with petrified monsters

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#7472] opened 2024-10-10 07:08 UTC
### Operating System

Linux x64

### DevilutionX version

Custom build (commit 181247924b6ffe4d25b6988f3b1c0e4965399247)

### Describe

While playing the hero very often does not face the monster in battle.
In 1.4.0 it looks normal and needs to be narrowed down further.

![1](https://github.com/user-attachments/assets/6a547fa7-bcd8-4210-a39b-6a95e04b0951)
![2](https://github.com/user-attachments/assets/bbbbbbf1-45b0-4dd3-be23-f1bda4000f08)

### To Reproduce

1. Load attached game.
[stone.zip](https://github.com/user-attachments/files/17324429/stone.zip)
2. Only play with Stone curse and pay close attention to whether the hero is looking towards the monster when hitting.
3. Unfortunately, it doesn't always happen and it's not easy to determine whether the issue is occurring.
If necessary, play longer to determine the issue by continuing to play
4. You should notice from time to time that the alignment is not correct.

### Expected Behavior

The hero should always look in the direction of the monster when hitting

### Additional context

In 1.5.3 things already look bad in this regard

**Comment by julealgon** [comment] 2024-10-10 15:26
Interesting that this would only happen with stone cursed monsters... apparently, the monster was moving while he got petrified, and for whatever reason his position was set to the target tile, which is what the hero is targeting?

**Comment by Chance4us** [comment] 2024-10-10 18:23
Yes, just as you describe it seems to be.
This also seems to be related to timing and is not easy to isolate the issue.
It will take time.

**Comment by kphoenix137** [comment] 2024-10-10 19:21
Is it possible to walk into the tile that you seemingly attempt to attack?

**Comment by kphoenix137** [comment] 2024-10-10 19:54
![image](https://github.com/user-attachments/assets/f7f0ff69-3367-45b1-a6c5-6ff61f1b1052)

I'm under the impression it's intentional that the player attacks facing the tile that the monster is walking into. Consider this:

![image](https://github.com/user-attachments/assets/08748dfd-7eec-4e7c-bcac-4bfcc387c0fd)

If the player was attacking the originally occupied tile of the monster, the player would begin pathfinding to the side of the monster in an attempt to reach the tile they're exiting. Normally you wouldn't notice this behavior, but it becomes much more apparent then you stone curse a monster that's in the beginning stage of moving into the next tile.

**Comment by kphoenix137** [comment] 2024-10-10 20:26
So it is by design that the player pathfinds to the tile the monster is moving into, and faces that tile when starting an attack. Although the game technically *does* allow you to hit a target successfully by attacking the tile they're moving out of. 

We could introduce logic that forces the player to conditionally target a tile based on walk progress, rather than consistently always the future tile. It may result in some cases where the player swings at nothing, but still might be worth it, as there could be many cases where the player can successfully hit the target instead of beginning a pursuit.

**Comment by kphoenix137** [comment] 2024-10-10 21:11
> > We could introduce logic that forces the player to conditionally target a tile based on walk progress, rather than consistently always the future tile. It may result in some cases where the player swings at nothing, but still might be worth it, as there could be many cases where the player can successfully hit the target instead of beginning a pursuit.
> 
> A more intelligent pathing for melee attacks could fix one of your bigger gripes about Hellfire, I guess. Ranged attacks should probably continue to target the future tile.

Working on this right now

**Comment by julealgon** [comment] 2024-10-10 21:50
Slightly related to this:
- https://github.com/diasurgical/devilutionX/issues/801

SHIFT-Attacking doesn't track the monster and thus performs an attack against the current tile instead of future tile.

@kphoenix137 I suspect your proposed change will align the behaviors unexpectedly, but maybe in a worse way (read on).

I'll be honest here... I've always preferred the tracking behavior. It is super noticeable when you are fighting a pack of fallen around you: if you try to kill them with SHIFT-Attack (non-tracking), it results in much worse hit chance than doing normal (tracking) attacks.

IIRC the only difference between the 2 is that shift+attack does not pass the monsterID while normal attack does.

I had proposed before that SHIFT+Attacking should also be tracking if you do so on top of a monster.

**Comment by kphoenix137** [comment] 2024-10-11 00:01
Should we close this? The game is working as intended and this isn't a bug.

**Comment by StephenCWills** [comment] 2024-10-11 00:24
Yes, I think so.

**Closed by StephenCWills** 2024-10-11 00:24 UTC

**Comment by Chance4us** [comment] 2024-10-11 05:33
I'm glad it's not a bug, even if it's hard to believe. :yum:

**Comment by StephenCWills** [comment] 2024-10-11 13:40
> I'm glad it's not a bug, even if it's hard to believe. 😋

You said it looks correct in 1.4.0, but it appears to work the same way to me. I actually have a hard time believing anything has changed with regard to attacking future tiles.

**Comment by julealgon** [comment] 2024-10-11 14:42
@Chance4us are you consistently using normal attack or shift+attack in your tests? Keep in mind it makes a difference (check my linked issue for more details on that).

**Comment by kphoenix137** [comment] 2024-10-11 16:57
> I'm glad it's not a bug, even if it's hard to believe. 😋

Basically, when a monster is walking, it is occupying 2 tiles at the same time. in the `dMonster` array, the positive monster index indicates it's the tile they're originating from, and the negative monster index indicates it's the tile they're moving into. Targeting always takes into account the future tile always to avoid "whiffing" as julealgon put it.

Using this knowledge, in the circumstance that a monster just began moving into another tile and is stone cursed, it will look like you are facing the wrong direction. if you stone curse the monster when it's over halfway into the destination tile, then it will look correct. If we changed it to use the original tile to target, that means when you stone curse a monster near the beginning of the walk animation, it will look correct, and when it's over halfway, it will look incorrect.

The PR that I opened made it so the targeted tile for an attack would choose whichever tile the monster is most inside, however this can create a scenario where a slower attacking character (even a warrior without a speed boost) may end up swinging at a monster that's fleeing and ending up with a 0% chance to hit. A potential alternative to having to do a bunch of special handling for this would be simply changing the facing direction to the tile the monster is most inside, however that's not entirely ideal either, because your attack is targeting a tile you're no longer facing. Applied to bows, this would result in arrows visually shooting in the wrong direction.

The problem is that the game uses such a big tile system and only has 8 facing directions. If it was more like d2, or hit detection didn't use a tile grid at all, then this wouldn't be an issue.
