### ISSUE TITLE
Diablo Hellfire support

### ISSUE THREAD

**Issue by mbreskovec** [diasurgical/devilutionX#52] opened 2019-03-22 23:17 UTC
Current known issues.
- [x] Barrels and other objects are missing from the hive and crypt.
- [x] Na-Krul doesn't spawn.
- [x] Store menus aren't correct
- [x] Some instability
- [x] Town doesn't update when opening crypt and hive
- [x] Runes have no effect
- [x] Corner Stone of The World doesn't work
- [x] Not compatible with Hellfire save games
- [x] The support screen is missing.
- [x] Clicking ESC goes to the support screen instead of Quit Hellfire
- [x] Description for Loopback is that of UDP
- [x] Griswold will buy random belt items.
- [x] Items morph (multiplayer, new single-player, slain hero issues are all caused by this) #981
- [x] Multiplayer hero save/load (currently only Diablo saves are supported for multiplayer)

**Comment by AJenbo** [comment] 2019-03-22 23:45
Hi @mbreskovec 

We probably will incorporate some of the changes from Hellfire (like map in town). The expansion issn't universally liked (especially not by the original developers). Most likely it will be added as a mod for DevilutionX once we get that going, it would form a pretty good proving grounds for that goal.

As for your question about translation, yes defiantly, i think we will aim for a multilingual program so that users can switch the language instead of the current solutions floating around out there where the exe has been hex edited to a specific language.
The only real limitation here is that the font in Diablo is ISO_8859-1 so there some limitations of how well different languages can be represented.
https://en.wikipedia.org/wiki/ISO/IEC_8859-1#Modern_languages_with_complete_coverage

**Comment by mewmew** [comment] 2019-06-08 02:13
Related to this issue, the GoG release now includes Hellfire: https://www.gog.com/game/diablo

**Comment by galaxyhaxz** [comment] 2019-06-08 10:55
`hellfire.exe` v1.01 has been completely mapped out in the scalpel repo, surprisingly there were very few functions added/changed. The DRLG code is just a slight hack of the original. Only complex part is all the new code for the missiles.

**Comment by mewmew** [comment] 2019-06-08 10:56
> hellfire.exe v1.01 has been completely mapped out in the scalpel repo, surprisingly there were very few functions added/changed. The DRLG code is just a slight hack of the original. Only complex part is all the new code for the missiles.

Sounds like a weekend hackathon to me! :)

**Comment by AJenbo** [comment] 2019-06-08 10:57
@mewmew I'll come visit you for this one :D

**Comment by galaxyhaxz** [comment] 2019-06-08 10:59
Well then I'll have to show up and crash the party xDDDDDDDDD

**Comment by mewmew** [comment] 2019-06-08 10:59
> @mewmew I'll come visit you for this one :D

Definitely!!

**Comment by mewmew** [comment] 2019-06-08 10:59
> Well then I'll have to show up and crash the party xDDDDDDDDD

You are always welcome Andi! <3

**Comment by ZaDarkSide** [comment] 2019-08-04 11:22
Well just add a Sponsor button, I will gladly throw in some money for the Hellfire mod support.

**Comment by mewmew** [comment] 2019-08-04 13:23
> Well just add a Sponsor button, I will gladly throw in some money for the Hellfire mod support.

Regarding a sponsor button, this has been discussed before. And to avoid any risk of associating Devilution with monetary gain the option of donations has been decided against. Thanks for the will to help out though!

>  Maybe your hackathon will have some beer included.

Haha, as the hackathon happens in Sweden we will most likely have tea and a cinnamon bun, proper [FIka style](https://www.youtube.com/watch?v=oRIeytEXGhQ)!

**Comment by cmhobbs** [comment] 2019-08-04 14:23
I'd love to see hellfire support as well and I was going to ask about a donation button, too.   I just discovered this project so I wish I could help.  I'll see if I can make sense of the source and figure out how it works but this is all very new to me.

Also, thanks a ton for Devilution.  It's so nice to be able to revisit Diablo!

**Comment by MBeijer** [comment] 2019-08-04 15:56
@mewmew Where in Sweden? ^^

**Comment by galaxyhaxz** [comment] 2019-08-05 00:37
> we will most likely have tea and a cinnamon bun, proper FIka style!

Oh, will Hallondricka be included as well? :P

> I'll see if I can make sense of the source and figure out how it works but this is all very new to me.

Cool, would be great to have you join the project. Prepare for an addiction that leads to a gloomy fate and be bound by the chains of code archaeology!

I thought about working on Hellfire support. The issue was that a different compiler was used and some structs were dynamically allocated. We can probably `ifdef` this for the main project and include a separate .DSP for VC 5.10, but then that leaves the issue of being based on 1.04 vs. 1.07. Most of hellfire's code changes were trivial, with the addition of new missiles being the only complex part.

**Comment by cmhobbs** [comment] 2019-08-05 01:52
> Cool, would be great to have you join the project. Prepare for an addiction that leads to a gloomy fate and be bound by the chains of code archaeology!
> 

No promises but I'm already digging through the codebase.  I've only recently picked up C++ for work and I know nothing about how Diablo or Hellfire behave but the source is interesting at least!

**Comment by OrangBuangan** [comment] 2019-08-05 11:05
@galaxyhaxz I think it would be ok to have hellfire build on 1.09 even if not bin exact, or are you saying that it makes it harder to see what hellfire changed?

**Comment by mewmew** [comment] 2019-08-06 07:39
> @mewmew Where in Sweden? ^^

Hi @MBeijer!

We are meeting up in Stockholm. If you happen to be close to the area, feel free to join the Devilution Fika Hackathon :)

Cheers,
Robin

**Comment by galaxyhaxz** [comment] 2019-08-06 08:14
>  it makes it harder to see what hellfire changed?

Yeah basically. Not only do the changes between 1.04 and 1.07 have to be differentiated, but Sierra also released patch 1.01, which addressed many bugs including some that were fixed in 1.07. And it may have been done differently. More look at the code is needed before we decide, but hopefully we can add it to the base project.

> We are meeting up in Stockholm

Is it going to be later this year? Not that I can attend sadly, still gotta do the whole 9 month passport thing lol. Would be super edgy though!!

**Comment by mewmew** [comment] 2019-08-06 08:29
> Is it going to be later this year? Not that I can attend sadly, still gotta do the whole 9 month passport thing lol. Would be super edgy though!!

Yeah, the first of many Fika hackathons is in a few weeks/a month or two :)

**Comment by MBeijer** [comment] 2019-08-06 10:27
@mewmew I'm relatively close and I travel to Stockholm pretty often. :) Would be fun to join up for a fika-hackaton!

**Comment by AJenbo** [comment] 2019-09-15 14:36
We had a grate second hackathon, 64bit support is now done and the road ahead is more clear. Hellfire support is also well underway!

**Comment by mewmew** [comment] 2019-09-15 18:51
>> @mewmew I'm relatively close and I travel to Stockholm pretty often. :) Would be fun to join up for a fika-hackaton!
>
> We had a grate second hackathon, 64bit support is now done and the road ahead is more clear. Hellfire support is also well underway!

@MBeijer you are most welcome to join future hackathons :) Anders came up the last week to Stockholm and we did a lot of hacking together. This is but one of many fika hackathons we will be hosting :)

**Comment by Yorper** [comment] 2019-11-24 13:03
Very excited for this. Thanks for all your hard work guys/girls.

**Comment by cpgrant2482** [comment] 2020-01-17 22:44
Just stirring the pot a bit :)  Has there been any recent developments on Hellfire support?  If it gets added in, I'd love to try it out.

**Comment by qndel** [comment] 2020-01-17 22:45
![image](https://user-images.githubusercontent.com/14297035/72651373-708cdc00-3983-11ea-9a6b-6d1ac7817628.png)
I'd suggest joining discord for staying up to date :D also nice timingg haha

**Comment by cpgrant2482** [comment] 2020-01-17 22:47
Awesome!  Thanks for pointing this out!

**Comment by qndel** [comment] 2020-01-17 22:48
discord.gg/aQBQdDe 
:)

**Comment by AJenbo** [comment] 2020-10-12 12:45
Hellfire has now been merged and a menu has been build for it, at this point trying it out is as easy as:
`cmake .. -DHELLFIRE=ON
make -j4`

Current known issues.
- Barrels and other objects are missing.
  -Na-Krul doesn't spawn.
- Store menus aren't correct
- Some instability
- Town doesn't update when opening crypt and hive
- Runes have no effect
- Corner Stone of The World doesn't work
- Not compatible with Hellfire save games
- The support screen is missing.
- Clicking esc goes to the support screen instead of Quit Hellfire
- Description for Loopback is that os UDP

https://github.com/diasurgical/devilutionX/pull/876

**Comment by AJenbo** [comment] 2020-10-13 00:15
If anyone has some original Hellfire savegames they would be willing to donate then that would be very helpful for testing.

**Comment by spitfire** [comment] 2020-10-13 00:22
There you go 
https://www.dropbox.com/s/t0ho76gjuthguu0/single_0.hsv?dl=0

https://www.dropbox.com/s/vn9oam0vz3s57uj/single_1.hsv?dl=0

**Comment by AJenbo** [comment] 2020-10-13 01:07
@spitfire any chance you can upload them here on github so i don't have to create a dropbox account :)

**Comment by AJenbo** [comment] 2020-10-13 01:37
Any multiplayer saves out there :)

Should be called something like `hrinfo_%d.drv`

**Comment by AJenbo** [comment] 2020-10-13 02:27
![image](https://user-images.githubusercontent.com/204594/95808299-76de9780-0d0c-11eb-831d-29984a5bf940.png)

**Comment by AJenbo** [comment] 2020-10-13 03:21
@spitfire you can now start new games using your existing Hellfire heros. Loading a save game will fail atm, and hellfire spell levels are set to 0. Could you verify the equipment and other hero stats are correct? I can already say that there are some issues with items but need to know what it is supposed to look like before I can easily correct it :)

**Comment by spitfire** [comment] 2020-10-13 07:28
> @spitfire any chance you can upload them here on github so i don't have to create a dropbox account :)

Already had them on there and couldn't upload them again on mobile. They should be public and not require an account, did they?


> @spitfire you can now start new games using your existing Hellfire heros. Loading a save game will fail atm, and hellfire spell levels are set to 0. Could you verify the equipment and other hero stats are correct? I can already say that there are some issues with items but need to know what it is supposed to look like before I can easily correct it :)

You mean I should try to load them in both Hellfire & devilutionX and compare?

**Comment by AJenbo** [comment] 2020-10-13 09:06
Yeah i figured it out, one of the buttons didn't require an account. They are on git hub now for future usage.

If you can compare that would be helpful, but just a screen shot of your stats and inventory in hellfire would be a bit help in it self :)

**Comment by spitfire** [comment] 2020-10-13 09:33
These are the stats as seen with Hellfire 1.01 I was playing them on:
<img width="642" alt="Zrzut ekranu 2020-10-13 o 11 31 39" src="https://user-images.githubusercontent.com/42872/95843242-c55d5780-0d47-11eb-9f16-f9c34eaee16d.png">
<img width="641" alt="Zrzut ekranu 2020-10-13 o 11 31 13" src="https://user-images.githubusercontent.com/42872/95843252-c7bfb180-0d47-11eb-9986-24838ee32c4e.png">

**Comment by AJenbo** [comment] 2020-10-13 15:02
how about ingame so we see the full stats and items :)

**Comment by spitfire** [comment] 2020-10-13 19:23
> how about ingame so we see the full stats and items :)

<img width="635" alt="Zrzut ekranu 2020-10-13 o 21 22 25" src="https://user-images.githubusercontent.com/42872/95906356-50673d80-0d9a-11eb-86ed-a4c22f896644.png">
<img width="638" alt="Zrzut ekranu 2020-10-13 o 21 21 23" src="https://user-images.githubusercontent.com/42872/95906374-53fac480-0d9a-11eb-96e8-4dfb9462fbfd.png">

**Comment by AJenbo** [comment] 2020-10-13 20:30
The secound savegame you attached appears to be of your Spitfire rouge and not the Sledgehammer barbarian, pretty cool hero though :)

**Comment by spitfire** [comment] 2020-10-13 20:33
Attaching my characters straight from the game dir:

[hsv.zip](https://github.com/diasurgical/devilutionX/files/5373942/hsv.zip)

**Comment by AJenbo** [comment] 2020-10-13 23:09
Looks like most is being loaded correctly, but there are still some issues around items:
![image](https://user-images.githubusercontent.com/204594/95925381-ef4f6200-0db9-11eb-9cdb-1a17690b6391.png)

![image](https://user-images.githubusercontent.com/204594/95925348-e068af80-0db9-11eb-98a3-a86ba5fa8f7c.png)

**Comment by muzena** [comment] 2020-10-21 11:37
@AJenbo 
I compile DevilutionX with [Hellfire support](https://code.launchpad.net/~trebelnik-stefina/+archive/ubuntu/devilutionx).
Then I extract "setup_diablo_1.09_hellfire_v2_(30038).exe" file.
I copied diabdat.mpq to /home/user/.local/share/diasurgical/devilution path.
diabdat.mpq extracted files from "setup_diablo_1.09_(27873).exe" and "setup_diablo_1.09_hellfire_v2_(30038).exe" files are the same size 517.5 MB.
setup_diablo_1.09_(27873).exe file has -> 674.9 MB.
setup_diablo_1.09_hellfire_v2_(30038).exe file has -> 850.1 MB.

When I tried to strat hellfire I get error like in this screenshot:
![diablo error](https://user-images.githubusercontent.com/1978777/96714031-d9393700-13a1-11eb-82a4-b83f6840af55.png)

**Comment by qndel** [comment] 2020-10-21 11:38
do you have hellfire mpq?

**Comment by muzena** [comment] 2020-10-21 11:42
I extract "setup_diablo_1.09_hellfire_v2_(30038).exe" file.
I copied diabdat.mpq to /home/user/.local/share/diasurgical/devilution path.
I extracted according to [wiki instructions](https://github.com/diasurgical/devilutionX/wiki/Extracting-the-DIABDAT.MPQ-from-the-GoG-installer) diabdat.mpq file

**Comment by spitfire** [comment] 2020-10-21 11:43
Hellfire has its own mpq files you need to copy in addition to diabdat

**Comment by muzena** [comment] 2020-10-21 11:46
How do I unpack that file from "setup_diablo_1.09_hellfire_v2_(30038).exe"?

**Comment by qndel** [comment] 2020-10-21 11:47
no idea

**Comment by spitfire** [comment] 2020-10-21 11:48
> How do I unpack that file from "setup_diablo_1.09_hellfire_v2_(30038).exe"?

I don't have the gog  version (this is what you have, right?). If you managed to extract it those files should be next to diabdat if your version does include hellfire.

**Comment by AJenbo** [comment] 2020-10-21 11:50
> How do I unpack that file from "setup_diablo_1.09_hellfire_v2_(30038).exe"?

The exact same way as diabdat.mpq, but replace the file name with the 4 hellfire mpq names.
hellfire.mpq
hfmonk.mpq
hfmusic.mpq
hfvoice.mpq

**Comment by AJenbo** [comment] 2020-12-29 04:54
The save game issues and stores have now been corrected:
![image](https://user-images.githubusercontent.com/204594/103259581-4ff24200-499a-11eb-8f27-556531153cb7.png)

![image](https://user-images.githubusercontent.com/204594/103259570-39e48180-499a-11eb-81fa-c20e1f93a959.png)

**Comment by AJenbo** [comment] 2021-01-02 06:51
We can low load the game save state also, Hellfire support is now considered beta quality.

**Comment by AJenbo** [comment] 2021-01-11 19:31
All player classes are now fully implemented

**Comment by AJenbo** [comment] 2021-01-13 15:15
Diablo save games can now be loaded in Hellfire and Hellfire games can be loaded in Diablo. Items and game state is maintained when transferring the games (Hellfire specific items are lost when loading it's saves in Diablo).

**Comment by AJenbo** [comment] 2021-01-16 02:15
Most stability issues have been fixed, all features are now implemented. 80% of the code has been properly integrated. Test builds will become available once we finish the remaining 20%.

**Comment by ChrisDasinger** [comment] 2021-01-20 22:43
I copied all of the following to the devilutionx-windows-i386 folder:
diabdat.mpq
hellfire.mpq
hfmonk.mpq
hfmusic.mpq
hfvoice.mpq

When I open devilutionx.exe, it starts up basic Diablo without the Hellfire expansion. What am I doing wrong?

**Comment by AJenbo** [comment] 2021-01-25 03:07
Hellfire is now 99% implemented, stability issues have been solved, and the Cornerstone of The World is now functional.

Currently, Hellfire multiplayer heroes will morph when starting a new game, but this should be easy enough to solve.

**Comment by AJenbo** [comment] 2021-01-26 03:27
New test-build: https://15745-143324737-gh.circle-artifacts.com/0/devilutionx_x86.exe

Notable changes:
- Oils are now fully integrated

The only missing part is a bit about how items are being picked up.

**Comment by h3ct0r** [comment] 2021-01-29 21:51
Hi @AJenbo , is there any way to test this build in Linux? If the master HEAD is updated with these hellfire enhancements, I can try to compile the project. PD: Thanks for the hard work!

**Comment by AJenbo** [comment] 2021-01-29 22:45
@h3ct0r this is build from master, it's simply a link to the latest artifact on CircleCI so you can grab on for your system of choice there. I just put the link here as we get a lot of questions like this from windows users

**Comment by muzena** [comment] 2021-01-30 06:30
@h3ct0r 
Which distro do you use?

**Comment by Massi-Daisy** [comment] 2021-01-30 11:03
Hi, I downloaded and compiled the source under Ubuntu 20.04. I absolutely LOVE being able to play Diablo 1 again (and now Hellfire too!), so thank you so much for making this happen!! <3

I thought you might appreciate the feedback... I created a monk, cleared the first level of the cathedral, went to town to pawn some stuff and buy a better staff from Griswold, heard what Lester had to say, and everything went well. Then I clicked on the entrance of the cathedral to go back down and this happened:

INFO: Unhandled SDL event: SDL_AUDIODEVICEADDED 0
INFO: Unhandled SDL event: SDL_AUDIODEVICEADDED 0
INFO: Unhandled SDL event: SDL_TEXTEDITING 0
INFO: SFileOpenFile: Not found: ui_art\hf_titlew.pcx
INFO: Failed to load image meta
INFO: SFileOpenFile: Not found: ui_art\mainmenuw.pcx
INFO: Failed to load image meta
Segmentation fault (core dumped)

Rest assured that I'll be doing a lot more testing :D Thank you guys so much again, you're the best ever!!

**Comment by muzena** [comment] 2021-01-30 11:54
@Massi-Daisy 
You can try install from PPA, for me work without error
https://launchpad.net/~devilutionx/+archive/ubuntu/dev

**Comment by Massi-Daisy** [comment] 2021-01-30 14:56
Thank you, gonna try it now!

**Comment by Massi-Daisy** [comment] 2021-01-30 15:04
Btw, is there a way to enable the bard and barbarian yet? I found an .ini file in the diasurgical folder and tried adding random strings like "bardtest" and "barbariantest=1" but it didn't unlock the classes.

**Comment by Trihedraf** [comment] 2021-01-30 15:11
When launching you have to give it the switches --bardtest --barbariantest. Whether that’s through terminal, a .sh script or adding it to the menu item.

**Comment by Massi-Daisy** [comment] 2021-01-30 15:24
Thank you!
By the way, I still get the segfault + crash even with the package from the PPA. But the workaround still works so I'm happy.

**Comment by h3ct0r** [comment] 2021-01-30 15:43
> @h3ct0r
> Which distro do you use?

I'm using Xubuntu 16.04. I did manage to compile devilutionX after manually installing the latest libsodium version. I'm testing Hellfire right now!

**Comment by Massi-Daisy** [comment] 2021-01-30 16:04
I have another strange experience to relate ;)

I went into town to sell some items. Everything worked mostly as expected. However, the icons for the scrolls and the oils that I had just sold stayed in my inventory. The info box didn't display any text when I hovered the mouse pointer over them, and they poofed when I clicked on them. So I'd say that this glitch is purely cosmetic and doesn't seem to affect gameplay.

**Comment by qndel** [comment] 2021-01-30 16:12
@Massi-Daisy there are some issues before hellfire gets fully integrated, this seems to be one of them

**Comment by Massi-Daisy** [comment] 2021-01-30 17:04
I have noticed that there is definitely something funky going on with scrolls, runes and oils. They have repeatedly disappeared from my inventory and belt (at least slot #8) between saves.
Still, amazing job everyone involved, keep up the awesome work!!

**Comment by AJenbo** [comment] 2021-01-30 17:16
yeah save games have known issues atm, this is probably also why you have crashes when changing levels as it reaads the save when doing so.

**Comment by AJenbo** [comment] 2021-02-21 23:22
Ok things are stabilizing, all bugs should now be fixed and the only missing part is the support screen, here is a new fresh Windows build for anyone testing this:
https://16920-143324737-gh.circle-artifacts.com/0/devilutionx_x64.zip
Not that it is also 64bit now, something I would also like people to test to see if it's good enough for release :)

For Linux, Switch, Vita, 3DS, Amiga, and 32bit Windows please login here with github or build from master: https://app.circleci.com/pipelines/github/diasurgical/devilutionX/3160/workflows/a55919d4-5d57-4cd9-8268-a0ed5ed1bdd7

**Comment by Massi-Daisy** [comment] 2021-02-21 23:47
Amazing!! Thank you so much! I'll try this out as soon as I can!

**Comment by Massi-Daisy** [comment] 2021-02-22 00:48
Nope, I'm still having the bug with the scrolls disappearing from my belt between saves.

I downloaded and installed the updated package from the PPA, created a new monk, went to Adria to buy a healing scroll, put it into the eighth belt slot, saved the game, then loaded, and the scroll was gone. This happens reliably with the eighth slot, but occasionally with other slots too.
It's only with scrolls, runes and oils though, potions appear to be unaffected.

**Comment by AJenbo** [comment] 2021-02-22 00:50
>  updated package from the PPA

I don't know what you are referring to, could you please test the official build that I linked to.

**Comment by Massi-Daisy** [comment] 2021-02-22 00:59
I'm sorry, I guess I'm not very computer literate. I'm trying to figure out how the circleci page works. I see a list of steps with outputs but I can't find a download link.

I am using the PPA that muzena gave me in this thread (https://launchpad.net/~devilutionx/+archive/ubuntu/dev). My package manager says that it's version 1.1.0.

**Comment by Massi-Daisy** [comment] 2021-02-22 01:04
Never mind, found it under "Artifacts". Will download and install now.

**Comment by Massi-Daisy** [comment] 2021-02-22 01:16
Amazing job guys!! Looks like scrolls are being preserved correctly in the belt now between saves. This was a quick test with a new monk and bard. I'll play some more (OK, a lot more) in the next days and let you know.
Thank you so much, and sorry again for being slow on the technical side of things. Kudos to all of you who made this!

**Comment by AJenbo** [comment] 2021-02-22 01:24
@Massi-Daisy thanks for the quick test :)

**Comment by Jarzuul** [comment] 2021-02-23 21:40
I'm not sure if this is DevilutionX / Hellfire related, but I'd like to share this issue with you.

I've tested the DevilutionX version that @AJenbo mentioned 2 days ago. Everything works fine - so far. I've imported my DevilutionX Diablo char by simple renaming the savegame from .sv to .hsv and started the first hellfire quest (Hive - The Defiler).

After defeating the mob "The Defiler" on Level Hive 4, the Quest "The Defiler" is still active and no needed cathedral map is dropping. I've searched for it in the entire level on every pixel but sadly it is not there. Even the quest "The Defiler" is still shown as active.

If this is a known bug with Hellfire itself, I'm sorry for writing these lines.

**Comment by AJenbo** [comment] 2021-02-23 21:57
@Jarzuul thanks, I just did a quick fresh run where the quest definitely works, so this is probably related to converting a D1 game to HF, and I think I have a pretty good idea what the issue is.

**Comment by Jarzuul** [comment] 2021-02-23 22:03
@AJenbo Thanks for your quick reply. If I can support you with my savegame please let me know :)

**Comment by spitfire** [comment] 2021-02-24 09:13
I have tried this on my Switch, Vita and N3DSXL and it seems to be working pretty well :)

**Comment by AJenbo** [comment] 2021-02-24 11:16
@spitfire nice, that good to have all 3 platforms confirmed :) Especially the Switch since it hasn't been tested for a bit.

**Comment by Massi-Daisy** [comment] 2021-02-24 23:04
I've been having a blast with my monk the last couple of days! The cathedral map dropped for me as expected, and I'm in the crypt right now.
The game is fully playable. I've only encountered two small cosmetic glitches so far (when Griswold gave me the Anvil of Fury quest, the text was scrolling way too quickly, and the listed damage for lightning wall is weird), but they don't impact gameplay at all. Fantastic job everybody!!

**Comment by AJenbo** [comment] 2021-02-25 01:43
> the listed damage for lightning wall is weird

in the spellbook? Could you let me know what it is and what it should be?

**Comment by AJenbo** [comment] 2021-02-25 04:59
Ok, Hellfire multiplayer should now be fully working.

@spitfire upgrading your hero from D1 to Hellfire should now work correctly for the new quests (could you test this, with a hero that hasn't been upgraded).

Windows x86_64 build:
https://17247-143324737-gh.circle-artifacts.com/0/devilutionx_x64.zip
Linux x86_64 build:
https://17249-143324737-gh.circle-artifacts.com/0/devilutionx_linux_x86_64
Everything else:
https://app.circleci.com/pipelines/github/diasurgical/devilutionX/3193/workflows/1a36d2d5-1c47-4926-a9cd-457162635b4b

**Comment by Massi-Daisy** [comment] 2021-02-25 07:58
Yes, in the spellbook. According to diablo.fandom.com, the min damage should be 4+2*clvl, and the max should be 40+2*clvl.

In the spellbook, from the moment I got the spell until now (I gained several levels in the meantime) the min has been some ridiculous number over 22000. The max is listed as 0 unless my cursor hovers over the "Spells" or "Inv" buttons, in which case it becomes something around 170. I think the exact values have been changing a little with levels. If you want, I can start a new playthrough, try to get the spell as early as possible, and tabulate the exact numbers I get for each clvl.

I have used the spell against the torchants in the Nest and it kills them about as fast as I would expect, so I'm sure the damage is calculated correctly, and the bug is just a visual one.

I'll be very happy to download the new version and play around with multiplayer too :) I can't thank you enough for this!!

**Comment by AJenbo** [comment] 2021-02-25 08:38
> Yes, in the spellbook

Thanks, we were missing handling for the new spells (no new calculations were added, it simply reused existing calculations). The latest build should now match the numbers in the original game, not that these aren't actually related to the actual damage calculation. The number you were seeing previously was more or less random.

**Comment by Massi-Daisy** [comment] 2021-02-25 09:24
Fantastic, thank you! Can't wait to play the new version tonight :D

**Comment by Chance4us** [comment] 2021-02-25 09:51
@Massi-Daisy did the text scrolling it look like this?: https://github.com/diasurgical/devilutionX/issues/1046

**Comment by Massi-Daisy** [comment] 2021-02-25 10:04
> @Massi-Daisy did the text scrolling it look like this?: #1046

Yes! So far it has only happened to me with the Anvil of Fury quest. Other quests were behaving normally, as were the tomes on levels 4 and 8. I haven't reached level 12 of the caves yet.

**Comment by spitfire** [comment] 2021-02-25 11:39
> The game is fully playable. I've only encountered two small cosmetic glitches so far (when Griswold gave me the Anvil of Fury quest, the text was scrolling way too quickly, and the listed damage for lightning wall is weird), but they don't impact gameplay at all. Fantastic job everybody!!
I also had the text scroll real really fast, while narrator continued to speak - once in the give and second time in the crypt

Other than that haven't seen any issues

**Comment by qndel** [comment] 2021-02-25 15:00
https://github.com/diasurgical/devilutionX/pull/1057
Fast scrolling fixed

**Comment by Polynomial-C** [comment] 2021-02-26 08:29
I finally found some time to compile git HEAD on my Gentoo box. Unfortunately, while testing Hellfire I get regular segfaults. Is this a known issue or would you appreciate if I compile again with debugging symbols and report these segfaults? If yes, any preferred way of reporting these?

**Comment by Massi-Daisy** [comment] 2021-02-26 09:11
On Ubuntu 20.04, I only ever got a segfault twice. On both occasions it was on a new game, without having made a savefile, when I came back to town from the cathedral. Saving my game before changing maps fixed the issue.

**Comment by AJenbo** [comment] 2021-02-26 12:59
> I finally found some time to compile git HEAD on my Gentoo box. Unfortunately, while testing Hellfire I get regular segfaults. Is this a known issue or would you appreciate if I compile again with debugging symbols and report these segfaults? If yes, any preferred way of reporting these?

ofcause, create github issues

**Comment by Jarzuul** [comment] 2021-02-26 17:58
> Ok, Hellfire multiplayer should now be fully working.
> 
> @spitfire upgrading your hero from D1 to Hellfire should now work correctly for the new quests (could you test this, with a hero that hasn't been upgraded).
> 
> Windows x86_64 build:
> https://17247-143324737-gh.circle-artifacts.com/0/devilutionx_x64.zip
> Linux x86_64 build:
> https://17249-143324737-gh.circle-artifacts.com/0/devilutionx_linux_x86_64
> Everything else:
> https://app.circleci.com/pipelines/github/diasurgical/devilutionX/3193/workflows/1a36d2d5-1c47-4926-a9cd-457162635b4b

Hey @AJenbo 

I'm not sure if you wanted to mention me instead of spitfire, but I've tried the new build with a Devilution D1 Char. After starting a "New Game" I'm sadly have the same issues. Defiler Quest is not ending and the cathedral map is not dropping.

**Comment by AJenbo** [comment] 2021-02-26 18:02
Could you provide a save.

**Comment by Jarzuul** [comment] 2021-02-26 21:02
@AJenbo 

I've just sent you an email with attached savegames. Thank you, Anders!

**Comment by qndel** [comment] 2021-02-26 21:49
> @AJenbo
> 
> I've just sent you an email with attached savegames. Thank you, Anders!

An email? Sigh ... Why not attach them here so everyone can test? :(

**Comment by Jarzuul** [comment] 2021-02-26 22:18
@qndel 

I'm sorry. It wasn't my intention to upset you. :-(

The .hsv file was originally created with DevilutionX Stable (Diablo 1). After downloading DevilutionX Hellfire from Feb 25, I've changed the extension from .sv to .hsv and started a new game. (single_0.hsv). With this savegame you are starting on Hive Level 4. Just head north and you'll meet the Defiler.

I've also attached the original, not yet converted DevilutionX Stable (Diablo 1) file - just head east to kill the dark load :-) (single_0.sv)

[DevilutionX Savegames Jarzuul.zip](https://github.com/diasurgical/devilutionX/files/6052747/DevilutionX.Savegames.Jarzuul.zip)

**Comment by qndel** [comment] 2021-02-26 22:24
thx

**Comment by AJenbo** [comment] 2021-02-27 04:38
> The .hsv file was originally created with DevilutionX Stable (Diablo 1). After downloading DevilutionX Hellfire from Feb 25, I've changed the extension from .sv to .hsv and started a new game.

Hmm when I try I get the map. What system are you on?

> I've also attached the original, not yet converted DevilutionX Stable (Diablo 1) file

Good this is preferred as the save game will contain the quest status after having been converted :)

It does highlight another issue as some level items load corrupted when loading the D1 generated world in HF.

**Comment by Jarzuul** [comment] 2021-02-27 15:07
@AJenbo Tried it several times - it's not dropping :-(

I'm running the latest version from 25 Feb with the original Diablo DIABDAT.MPQ and the Hellfire files hellfire.mpq, hfmonk.mpq, hfmusic.mpq and hfvoice.mpq from the GOG version on Windows 10 x64. (please see the attached screenshot).

![devilutionx_hellfire_folder](https://user-images.githubusercontent.com/79545169/109391125-d92fe180-7915-11eb-9910-afb94845673b.png)

**Comment by AJenbo** [comment] 2021-02-27 23:11
Loading Diablo saves in Hellfire should now be fully working (levels and all), but be aware that saves that were converted in previous betas my well crash, so you will need to either create a new game or convert you original Diablo save again if you wish to continue it in Hellfire.

https://app.circleci.com/pipelines/github/diasurgical/devilutionX/3232/workflows/33cb2a2c-4479-4094-bcfe-faa345365f11/jobs/17639

https://github.com/diasurgical/devilutionX/runs/1995792945

**Closed** 2021-03-01 11:02 UTC
Labels: enhancement, upstream

**Comment by Jarzuul** [comment] 2021-03-01 21:09
Is an updated build available there? :)

**Comment by AJenbo** [comment] 2021-03-01 21:58
Test builds are generated for every change you can always find the latest here: https://app.circleci.com/pipelines/github/diasurgical/devilutionX?branch=master

Hellfire support is now considered complete, any issues with the implementation should be handled in new issues like any other issue :)

**Comment by Chance4us** [comment] 2021-03-01 22:37
An incredible status that has been achieved in this project.
The game now seems to be complete now and yet I still have two important questions.

The first concerns the exact execution of the game logic, because the following milestone has not yet been completed.
https://github.com/diasurgical/devilution/milestones/Hellfire

Can we assume that the execution and the game logic runs in the same way?

The second concerns the intergation of hellfire bard and barbarian.
Are bard and barbarian fully integrated and is there a way to activate them so that they can be played with?

**Comment by AJenbo** [comment] 2021-03-01 22:47
> Can we assume that the execution and the game logic runs in the same way?

Yes, the logic should be the same, the stuff that is left is either not related to the game itself (most is about writing error messages), or we manually compared the logic at a human level. The reason we had to do a manual comparison of something is that Hellfire was compiled with VC5 which is much more sensitive to auxiliary conditions that we can't replicate. Diablo 1.09 used VC6 which does a much more consistent job of compiling.

> The second concerns the intergation of hellfire bard and barbarian.
> Are bard and barbarian fully integrated and is there a way to activate them so that they can be played with?
Yes, `--help`

**Comment by spitfire** [comment] 2021-03-01 22:55
> > The second concerns the intergation of hellfire bard and barbarian.
> > Are bard and barbarian fully integrated and is there a way to activate them so that they can be played with?
> 
> Yes, `--bardtest --barbariantest`
How to use them on consoles (Switch/Vita/3DS in my case)?

**Comment by Chance4us** [comment] 2021-03-01 23:03
Thanks for the quick feedback and the great work from all of you.

**Comment by AJenbo** [comment] 2021-04-03 04:54
@spitfire they have been added to ini
