### ISSUE TITLE
TRN rewrite causes a crash in some situations

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#4144] opened 2022-03-08 22:38 UTC
Unfortunately, as we have already discussed under (https://github.com/diasurgical/devilutionX/pull/4079),
my suspicion has been strengthened that in some situations a crash can occur.

This seems to occur mostly when unique skeletons are nearby. Unfortunately, I cannot assess whether there are other possibilities or circumstances that could lead to a similar crash.

It's also important to mention that I was only able to isolate the crash on level-change from level 3 to level 4.

The issue occurs since commit 9ba64ad08b2a56b3cf00b15b485997a0deec9dc2.
Anyhow, thank you all very much for all your efforts despite all possible side effects that may occur from time to time.

To reproduce the crash, load the attached game and follow the same path as in the following video.
Savegame:
[crash.zip](https://github.com/diasurgical/devilutionX/files/8210100/crash.zip)

https://user-images.githubusercontent.com/45902449/157337637-a17fd48e-e114-4b94-9f2b-157f395e2dfe.mp4

**Comment by qndel** [comment] 2022-03-09 00:42
Can you give me more details about that save? Was it 100% devx? Or transferred? The problem is unique skeleton boss has index 40 while being spawned but later somehow ends up with 44 = that index doesn't have boss trn loaded = missile tries to use nullptr trn = crash

**Comment by qndel** [comment] 2022-03-09 02:04
Bisected to 2456aded6b6b337b8ac81df06df71209ed9cb288 18176fb35d58c8ee08a2dfff1e41b0bf6181d711
@obligaron 
To test I did this
```cpp
void PlaceUniqueMonst(int uniqindex, int miniontype, int bosspacksize)
{
	SDL_Log("MON INDEX: %d", ActiveMonsterCount);
	auto &monster = Monsters[ActiveMonsterCount];
```
then entered a level, went back, entered again, if unique monster indexes were different on second entry = broken

**Comment by Chance4us** [comment] 2022-03-09 05:49
> Can you give me more details about that save? Was it 100% devx? Or transferred? The problem is unique skeleton boss has index 40 while being spawned but later somehow ends up with 44 = that index doesn't have boss trn loaded = missile tries to use nullptr trn = crash
> 
> Actually there's same boss on index 40 and on 44 = something went wrong lol

Glad you found the cause.
I could not have provided any further details except that it is 100% Devilutionx savegame.

**Closed** 2022-03-09 19:23 UTC
Labels: bug

**Comment by Chance4us** [comment] 2022-03-09 23:24
TRN rewrite along with this fix adds a great value to the game. Thanks a lot.
