### ISSUE TITLE
[SDL1] - START + D-PAD-R does not open inventory

### ISSUE THREAD

**Issue by jimmiejoe** [diasurgical/devilutionX#4368] opened 2022-04-08 23:28 UTC
Downloaded the 3ds (85962) commit [2450adf]

The video on the 2DS FTR-001, now works, but the intro stutters.
The START + D-PAD-R does not open the inventory.
The START + R does open the inventory.

Expected behavior is that both should open the inventory.

**Comment by jimmiejoe** [comment] 2022-04-08 23:40
START + D-PAD-U works on 2DS
START + D-PAD-L works on 2DS
START + D-PAD-D works on 2DS
START + L works on 2DS
SELECT + Y works on 2DS
SELECT + B works on 2DS

Not sure what other mouse emulations there are on the 2DS.

**Comment by glebm** [comment] 2022-04-09 01:37
Does START + D-PAD-L work?

**Comment by jimmiejoe** [comment] 2022-04-09 02:29
Ok. I just figured out how to get to the correct file.
Pulled 3ds (86019) commit [https://github.com/diasurgical/devilutionX/commit/999fce97826d25436e13afb5fe7f9f2a0788ffaf]
The START + D-PAD-R still does not ope the Inventory, but other emulations work.
I also check the SELECT + D-PAD, but none of the emulation works, but the menu does show. The cursor jumps to the edge of the screen. In addition, you can not bring the menu back up with SELECT unless the character moves at least 1 step. Then you can get the SELECT menu to come up.

**Comment by jimmiejoe** [comment] 2022-04-09 03:10
Pulled 3ds (86024) commit [4c2fa76]
Same as 3ds (86019) the emulation clicks is not working on the 2DS.

**Comment by jimmiejoe** [comment] 2022-04-09 05:33
Yes

**Comment by glebm** [comment] 2022-04-09 09:38
> In addition, you can not bring the menu back up with SELECT unless the character moves at least 1 step. 

The rest sound like bugs but this one intended for D-Pad mouse emulation. It leaves mouse mode on until you press another button, e.g. so that you can use SELECT + L to click.

**Comment by glebm** [comment] 2022-04-09 09:57
Are you sure you've actually downloaded the correct version?
E.g. from here https://app.circleci.com/pipelines/github/diasurgical/devilutionX/12617/workflows/7405a61c-0372-4d19-9567-cde884c59769/jobs/86040/artifacts

(the current 3ds build appears to be quite slow, this is being investigated separately)

**Comment by AJenbo** [comment] 2022-04-09 12:06
> Pulled 3ds (86024) commit [[4c2fa76](https://github.com/diasurgical/devilutionX/commit/4c2fa76e492955754bbd413de3c8dd0466506198)] Same as 3ds (86019) the emulation clicks is not working on the 2DS.

What are the 86024/86019 numbers referring to?

**Comment by jimmiejoe** [comment] 2022-04-09 14:41
glebm's link goes to 3ds (86040) commit [0976278]. I believe 85962/86024/86019 are the file revision numbers.

**Comment by AJenbo** [comment] 2022-04-09 14:45
0976278 is the file revision number (commit hash), the others appear to just be some internal CircleCI counter. You can also see git hub recognize the has an converts it to a link, where the other ones just appears as text.

**Comment by jimmiejoe** [comment] 2022-04-09 14:52
Pulled 3ds (86040) commit 0976278, but the START + D-PAD-R does not open the inventory.

**Comment by jimmiejoe** [comment] 2022-04-09 15:14
This may be a dumb question, as I have not needed to use the SELECT menu yet, but does the SELECT menu need to have spells loaded. I am using a new character which does not have any spells. I can pull a character from a real Diablo CD built environment and load it with spells if that will help with testing. The next question is how do you load spells into the SELECT menu, to emulation F9, F10, F11, F12.

**Comment by jimmiejoe** [comment] 2022-04-09 17:51
Downloaded 3ds (86065) commit [0df7fd1], but the START + D-PAD-R does not open the inventory.

**Comment by AJenbo** [comment] 2022-04-09 18:23
@jimmiejoe please don't tell use every time we don't fix this issue. There are other things to work on as well.

**Comment by StephenCWills** [comment] 2022-04-09 19:27
Reproduced on Windows with SDL1.

**Comment by AJenbo** [comment] 2022-04-09 22:32
@jimmiejoe, alright now you can test and see if it's been fixed in the latest build :)

**Closed** 2022-04-09 22:31 UTC

**Comment by jimmiejoe** [comment] 2022-04-10 01:05
START + D-PAD-R is working now. It Open the Inventory as expected. However, Now when to push START it open the Menu as though START + D-PAD-U has been press.
