### ISSUE TITLE
Hide touch controls when using a gamepad

### ISSUE THREAD

**Issue by leires1** [diasurgical/devilutionX#3914] opened 2022-01-07 01:51 UTC
It would be pretty awesome. At least the virtual movement pad would be amazing.

**Comment by glebm** [comment] 2022-01-07 01:53
This is already done and will be in the next version! Closing as duplicate of #3824.

**Closed by glebm** 2022-01-07 01:53 UTC

**Comment by glebm** [comment] 2022-01-07 01:54
For now you can try out the debug APK https://github.com/diasurgical/devilutionX/suites/4857867919/artifacts/138184737
