### ISSUE TITLE
Dialog loops with monsters

### ISSUE THREAD

**Issue by myself600** [diasurgical/devilutionX#6306] opened 2023-07-03 17:11 UTC
### Operating System

Other (please specify)

### DevilutionX version

1.5.0 (latest release)

### Describe

In the title

**Operating system**: Manjaro ARM 23.02 (aarch64)

### To Reproduce

1. Teleport to Warlord of Blood and CL the surrounding Steel Lords
2. Repeatedly click on him right before he ends his talk
3. Repeat # 2

### Expected Behavior

He should stop talking

### Additional context

Happens in previous releases

**Comment by AJenbo** [comment] 2023-07-03 18:19
Duplicate of #6221

**Closed by AJenbo** 2023-07-03 18:19 UTC
