### ISSUE TITLE
Archbishop Lazarus' minion room closed after loading save game

### ISSUE THREAD

**Issue by DailyGrond** [diasurgical/devilutionX#889] opened 2020-10-20 01:15 UTC
Like the title says, transported out of the Unholy Altar before defeating Lazarus, came back and he is gone. Please help if you can.

[D1 Save.txt](https://github.com/diasurgical/devilutionX/files/5405675/D1.Save.txt)

**Comment by qndel** [comment] 2020-10-20 01:16
what version, what platform, attach a proper save

**Comment by AJenbo** [comment] 2020-10-20 02:07
I belive this is from GoG 1.09.

https://www.gog.com/forum/diablo/archbishop_lazarus_bug

**Comment by qndel** [comment] 2020-10-20 02:12
yep, but it still contains 0 useful info

**Comment by AJenbo** [comment] 2020-10-20 02:16
It's not a save game but some SQLLite3 meta data table :/

**Comment by qndel** [comment] 2020-10-20 02:19
I know ...

**Comment by qndel** [comment] 2020-10-20 02:21
not enough info to do anything, provide platform/version info & attach proper save

**Comment by DailyGrond** [comment] 2020-10-20 21:51
I apologize for the errors on my part. I'm playing on GOG, version 1.09

[D1 Save.zip](https://github.com/diasurgical/devilutionX/files/5411788/D1.Save.zip)

**Comment by qndel** [comment] 2020-10-20 22:01
uh, then why would you report it here? we don't have anything to do with GOG

**Comment by DailyGrond** [comment] 2020-10-20 22:31
Because AJenbo told me to on the GOG community forum.

**Comment by qndel** [comment] 2020-10-20 23:13
seems he thought that by "hi-res version" you meant devilutionX

**Comment by AJenbo** [comment] 2020-10-21 04:11
No I actually wanted to look in to if this is a vanilla bug happening

**Comment by AJenbo** [comment] 2020-10-21 08:49
I'm not sure exactly what went wrong with the level but I have fixed your save game:
[single_0.zip](https://github.com/diasurgical/devilutionX/files/5414505/single_0.zip)

Lazarus was standing inside the walled-off section so all I have done is force triggering the map change and saved again.

I tried replaying the same dungeon instance from start to finish and using a town portal at the point that you got the issue, but things worked as they should so possibly we have already solved the issue in DevilutionX or the bug is harder to trigger then one might expect.

**Comment by AJenbo** [comment] 2020-10-21 08:54
Ok, this is interesting, the issue is not related to the town portal but loading the game. Apparently, it doesn't remember the changed level state and so walls off this section again.

Here is a save where I loured him out of the buggy section so you can atleast continue your game while we try to fix this for DevilutionX. 
[single_0.zip](https://github.com/diasurgical/devilutionX/files/5414588/single_0.zip)

**Comment by AJenbo** [comment] 2021-01-31 06:37
Alright I figured out what was going one here.

Stepping on the teleport circle a second time will reset the quest to an earlier. If the player then re-enter the level (load gave, town portal etc.) the trap room will be inaccessible.

**Closed** 2021-01-31 06:39 UTC
Labels: bug, savegame attached, vanilla

**Comment by kdj7770** [comment] 2023-04-20 02:08
[single_0.zip](https://github.com/diasurgical/devilutionX/files/11279138/single_0.zip)
Hello,
I have had the same issue with Lazarus disappearing after using a town portal.  The difference was that I went back down into Hell through town to get some items I left and then using the town portal back again.  The red portal also opened up but neither would let Lazarus appear again.  I was so close to completing the game too!  The save file is attached.  Hopefully, someone is still monitoring this thread and is able to help.  I would hate to have to restart so close to the end.

**Comment by StephenCWills** [comment] 2023-04-20 02:57
@kdj7770 I don't know whether anyone will be gracious enough to fix your savegame, but I did test your save against DevilutionX 1.4.1 and was able to find and defeat Lazarus with no issues. You might just want to try doing that yourself.

**Comment by AJenbo** [comment] 2023-04-20 05:33
You can download the latest version here: https://github.com/diasurgical/devilutionX/releases/latest

**Comment by kdj7770** [comment] 2023-04-21 02:17
@AJenbo  @StephenCWills 

Thank you so much! The DevilutionX 1.4.1 build is awesome!  It fixed the Lazarus issue and also provided full widescreen support, which the original did not.  Awesome playing on the full widescreen and nothing is stretched!  Now if I can only beat Diablo lol.  I forgot how hard he was!  Thanks again!!!
