### ISSUE TITLE
1.5.0. Beta Controller Mapping

### ISSUE THREAD

**Issue by HellaTree** [diasurgical/devilutionX#5943] opened 2023-04-02 19:18 UTC
While using Xbox Controller I noticed that while mapping certain buttons (action/attack from A to X) worked while in dlvls, in town I still had to use A as an action with shopkeepers as well as in the menu.

**Comment by StephenCWills** [comment] 2023-04-02 23:13
Duplicate of #5467

But thanks for reporting.

**Closed by StephenCWills** 2023-04-02 23:13 UTC
