### ISSUE TITLE
Missing text space when selling unique item to vendor

### ISSUE THREAD

**Issue by Baracudus** [diasurgical/devilutionX#1559] opened 2021-04-16 22:50 UTC
**Important information**
WIn10 / DevilutionX 1.2.1 / Download

**Describe**
When selling a Unique Item to Adria (Mindcry in my case) then the text "Unique Item" has no space under it to the next Item. Works, but looks strange. Maybe a space under "Unique Item" would look better? No idea, if this is a vanilla bug. Screenshot attached!

**To Reproduce**
Sell "Mindcry" to Adria

**Expected behavior**
Space under the text "Unique Item"

**Screenshots**
added

**Additional context**
-
![screen14](https://user-images.githubusercontent.com/71731621/115091073-cd749a80-9f16-11eb-9974-a179f83659b1.png)

**Comment by julealgon** [comment] 2021-04-16 23:52
> No idea, if this is a vanilla bug.

Can't you check that?

**Comment by AJenbo** [comment] 2021-04-17 01:27
@Baracudus in case you are not aware savegames are compatible

**Comment by FitzRoyX** [comment] 2021-04-17 06:31
I see no issue here. The window is a fixed height and so are entries. If you add a space after a 4line entry, it would cut off a 4 line entry below it.

**Comment by yuripourre** [comment] 2021-04-17 07:57
Well, now that unique items have a golden color, why not remove the line that says unique item?

Unique items are probably blue because the rest of store UI is golden so they needed to flag unique items somewhere.

**Comment by Baracudus** [comment] 2021-04-17 08:02
Ok. I see this goes nowhere. It's not a bug, just a personal preference. Closed.

**Comment by qndel** [comment] 2021-04-17 11:23
Too bad you didn't include save ...

**Comment by AJenbo** [comment] 2021-04-17 11:29
It's not even been 24h and we haven't had the opportunity to investigate the cause, let's not close it just yet.

**Comment by qndel** [comment] 2021-04-17 11:30
it only happens for this specific case (unique staves), but I'd agree with removing "unique item" completely, because we have a proper color indicating unique items

**Comment by julealgon** [comment] 2021-04-17 16:26
> Well, now that unique items have a golden color, why not remove the line that says unique item?
> 
> Unique items are probably blue because the rest of store UI is golden so they needed to flag unique items somewhere.

This is a very reasonable suggestion now indeed. Great idea.

**Comment by julealgon** [comment] 2021-04-17 16:27
> Ok. I see this goes nowhere. It's not a bug, just a personal preference. Closed.

What's with this attitude? What do you even mean by "this goes nowhere"? Did you check to see if it happens in vanilla?

**Comment by FitzRoyX** [comment] 2021-04-17 18:06
> Well, now that unique items have a golden color, why not remove the line that says unique item?

It still turns red if you don't meet the reqs, right?

**Comment by qndel** [comment] 2021-04-17 18:08
yes

**Comment by FitzRoyX** [comment] 2021-04-17 18:24
And 75% of the visible selection is 3 potions. *throws list method out the window*

**Comment by AJenbo** [comment] 2021-04-17 21:22
> > Ok. I see this goes nowhere. It's not a bug, just a personal preference. Closed.
> 
> What's with this attitude? What do you even mean by "this goes nowhere"? Did you check to see if it happens in vanilla?

I'm guessing the many people debating looks more like a lot of aimless comments to someone who isn't in to the code or how the debug process works.

**Closed** 2021-04-17 21:42 UTC
