### ISSUE TITLE
Picking up the amulet in halls of the blind does not complete the quest

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#6347] opened 2023-07-11 19:51 UTC
Directly teleporting to the Halls of the Blind without first activating the quest will cause a random amulet to appear.

![amulet](https://github.com/diasurgical/devilutionX/assets/45902449/cf29949f-8b7f-48c9-b4a2-1be7010cfaa9)

Savegame:
[single_0.hsv.zip](https://github.com/diasurgical/devilutionX/files/12018563/single_0.hsv.zip)

**Comment by julealgon** [comment] 2023-07-11 19:53
If you then activate the quest after doing this but before picking up the item, does it change the amulet to the unique Optic Amulet?

**Comment by Chance4us** [comment] 2023-07-11 20:13
I only just discovered that.
But as soon as the hero was in the halls, the quest was already activated in the quest log.
So I guess the amulet won't change anymore.

There is also a possibility that it is due to the "Nightmare" difficulty level.
Possibly the generation of the items is different and depends on the difficulty.

We may also have the issue on a normal difficulty level, this still needs to be tested.

**Comment by Chance4us** [comment] 2023-07-11 20:51
Additional information.
Obvious that I already activated the quest at the beginning of the level.
The quest can no longer be completed and does not disappear in the quest log.

**Comment by Chance4us** [comment] 2023-07-11 20:53
It means that the amulet was already created this way when the quest was activated.

**Comment by FitzRoyX** [comment] 2023-07-12 12:17
Can't reproduce. The amulet only spawns once you read the book. The quest only activates once you read the book. When I loaded your savegame, I can see that the tome is opened near the start of the level.

Also, nightmare and hell difficulties no longer drop quest rewards. Did you not see that commit?

**Comment by Chance4us** [comment] 2023-07-12 17:46
Yes i saw a commit to allow the dropped items to be based on difficulty.
If the issue has something to do with it, it is no longer possible to complete "Halls of the Blind" quest in this state.
You can pick up the randomly generated amulet, but the quest doesn't disappear from the quest log.
Somehow a reasonable solution should be found.

Ultimately, the problem will have to be bisected, or the developers involved will know right away where the problem is.
In any case, I am unable to provide adequate answers at the moment as more time is needed for accurate analysis.

**Comment by FitzRoyX** [comment] 2023-07-12 23:14
Ok I see the problem. The quest is not being marked as complete once you pick up the non-optic amulet. Quest has no trouble with initiating and "teleporting into the halls" is not a problem either.

Sidenote: when loading devx saves from the latest master into vanilla, the automap is all borked and almost none of the walls get drawn.

**Comment by Chance4us** [comment] 2023-07-13 06:06
> Sidenote: when loading devx saves from the latest master into vanilla, the automap is all borked and almost none of the walls get drawn.

Then we should maybe create a separate issue for it.

**Comment by AJenbo** [comment] 2023-07-15 19:41
> You can pick up the randomly generated amulet, but the quest doesn't disappear from the quest log.

it supposed to work that you pick up the amulet at the specific location completes the quest. Not specifically the Optic Amulet

**Comment by AJenbo** [comment] 2023-07-15 19:42
> The quest can no longer be completed and does not disappear in the quest log.

Quests are not removed but marked as completed by changing to gold and won't play the latest dialog.

**Comment by AJenbo** [comment] 2023-07-15 19:50
> Sidenote: when loading devx saves from the latest master into vanilla, the automap is all borked and almost none of the walls get drawn.

For me the map looks exactly like in the image

**Comment by StephenCWills** [comment] 2023-07-15 19:58
Loading the attached save in vanilla Hellfire looks like this. The automap is basically empty and won't fill in.

![image](https://github.com/diasurgical/devilutionX/assets/9203145/0007d982-33ef-4d62-bcba-c69000d694a3)

**Comment by StephenCWills** [comment] 2023-07-15 20:08
> it supposed to work that you pick up the amulet at the specific location completes the quest. Not specifically the Optic Amulet

Seems like that logic only applies to multiplayer. I'm guessing the amulet's position is still randomized in SP too.

https://github.com/diasurgical/devilutionX/blob/1c0556ab711d3a7d8c3c99a55133258d0c1ad9a8/Source/inv.cpp#L872

**Comment by AJenbo** [comment] 2023-07-15 20:13
> Loading the attached save in vanilla Hellfire looks like this. The automap is basically empty and won't fill in.

yeah this is a known issue with how we change the format to handle other modes of exploration (shrine, coop)

**Closed** 2023-07-15 22:02 UTC
