### ISSUE TITLE
Search Spell Benefits More than the Caster

### ISSUE THREAD

**Issue by NiteKat** [diasurgical/devilutionX#2778] opened 2021-09-02 01:48 UTC
**Important information**
Windows 10 Pro / 1.2.1 / Downloaded a release

**Describe**
If you cast the Search spell in multiplayer, other players get gain the benefits of the spell.
Playing a multiplayer game with multiple players in it, cast the Search spell with at least two players on the same floor. All players on the floor (maybe other floors too?) gain the benefits of Search.

**To Reproduce**
1. Start a multiplayer game.
2. Learn the Search spell
3. Have a second player join the game.
4. Enter a dungeon level.
5. Cast search with the character that knows it
6. Both players will benefit from the search spell.

**Expected behavior**
Only the player casting Search should enjoy the benefits of the spell.

**Comment by AJenbo** [comment] 2021-09-02 08:01
Vanilla Hellfire bug it is then

**Comment by qndel** [comment] 2021-09-02 08:06
Read the description of "hellfire" label ;)

**Comment by AJenbo** [comment] 2021-09-02 08:14
I don't agre with your interpretation

**Comment by AJenbo** [comment] 2021-09-02 12:26
Definition :shrug:

**Comment by AJenbo** [comment] 2021-09-02 12:58
- This is a trivial issue to fix
- It's a common issues all over the hellfire code
- Marking it as intended leaves us with another issue as highlighed in #2508

**Comment by qndel** [comment] 2021-09-02 13:02
I'm not saying it's trivial to fix, I'm questioning if there's anything to fix there.

**Comment by AJenbo** [comment] 2021-09-02 13:10
I'm not saying you where.

**Comment by AJenbo** [comment] 2021-09-06 20:29
Fixed https://github.com/diasurgical/devilutionX/pull/2816#issuecomment-913826332

**Closed by AJenbo** 2021-09-06 20:29 UTC
Labels: good first issue, hellfire
