### ISSUE TITLE
Warlord of Blood

### ISSUE THREAD

**Issue by predator8bit** [diasurgical/devilutionX#24] opened 2019-02-27 23:13 UTC
On level 13 guarding the exit to level 14 is the "Warlord of Blood" monster with his friends, when I first encountered him, his dialog played but he didn't fight me. I couldn't attack him either, after killing all the other knight monsters I went back to town and after I returned to the level he attacked as expected.

**Comment by predator8bit** [comment] 2019-02-28 01:03
Same thing happened on Arch-Bishop Lazarus, his line plays and then the unique monsters just stare at my character but don't attack.

**Comment by predator8bit** [comment] 2019-02-28 22:21
I saved just before a crash here, and the save loads nicely. The previous one only worked if I created a new game with the character and then loaded into the game.

Something fishy is going on with the firemage projectiles, the sound effect repeats when going through walls and in some cases they damage through walls ( I can't remember if this is vanilla behaviour or not).

[crash2.zip](https://github.com/diasurgical/devilutionX/files/2917148/crash2.zip)

**Comment by AJenbo** [comment] 2019-02-28 23:14
I'm confused, when is your game crashing? Maybe you have posted this in the wrong issue?

**Comment by predator8bit** [comment] 2019-02-28 23:20
At archbishop lazarus, I started a new game and confirmed it again, during fights with the firemages the game crashes, maybe I should create a separate issue.

**Comment by AJenbo** [comment] 2019-03-01 03:24
If one is that some monsters don't attack and the other one is that the game crashes when you mean monsters then they should be separate issues.

**Comment by predator8bit** [comment] 2019-03-01 12:35
Yeah, I just couldn't get to the archbishop to replicate the standing still issue. 

Also in the first run interestingly Gharbad the Weak didn't stall like the other unique monsters with text, he attacked right after his dialog finished.

**Comment by AJenbo** [comment] 2019-03-01 23:10
It looks like this is actually an upstream issue. Could you test to see if the present is also present in the devilution releases to help pinpoint the issue?
https://github.com/diasurgical/devilution/releases

**Comment by predator8bit** [comment] 2019-03-02 00:29
Sorry but I don't have any Windows PCs in the household, so I can't really test it on that platform.

**Comment by AJenbo** [comment] 2019-03-02 00:53
Fair enough, it runs in Wine (except that the menu is black, but just hit enter a few times to load the first save game), but I can understand if you don't want to go down the path of having to install it.

**Comment by predator8bit** [comment] 2019-03-02 09:40
For me the black screen is non responsive, no menu sounds and no matter what button I press nothing happens. I have to kill the process manually when running through wine (it is wine 4.2).

**Comment by AJenbo** [comment] 2019-03-02 13:53
I hear that the game totally broke in some of the latest versions of Wine. I'm using wine-3.0.3

**Comment by AJenbo** [comment] 2019-03-02 14:06
Can now confirm that it broke between Devilution 0.4 and 0.5. Going to try and fix it now :)

**Comment by predator8bit** [comment] 2019-03-02 14:53
Related to this issue I think, is that when I talked to Pepin the healer after completing the Black mushroom part of the "Magic Mushroom" quest, the first monster I killed didn't drop the quest item "Monster Brain" so I wasn't able to return that to Pepin and complete the quest.

**Comment by AJenbo** [comment] 2019-03-02 15:28
Ok, please report this as a separate issue.

My find for the warlord turned out to be a false positive, I was testing with your save game and Lazurus thinking it was the same issue, but it turned out to be specific for Lazurus. Could you provide a save game that shows the issue with the Warlord? I realize that I may take some time to do, but it would be a big help.

**Comment by AJenbo** [comment] 2019-03-02 15:39
MAI_Warlord is now bin exact so likely isn't the cause of the issue.

**Comment by predator8bit** [comment] 2019-03-02 16:03
No biggie, I'm always up for a new run. :)

**Comment by AJenbo** [comment] 2019-03-02 16:32
Cool, now that Lazarus is fixed it reveals that he actually does get stuck because of the issue with audio dialogs. I expect that this is actually also why you don't get the monster brain and why the Warloard doesn't attack. Fixing the audio is part of the goal for 0.2.0 so probably by then all 3 issues should be fixed.

**Comment by AJenbo** [comment] 2019-03-02 17:09
@predator8bit here is a new test build that hopefully solves the issues, not that you can still not interrupt a dialog, but the game now thinks that the dialog ended instantly instead of ever ending.

[devilutionx.zip](https://github.com/diasurgical/devilutionX/files/2922330/devilutionx.zip)

**Comment by predator8bit** [comment] 2019-03-02 21:56
Man, got to the quest and I can't replicate the issue now the monster dropped the brain. (I didn't use the patched devilutionx when trying so it must've been a different issue or I simply missed the drop the last time.)

**Comment by predator8bit** [comment] 2019-03-03 15:08
Warlord of Blood attacks with the provided patched devilutionx. This save is right in front of the room where the Warlord is.
[warlord.zip](https://github.com/diasurgical/devilutionX/files/2923251/warlord.zip)

**Comment by predator8bit** [comment] 2019-03-03 17:29
Here is a save in front of the portal to Lazarus, for future testing. 
[lazarus.zip](https://github.com/diasurgical/devilutionX/files/2923401/lazarus.zip)

**Closed** 2019-03-16 14:36 UTC

**Comment by AJenbo** [comment] 2019-03-16 14:40
This is now fixed in the latest build, feel free to get from the build server to test it:
https://circleci.com/gh/diasurgical/devilutionX/47#artifacts/containers/0
(devilutionx_linux_x86)
