### ISSUE TITLE
[Bow of Fire] Enemies can take multiple damage from a fire arrow attack

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#3842] opened 2021-12-25 19:20 UTC
Enemies can take multiple damage from a fire arrow attack when using the "bow of fire".
The issue is similar to #1672 or #1675, but with the difference that it is not the hero that suffers multiple damage, but the monster.

It also remains to be investigated whether this is also a vanilla issue.
Unfortunately, it cannot be reproduced that often with this hero, but it was noticed that it mainly happens when firing diagonally.

There is also a high probability that the frequency of the issue will depend on the dexterity of the hero.
Furthermore, it could also be that this behavior also occurs when using the "bow of lightning".

You can see what it looks like in the slowed-down image sequence below, in which the opponent is framed in red.

https://user-images.githubusercontent.com/45902449/147392104-420e0128-0415-484a-ac53-1367a608494d.mp4

Savegame:
[multiple_damage.zip](https://github.com/diasurgical/devilutionX/files/7776190/multiple_damage.zip)

EDIT:
After a closer examination, I can confirm that the "bow of lightning" behaves similarly. 
Savegame:
[bow_of_lightning.zip](https://github.com/diasurgical/devilutionX/files/7777625/bow_of_lightning.zip)

**Comment by kphoenix137** [comment] 2021-12-29 00:12
I can confirm this bug exists in Vanilla. AFAIK, Fire Arrow bows are able to stack more damage than lightning arrow bows.

**Comment by kphoenix137** [comment] 2021-12-29 06:50
Would like to add some more information regarding this bug. When this bug occurs in PVP, the shooter will hear not only the target player's damage sound, but they will hear their own damage sound stacked several times which is very loud.

After some testing with another player in an environment where physical damage from these arrows was reduced to a range of 0-0, this bug still occurred as indicated by the stacked incorrect damage sound, however the damage dealt was not noticeable at all during these bugged hits as compared to normal hits. I am under the impression that physical damage is somehow being multiplied when it should only be applied once.

To add some more, there is an old PVP trick where players will cast Charged Bolt in addition to shooting players with arrows or casting Fireballs, where a simultaneous hit from both missiles will cause an insanely large amount of damage to occur.

**Comment by StephenCWills** [comment] 2021-12-29 07:27
> When this bug occurs in PVP, the shooter will hear not only the target player's damage sound, but they will hear their own damage sound stacked several times which is very loud.

This strongly supports the theory that the cause is elemental damage. See #3260.

**Comment by kphoenix137** [comment] 2021-12-30 05:31
#3863 
Here's the fix

**Comment by Chance4us** [comment] 2021-12-30 10:45
> #3863 Here's the fix
> 
> What was happening was a combination of 2 bugs. The unusual large amounts of damage being dealt were actually the ...

Thanks a lot.

**Comment by AJenbo** [comment] 2022-01-19 02:06
@Chance4us can you test if this is fixed now :)

**Comment by Chance4us** [comment] 2022-01-19 10:38
> @Chance4us can you test if this is fixed now :)

As soon as some free time is available. I will report as soon as possible.

**Comment by julealgon** [comment] 2022-01-19 15:56
> AFAIK, Fire Arrow bows are able to stack more damage than lightning arrow bows.

Such an intriguing aspect to it. Do we know why this is the case now @kphoenix137? Is it because of this?

> ...which is up to 9 times for fire based and up to 7 times for lightning based

Are those `9` and `7` values hardcoded somewhere?

**Comment by StephenCWills** [comment] 2022-01-19 16:07
The damage was applied once per frame throughout the animation for the elemental effect. Those values are therefore based on the number of frames in the elemental animation.

**Comment by kphoenix137** [comment] 2022-01-19 16:08
> > AFAIK, Fire Arrow bows are able to stack more damage than lightning arrow bows.
> 
> Such an intriguing aspect to it. Do we know why this is the case now @kphoenix137? Is it because of this?
> 
> > ...which is up to 9 times for fire based and up to 7 times for lightning based
> 
> Are those `9` and `7` values hardcoded somewhere?

Yes. They are the number of frames in the secondary animations minus 1

**Comment by Chance4us** [comment] 2022-01-19 23:03
I can confirm that the issue is resolved. The solution makes the game feel much more balanced.
It's about time, it was really a never ending annoying bug. Thanks a lot for fixing.

**Comment by ephphatha** [comment] 2022-01-19 23:05
thanks heaps for confirming the fix worked :D

**Closed** 2022-01-19 23:04 UTC
Labels: vanilla
