### ISSUE TITLE
Can't pick up Quest reward

### ISSUE THREAD

**Issue by cornels** [diasurgical/devilutionX#1400] opened 2021-04-07 11:07 UTC
**Important information**
Windows 10 64bit / DevilutionX 1.2.0 / downloaded release

**Describe**
Cleared the Poison Water Supply level, but when I had to recieve the reward from Pepin the ring appeared on the wall of the house and it can't be picked from there.
Additionally if I throw an item from my inventory on the ring, it gets duplicated instead of the ring, but the duplicate item cannot be picked up.

**To Reproduce**
1. Clear Poison Water Supply level.
2. Return to Pepin the Healer for reward.
3. Reward ring appears on the wall of the house, like in screenshot, and can't be picked up.
4. Throw an item from inventory onto the ring and it will be duplicated, the ring dissappears.

**Expected behavior**
The reward should be thrown onto an empty tile so it can be picked up.

**Screenshots**
![image](https://user-images.githubusercontent.com/1046550/113856491-fd4ed000-97a9-11eb-9f13-3158481d3051.png)

**Additional context**
[Attached an archive with the save and config files.](https://github.com/diasurgical/devilutionX/files/6271074/save.config.zip)

**Comment by AJenbo** [comment] 2021-04-07 11:11
Thanks for reporting, this is a duplicate of https://github.com/diasurgical/devilutionX/issues/1367

**Closed by AJenbo** 2021-04-07 11:11 UTC

**Comment by cornels** [comment] 2021-04-07 11:34
Sorry about that, I had't realised that #1367 was the same issue.
Just tried the 32bit build with the same save file and the issue persists.
Will try a new game with the 32bit build.

**Comment by AJenbo** [comment] 2021-04-07 11:41
No worries it's not super obvious, and that issue might actually contain two separate issues (still being investigated)

The issue that affects the save game will contain the bugged item list. So you will have to start a new game to properly test it.

**Comment by cornels** [comment] 2021-04-07 11:48
Ok, started a new game with the 32bit release, cleared the Poison Water Supply level, returned to Pepin and the ring dropped like it should.

**Comment by cornels** [comment] 2021-04-07 12:25
Started a new game with the 64bit build and haven't encounetered the problem. So... I guess it was something on my end?

**Comment by AJenbo** [comment] 2021-04-07 12:58
You are not the only one to encounter it and all of them were on 64bit Windows. I was actually able to replicate it just a little while ago using the 64bit windows build and have never encountered it on Linux so I'm pretty suspicious of the Windows 64bit atm.

**Comment by AJenbo** [comment] 2021-04-07 15:33
@cornels could you let me know if it was hellfire or diablo you were laying?

**Comment by cornels** [comment] 2021-04-07 15:35
It was Hellfire, with the quest randomizer disabled (to get all quests), plus the 2 hidden quests.
