### ISSUE TITLE
HUD is not updated on gamma change

### ISSUE THREAD

**Issue by arczi84** [diasurgical/devilutionX#383] opened 2019-10-21 09:13 UTC
Also HUD is not updated on gamma change, moving mouse over updates it.
![image](https://user-images.githubusercontent.com/3505526/67190094-a4417f80-f3ef-11e9-8631-863f7cd5dc2e.png)

> $ git log
> commit 56f953b (HEAD -> master, origin/master, origin/HEAD)
> Author: Gleb Mazovetskiy glex.spb@gmail.com
> Date: Sun Oct 20 18:59:17 2019 +0100
> 
> sdl2_to_1_2_backports.h: Add missing #include
> commit 0d7f876
> Author: Anders Jenbo anders@jenbo.dk
> Date: Sun Oct 20 19:23:20 2019 +0200
> 
> Remove width from info panel sy value
> 
> This was left behind when doing 337bc9b

**Comment by AJenbo** [comment] 2019-10-21 09:41
Confirmed on PC SDL2

**Comment by mmaret** [comment] 2019-11-05 21:48
I cannot reproduce it anymore on b6695fe26b68e0d4c39d7c9ee67bfa85d50a6520.
Cool :)

**Comment by AJenbo** [comment] 2019-11-06 08:51
Odd that commit dosent appear to touch any related code

**Comment by mmaret** [comment] 2019-11-06 09:19
Sorry, I did not test any particular commit but on "last master" it's fixed ! No idea which commit did the fix ...

**Comment by AJenbo** [comment] 2019-11-06 14:28
This is not solved:
![image](https://user-images.githubusercontent.com/204594/68306580-1b426d80-00aa-11ea-88a0-a9bd945d6985.png)

**Comment by mmaret** [comment] 2019-11-06 15:50
Sorry for that :(
I check and I've the SCREEN_WIDTH and SCREEN_HEIGHT modified in def.h.
I cannot reproduce the bug if they are 1280x720 (but I expect anything different from 640x480 may work ?).
I can reproduce it with 640x480

**Comment by qndel** [comment] 2019-11-06 15:51
I'll fix it

**Comment by qndel** [comment] 2019-11-06 15:58
fixed by #420

**Closed by qndel** 2019-11-06 15:58 UTC
Labels: bug

**Comment by mmaret** [comment] 2019-11-06 15:59
That was quick :)

**Comment by qndel** [comment] 2019-11-06 15:59
I knew exactly what to do ;)

**Comment by AJenbo** [comment] 2019-11-06 23:23
@mmaret at 640x* and lower the panels cover the screen so to speed up things only the game area of the screen is redrawn, for higher resolutions the whole screen has to be redrawn thus why the bug only shows up for the low resolution
