### ISSUE TITLE
Detect hacked items

### ISSUE THREAD

**Issue by ukos-git** [diasurgical/devilutionX#3813] opened 2021-12-20 22:29 UTC
The hellfire save game in the attached save game contains a "dragon's ring" which is a hacked item and to some extend is treated as a staff. It might be worth it to invalidate such nonsensical items.

[crash.zip](https://github.com/diasurgical/devilutionX/files/7753727/crash.zip)

**note this was adapted from a previous issues, hence the unrelated comments below**

**Comment by qndel** [comment] 2021-12-21 07:49
@ukos-git can u upload the character that crashes?

**Comment by AJenbo** [comment] 2021-12-21 08:01
Also could you let us know if your are using any translations in the game?

**Comment by ukos-git** [comment] 2021-12-21 09:18
No localization on both parties. I may have had `de` activated on the char some time ago. I added [char.tar.gz](https://github.com/diasurgical/devilutionX/files/7750925/char.tar.gz) and diablo.ini from the crashing party. The crash may also get caused by the char on the other PC that is not crashing. Both chars are legit and use the same mpq and git master.

The staff on the crashing character is a starting item. Assuming that this item causes the crash, can I print more details on the item with `gdb`?
```
#9  0x0000000000618469 in LanguageTranslate[abi:cxx11](char const*) ()
#10 0x00000000004d3457 in devilution::(anonymous namespace)::GetStaffPower(devilution::Item&, int, int, bool) ()
```

I will create two new characters to see if the problem persists.

**Comment by qndel** [comment] 2021-12-21 09:46
[char.zip](https://github.com/diasurgical/devilutionX/files/7751278/char.zip)
Reuploaded in a more standard format

**Comment by qndel** [comment] 2021-12-21 09:54
your character doesn't show up for me

**Comment by glebm** [comment] 2021-12-21 09:59
From the backtrace, it seems that either `AllItemsList[item.IDidx].iName` or `AllItemsList[item.IDidx].iSName` is `nullptr` (these are the only direct calls to `LanguageTranslate` in that function).

https://github.com/diasurgical/devilutionX/blob/97a5609cfff6b170ff943537e88cbbfbd9304b10/Source/items.cpp#L1131-L1132

**Comment by AJenbo** [comment] 2021-12-21 10:03
Invalidi item.IDidx values should be filtered out by the unpackplayer function

**Comment by ukos-git** [comment] 2021-12-21 11:24
Joining with two *new* characters works. The crash is caused by an item on the *other* (non-crashing) character. [crash.zip](https://github.com/diasurgical/devilutionX/files/7753727/crash.zip)

I have a few items on that char that were dropped by a random person who joined the game a few times after doing runs. At least one of these items seems to break the game for anybody that joins.

**Comment by qndel** [comment] 2021-12-21 11:32
Thanks, managed to reproduce the crash.

**Comment by ukos-git** [comment] 2021-12-21 11:41
Well, I remember having one at some point early on. 😂

**Comment by qndel** [comment] 2021-12-21 12:00
INFO: UnPackPlayer NAME: Jazreth BODY SLOT: 2
INFO: UNPACK ITEM!
INFO: RECREATE ITEM!
INFO: SETUP ALL ITEMS
INFO: GET STAFF SPELL Short Staff of Charged Bolt Short Staff of Charged Bolt
INFO: GET STAFF POWER: Short Staff of Charged Bolt (null)
INFO: NULL KEY

So in multiplayer other characters somehow see your staff as a crashing staff of charged bolt

**Comment by ukos-git** [comment] 2021-12-21 12:57
thanks. Confirmed. This "Dragon Ring" probably was non-legit item.
Crashing the game at this point is probably not the right way of handling the error. Would it be possible to add a debug message for items like this?

**Comment by AJenbo** [comment] 2022-04-04 21:31
Looks like this is fixed now?

![image](https://user-images.githubusercontent.com/204594/161635703-d5a5bfb4-48e9-4b36-9ecf-8a08f7040bb2.png)

**Comment by AJenbo** [comment] 2022-04-04 21:36
I'm a bit unsure if I did things correctly as I did not see a staff of holy bolt and i'm not sure which of the characters i should be using :shrug:

**Comment by StephenCWills** [comment] 2022-04-04 21:53
Could be related to #3956.

**Comment by AJenbo** [comment] 2022-04-04 22:02
Yep, that one fixes the crash.

**Closed** 2023-06-19 01:14 UTC
