### ISSUE TITLE
Error building on Linux

### ISSUE THREAD

**Issue by muzena** [diasurgical/devilutionX#3786] opened 2021-12-17 18:05 UTC
Linux Mint 20.2, DevilutionX version is latest git/master
Enter build commands:
cmake -S. -Bbuild ..
cmake --build build -j $(nproc) --target package
Log files:
[CMakeError.log](https://github.com/diasurgical/devilutionX/files/7736951/CMakeError.log)
[CMakeOutput.log](https://github.com/diasurgical/devilutionX/files/7736952/CMakeOutput.log)

**Comment by AJenbo** [comment] 2021-12-17 18:24
> latest git/master

please provide the actual hash since "latest" can be old if you haven't updated recently or hard to figure out by the time someone looks at the issue.

>  cmake -S. -Bbuild ..

This is malformed, it should be: `cmake -S. -Bbuild`

**Comment by muzena** [comment] 2021-12-17 19:43
@AJenbo 
https://github.com/diasurgical/devilutionX/commit/95b2467ea504fd185e55f15740db78965450f5b9

**Comment by AJenbo** [comment] 2021-12-17 20:13
Considering that this is newer then when you first reported the issue I think we can conclude that the issue is know to affect older versions also :P

**Comment by muzena** [comment] 2021-12-17 20:19
Everything worked until yesterday, before this test/googletest changes.

**Comment by AJenbo** [comment] 2021-12-17 20:26
Considering that you are updating a different folder then the folder where you run the build from I'm not to surprised. Could you try clearing your build folders and running the process from a path.

**Comment by muzena** [comment] 2021-12-18 16:56
Same error on Fedora Rawhide and Ubuntu Impish

**Comment by AJenbo** [comment] 2021-12-18 18:01
Please rerun with the correct commands as described in the build instructions: https://github.com/diasurgical/devilutionX/blob/master/docs/building.md#building-from-source

You are generating the config in `/tmp/devilutionx-git-manually-build/build` and trying to compile from `/tmp/devilutionx-git-manually-build/devilutionX/build`. This won't work correctly.

The CI is running builds on Debian 9 (Stretch) and  Ubuntu 20.04.3, and I am able to build both on Ubuntu 21.04 and 21.10 (Impish).

I'm also not sure what the two logs you attached represents, normally the cmake out put would look something like this:

```

-- The C compiler identification is GNU 11.2.0
-- The CXX compiler identification is GNU 11.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- 📚 SDL2: dynamic system library
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2") 
-- Suitable system SDL_image package not found, will use SDL_image from source
-- 📚 SDL_image: static library from source
-- Suitable system png package not found, will use png from source
-- 📚 libpng: static library from source
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11") 
-- Performing Test HAVE_LD_VERSION_SCRIPT
-- Performing Test HAVE_LD_VERSION_SCRIPT - Success
-- Symbol prefix: 
CMake Warning (dev) in build/_deps/libpng-src/CMakeLists.txt:
  A logical block opening on the line

    /home/ajenbo/code/diablo/devilutionX/build/_deps/libpng-src/CMakeLists.txt:275 (if)

  closes on the line

    /home/ajenbo/code/diablo/devilutionX/build/_deps/libpng-src/CMakeLists.txt:471 (endif)

  with mis-matching arguments.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- 📚 SDL_audiolib: static library from source
-- Performing Test HAVE_STD_CLAMP
-- Performing Test HAVE_STD_CLAMP - Success
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
-- 📚 libsodium: dynamic system library
-- Found sodium: /usr/lib/x86_64-linux-gnu/libsodium.so (found version "1.0.18") 
-- Found fmt 7.1.3
-- 📚 libfmt: dynamic system library
-- 📚 bzip2: dynamic system library
-- Found BZip2: /usr/lib/x86_64-linux-gnu/libbz2.so (found version "1.0.8") 
-- Looking for BZ2_bzCompressInit
-- Looking for BZ2_bzCompressInit - found
-- 📚 googletest: dynamic system library
-- Found GTest: /usr/lib/x86_64-linux-gnu/libgtest.a  
-- Found Gettext: /usr/bin/msgmerge (found version "0.21") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ajenbo/code/diablo/devilutionX/build
```

**Comment by muzena** [comment] 2021-12-18 21:36
I run in Ubuntu Impish and Fedora Rawhide in Home folder as i wrote before, with this steps from wiki as you mentioned:
$ git clone git@github.com:diasurgical/devilutionX.git
$ cd devilutionX
$ cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Release
$ cmake --build build -j $(getconf _NPROCESSORS_ONLN)

[terminal-output.txt](https://github.com/diasurgical/devilutionX/files/7739995/terminal-output.txt)

**Comment by AJenbo** [comment] 2021-12-18 22:32
> I run in Ubuntu Impish and Fedora Rawhide in Home folder as i wrote before, with this steps from wiki as you mentioned:

You never mentioned the home folder and your logs strongly indicated that you where running it from `/tmp`.

I didn't refer to the wiki but the docs. I can see that there are some [outdated instructions on the wiki](https://github.com/diasurgical/devilutionX/wiki/Compiling-from-Source). In fact the latest update to them is to simply refer to the docs instead. Please make sure you are using [the up to date docs](https://github.com/diasurgical/devilutionX/blob/master/docs/building.md) that I linked, and not the wiki.

Ubuntu 21.10 (impish) comers with GCC 11.2.0 but your log reports 9.3.0. Your system might only be partially upgraded and you should check for obsolete packages in Synaptic. GCC 9.3.0 shipped with Ubuntu 20.04 so I'm guessing that is what you originally installed and then since have upgraded from that with possible PPAs on top which can lead to a situation where part of the system will be healed back. On way to avoid it is to run ppa-purge on all repose you use prior to upgrading and then apply them again after upgrading. This can also be done after upgrading although it can become a bit more complicated with having to add them first before then removing them.
If the conflicts are not to bad you can also force the version from Synaptic.

Here are the corresponding Ubuntu versions for the various other package versions listed in your log:
pkg-config 0.29.1 -> Ubuntu 18.04 - 20.04
Gettext 0.19.8.1 -> Ubuntu 18.04 - 20.04
GCC 9.3.0 -> Ubuntu 20.04
libsodium 1.0.18 -> Ubuntu 20.04 - 21.10
fmt 7.1.3 -> Ubuntu 21.04 - 21.10
BZip2 1.0.8 -> Ubuntu 21.04 - 21.10
ZLIB 1.2.11 -> Ubuntu 18.04 - 21.10

So it very much looks like your system has become a hybrid of Ubuntu 20.04 and 21.10.

Additionally it's a bit hard to read your log since some of the error messages are in Croatian. If you could temporarily disable translations (by running `export LC_ALL=C`) for the compile process that would be helpful.

Your build seams to be failing during linking of the tests. Maybe your are missing some of the recently added dependencies.

On a clean Ubuntu vm I ran the following and got a successful compile, can you please try the same:
```bash
sudo apt-get install cmake g++ libsdl2-dev libsodium-dev libpng-dev libbz2-dev libgtest-dev libgmock-dev
sudo apt install git
git clone https://github.com/diasurgical/devilutionX.git
cd devilutionX/
cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Release
cmake --build build -j $(getconf _NPROCESSORS_ONLN)
```

**Comment by AJenbo** [comment] 2021-12-18 23:37
Closing as I can't find a way to replicate and it seams to be specific to an inconsistent environment. Feel free to post more information if you figure out the cause/solution.

**Closed by AJenbo** 2021-12-18 23:37 UTC

**Comment by muzena** [comment] 2021-12-19 15:42
@AJenbo 
Problem is in **libfmt-dev** library, I removed it from build dependencies, so that build system use downloaded fmt source.
I use **make_src_dist.py** to download all dependencies and prepare packaging, but It seems according to [build log](https://launchpadlibrarian.net/575009115/buildlog_ubuntu-jammy-amd64.devilutionx_1.3.0-revno455-e496e1c4-202119121538~ubuntu22.04_BUILDING.txt.gz) instead using downloaded fmt source, building process is trying to download fmt.
Then I tried to run **python3 make_src_ --fully_vendored** to download and make all dependencies, but this gave me error:

> + cmake --build /tmp/devilutionx-ppa-upload/devilutionX/build-src-dist --target devilutionx_mpq
make: *** No rule to make target 'devilutionx_mpq'.  Stop.
Copying repo files...
Copying devilutionx.mpq...
Traceback (most recent call last):
  File "make_src_dist.py", line 210, in <module>
    main()
  File "make_src_dist.py", line 108, in main
    shutil.copy(_BUILD_DIR.joinpath('devilutionx.mpq'), paths.dist_dir)
  File "/usr/lib/python3.8/shutil.py", line 418, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.8/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/devilutionx-ppa-upload/devilutionX/build-src-dist/devilutionx.mpq'

**Comment by AJenbo** [comment] 2021-12-19 16:02
This seams to be an entirely different issue then what we have been looking at up til now. Did you manage to resolve the first issue? It would be good if we can deal with one at a time, and preferably create separate issues for each. Or for help with setting up the build process I would suggest joining [the chat](https://discord.gg/YQKCAYQ).

>  I use make_src_dist.py to download all dependencies and prepare packaging, but It seems according to build log instead using downloaded fmt source, building process is trying to download fmt.

The log shows that this is now on a beta of Ubuntu 22.04, is the issue specific to that system?

>  make: *** No rule to make target 'devilutionx_mpq'. Stop.

Do you have `smpq` installed?

[![image](https://user-images.githubusercontent.com/204594/146681651-f47ea03c-115e-482b-b29e-39c09a1ab66e.png)](https://github.com/diasurgical/devilutionX/blob/master/docs/building.md#if-you-want-to-build-the-devilutionxmpq-file-optional)

**Comment by muzena** [comment] 2021-12-19 16:11
But i have installed smpq package and I added it to [control file](https://github.com/muzena/devilutionX/blob/debian-manually/Packaging/debian/control)

**Comment by muzena** [comment] 2021-12-19 16:30
I tried in virtual machine Linux Mint/Ubuntu Focal, clean install and compilation worked when I removed libfmt-dev. But Launchpad build system does not allowing cloning/downloading from outside sources.

**Comment by AJenbo** [comment] 2021-12-19 17:33
What do you mean by removing libfmt-dev?

Are you using steps described ealier, or is this with a different build process? How can we replicate this?

Can you please try the previously metnioned steps and let us know if that works:
```bash
sudo apt-get install cmake g++ libsdl2-dev libsodium-dev libpng-dev libbz2-dev libgtest-dev libgmock-dev
sudo apt install git
git clone https://github.com/diasurgical/devilutionX.git
cd devilutionX/
cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Release
cmake --build build -j $(getconf _NPROCESSORS_ONLN)
```

If you are having issues with a different process then you need to describe the process so that we know what we are trying to help with. It sounds like the issue you talking about now is one of the following and not what this issue was originally about:

- `make_src_dist.py --fully_vendored` fails to generate devilutionx.mpq
- Build fails using system installed fmt 7.1.3

If that is the case then please create a new issue and give the exact steps to replicate the issue on a clean system.

**Comment by muzena** [comment] 2021-12-20 10:54
> Can you please try the previously metnioned steps and let us know if that works:

Yes, it works.

**Comment by AJenbo** [comment] 2021-12-21 00:01
After installing smpq and gettext i ran `python3 tools/make_src_dist.py --fully_vendored` which generated `build-src-dist/devilutionx-src-full-1.3.0-237caadf.tar.xz` seemingly with out issue as well, and it contains libfmt-src.

I also tried installing `libfmt-dev` and ran the previously mentioned build steps without issue.

So I'm still very much unable to replicate any of the issues you described.

**Comment by AJenbo** [comment] 2021-12-21 00:11
If I extract the content of `build-src-dist/devilutionx-src-full-1.3.0-237caadf.tar.xz` and try to build it I do get a linking error for the tests. But that can easily be avoided by simply not building tests with `-DBUILD_TESTING=OFF`, maybe that solves your problem?

**Comment by AJenbo** [comment] 2021-12-21 06:57
Also that issue is now solved: https://github.com/diasurgical/devilutionX/pull/3814

**Comment by muzena** [comment] 2021-12-22 12:26
@AJenbo 
I'm testing compilation in Virtualbox Ubuntu 22.04, to avoid problem with older dependencies.

1. Case:
    **git clone git@github.com:diasurgical/devilutionX.git**
    **cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Release**
    **cmake --build build -j $(getconf _NPROCESSORS_ONLN)**
    In this case all work without errors.
2. Case:
     **python3 make_src_dist.py** generated source
    **cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Release**
    <details>
    <summary>Terminal errors</summary>

    ```
    linux@VirtualBox:~/test/devilutionx-src-1.3.0-cacf55bb$ cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Release
    -- Detected a source distribution with the required FetchContent dependencies and devilutionx.mpq included
    -- The C compiler identification is GNU 11.2.0
    -- The CXX compiler identification is GNU 11.2.0
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Check for working C compiler: /usr/bin/cc - skipped
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Check for working CXX compiler: /usr/bin/c++ - skipped
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Looking for pthread.h
    -- Looking for pthread.h - found
    -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
    -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
    -- Found Threads: TRUE  
    -- 📚 SDL2: dynamic system library
    -- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2") 
    -- Found SDL_image
    -- 📚 SDL_image: dynamic system library
    -- Found SDL2_image: /usr/include/SDL2  
    -- 📚 SDL_audiolib: static library from source
    -- Performing Test HAVE_STD_CLAMP
    -- Performing Test HAVE_STD_CLAMP - Success
    -- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
    -- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
    -- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
    -- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
    -- Performing Test COMPILER_HAS_DEPRECATED_ATTR
    -- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
    -- 📚 libsodium: dynamic system library
    -- Found sodium: /usr/lib/x86_64-linux-gnu/libsodium.so (found version "1.0.18") 
    -- Suitable system fmt package not found, will use fmt from source
    -- 📚 libfmt: static library from source
    -- Version: 7.1.3
    -- Build type: Release
    -- CXX_STANDARD: 17
    -- Performing Test has_std_17_flag
    -- Performing Test has_std_17_flag - Success
    -- Performing Test has_std_1z_flag
    -- Performing Test has_std_1z_flag - Success
    -- Performing Test SUPPORTS_USER_DEFINED_LITERALS
    -- Performing Test SUPPORTS_USER_DEFINED_LITERALS - Success
    -- Performing Test FMT_HAS_VARIANT
    - - Performing Test FMT_HAS_VARIANT - Success
    -- Required features: cxx_variadic_templates
    -- Looking for strtod_l
    -- Looking for strtod_l - not found
    -- 📚 bzip2: dynamic system library
    -- Found BZip2: /usr/lib/x86_64-linux-gnu/libbz2.so (found version "1.0.8") 
    -- Looking for BZ2_bzCompressInit
    -- Looking for BZ2_bzCompressInit - found
    -- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11") 
    CMake Error at 3rdParty/libzt/CMakeLists.txt:16 (target_compile_options):
      Cannot specify compile options for target "zto_obj" which is not built by
      this project.
    
    
    CMake Error at 3rdParty/libzt/CMakeLists.txt:17 (target_compile_options):
      Cannot specify compile options for target "libnatpmp_obj" which is not
      built by this project.


    CMake Error at 3rdParty/libzt/CMakeLists.txt:18 (target_compile_options):
      Cannot specify compile options for target "libzt_obj" which is not built by
      this project.


    CMake Error at 3rdParty/libzt/CMakeLists.txt:19 (target_compile_options):
      Cannot specify compile options for target "lwip_obj" which is not built by
      this project.


    CMake Error at 3rdParty/libzt/CMakeLists.txt:20 (target_compile_options):
      Cannot specify compile options for target "miniupnpc_obj" which is not
      built by this project.


    CMake Error at 3rdParty/libzt/CMakeLists.txt:21 (target_compile_options):
      Cannot specify compile options for target "zt-static" which is not built by
      this project.


    CMake Error at 3rdParty/libzt/CMakeLists.txt:24 (target_compile_options):
      Cannot specify compile options for target "zto_obj" which is not built by
      this project.


    CMake Error at 3rdParty/libzt/CMakeLists.txt:25 (target_compile_options):
      Cannot specify compile options for target "libzt_obj" which is not built by
      this project.


    CMake Error at 3rdParty/libzt/CMakeLists.txt:26 (target_compile_options):
      Cannot specify compile options for target "zt-static" which is not built by
      this project.


    CMake Error at 3rdParty/libzt/CMakeLists.txt:29 (target_include_directories):
      Cannot specify include directories for target "zt-static" which is not
      built by this project.


    CMake Error at 3rdParty/libzt/CMakeLists.txt:38 (target_include_directories):
      Cannot specify include directories for target "zt-static" which is not
      built by this project.


    -- 📚 googletest: dynamic system library
    -- Found GTest: /usr/lib/x86_64-linux-gnu/cmake/GTest/GTestConfig.cmake (found version "1.11.0")  
    -- Found Gettext: /usr/bin/msgmerge (found version "0.21") 
    -- Configuring incomplete, errors occurred!
    See also "/home/goran/test/devilutionx-src-1.3.0-cacf55bb/build/CMakeFiles/CMakeOutput.log".
    See also "/home/goran/test/devilutionx-src-1.3.0-cacf55bb/build/CMakeFiles/CMakeError.log".

    ```

    </details>
3. Case:
     **python3 make_src_dist.py --fully_vendored** generated source
    **cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Release**
    <details>
    <summary>Terminal output</summary>

    ```
    linux@VirtualBox:~/test/devilutionx-src-full-1.3.0-cacf55bb$ cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Release
    -- Detected a source distribution with the required FetchContent dependencies and devilutionx.mpq included
    -- 📚 SDL2: static library from source
    -- 📚 SDL_image: static library from source
    -- 📚 libpng: static library from source
    CMake Error at 3rdParty/libpng/CMakeLists.txt:33 (target_include_directories):
      Cannot specify include directories for target "png_static" which is not
      built by this project.


    CMake Error at 3rdParty/libpng/CMakeLists.txt:37 (add_library):
      add_library cannot create ALIAS target "PNG::PNG" because target
      "png_static" does not already exist.


    -- 📚 SDL_audiolib: static library from source
    -- 📚 libsodium: static library from source
    -- 📚 libfmt: static library from source
    -- 📚 bzip2: static library from source
    CMake Error at 3rdParty/libzt/CMakeLists.txt:16 (target_compile_options):
      Cannot specify compile options for target "zto_obj" which is not built by
      this project.


    CMake Error at 3rdParty/libzt/CMakeLists.txt:17 (target_compile_options):
      Cannot specify compile options for target "libnatpmp_obj" which is not
      built by this project.


    CMake Error at 3rdParty/libzt/CMakeLists.txt:18 (target_compile_options):
      Cannot specify compile options for target "libzt_obj" which is not built by
      this project.


    CMake Error at 3rdParty/libzt/CMakeLists.txt:19 (target_compile_options):
      Cannot specify compile options for target "lwip_obj" which is not built by
      this project.


    CMake Error at 3rdParty/libzt/CMakeLists.txt:20 (target_compile_options):
      Cannot specify compile options for target "miniupnpc_obj" which is not
      built by this project.


    CMake Error at 3rdParty/libzt/CMakeLists.txt:21 (target_compile_options):
      Cannot specify compile options for target "zt-static" which is not built by
      this project.


    CMake Error at 3rdParty/libzt/CMakeLists.txt:24 (target_compile_options):
      Cannot specify compile options for target "zto_obj" which is not built by
      this project.


    CMake Error at 3rdParty/libzt/CMakeLists.txt:25 (target_compile_options):
      Cannot specify compile options for target "libzt_obj" which is not built by
      this project.


    CMake Error at 3rdParty/libzt/CMakeLists.txt:26 (target_compile_options):
      Cannot specify compile options for target "zt-static" which is not built by
      this project.


    CMake Error at 3rdParty/libzt/CMakeLists.txt:29 (target_include_directories):
      Cannot specify include directories for target "zt-static" which is not
      built by this project.


    CMake Error at 3rdParty/libzt/CMakeLists.txt:38 (target_include_directories):
      Cannot specify include directories for target "zt-static" which is not
      built by this project.


    -- Configuring incomplete, errors occurred!
    See also "/home/goran/test/devilutionx-src-full-1.3.0-cacf55bb/build/CMakeFiles/CMakeOutput.log".

    ```

    </details>

**Comment by glebm** [comment] 2021-12-22 13:37
That is very odd. By the way, I'm not sure if it matters, but so far we've been running `make_src_dist.py` from the root directory:

```
tools/make_src_dist.py
```

From your log it seems you're running:

```
cd tools && make_src_dist.py
```

**Comment by glebm** [comment] 2021-12-22 13:56
>  Cannot specify include directories for target "png_static" which is not built by this project.
>  Cannot specify compile options for target "zto_obj" which is not built by this project.

^ very odd, no idea what's up with these

**Comment by muzena** [comment] 2021-12-22 14:58
> That is very odd. By the way, I'm not sure if it matters, but so far we've been running `make_src_dist.py` from the root directory:

I tried this, same thing, maybe missing some other build dependencies.

**Comment by AJenbo** [comment] 2021-12-22 16:23
> I'm testing compilation in Virtualbox Ubuntu 22.04, to avoid problem with older dependencies.

Please use a supported version like 20.04 or 21.10, throwing an unstable beta that we can't accurately replicate is going to complicate things.

Give us the exact commit has that you are operating on.

Give us the full set of commands

are you starting fresh between each case or building on top of the previous?

Why are you still writing it as comments on a closed issue and not creating a new issue regarding building from the dist src?

**Comment by muzena** [comment] 2022-01-08 18:07
I'm trying to setup Launchpad PPA autobuilds.
I added [dist](https://github.com/muzena/devilutionX/tree/debian_build/dist) dir with all dependencies and **-DBUILD_ASSETS_MPQ=ON** flag to cmake.
For **amd64** and **armhf** architecture build works, for **arm64** and **ppc64el** builds failed.
[Build logs](https://code.launchpad.net/~devilutionx/+recipe/devilutionx-test)
Why builds this failed?

**Comment by AJenbo** [comment] 2022-01-08 18:18
Please open a new issue, this one is becoming a mess and is already closed.
