### ISSUE TITLE
Overlords are not moving

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#6016] opened 2023-04-21 17:37 UTC
### Operating System

Linux x64

### DevilutionX version

Custom build (c91feb71f9d3cfc9c69adf6650a74104e31798a4)

### Describe

The issue looks similar to #3118 except that the leader is not present at all.
It looks like a group and this group lacks a leader.
The group members are probably waiting for the actions of the leader, but due to his absence they only watching around.
In other words: Overlords are waiting for Christmas
The fact that the leader is missing is probably the issue.

![screen](https://user-images.githubusercontent.com/45902449/233699439-9557f83a-a80c-4dad-a685-1ad56913fe3d.png)

Savegame:
[single_0.hsv.zip](https://github.com/diasurgical/devilutionX/files/11298020/single_0.hsv.zip)

### To Reproduce

Load attached game.

### Expected Behavior

An enemy group should not lack a leader and and should not stuck.

**Comment by FitzRoyX** [comment] 2023-04-21 22:33
Are you sure this isn't a dupe of other reports you've made such as #3129 and #2232?

**Comment by xavier-sb** [comment] 2023-04-21 23:58
I grabbed the save file and checked it out.
1) The only Overlord boss (or "leader" as you put it) is Bilefroth the Pit Master, and he spawns on dlvl 6, not dlvl 7.  There are no Overlord types that can spawn on dlvl 7, so it's not an issue of the boss not spawning.
2) Not sure why these guys are stuck, but if you stun one of them, or get close enough for one to attack you, that one will break free and resume normal behavior.  Also they are all lacking the advanced hp to be considered part of a pack.

**Comment by StephenCWills** [comment] 2023-04-22 00:07
It's because `monster.var2` is extremely negative, like -26k. I think it goes up by 1 per frame and needs to reach 20 for them to choose to start walking, so if you stay more than a couple tiles away and decide to wait it out, they ought to start moving after about 20-25 mins.

https://github.com/diasurgical/devilutionX/blob/ef7c36c744c97723631b8cd469b61a6f08b3323d/Source/monster.cpp#L2022-L2028

However, I have no idea what `monster.var2` is for, so it's hard for me to say how it got that way.

**Comment by AJenbo** [comment] 2023-04-22 00:46
I think I might have seen similar behavior in a few monsters on crypt while testing things this week.

**Comment by galaxyhaxz** [comment] 2023-04-22 22:01
Your Seed: 903507905

From hindsight it seems to be you had a partial dungeon reset. `_mVar2` was documented to be trashed by some sources, so you're not the first to experience this. As you can see, loading the same seed fresh produces this:

![DIABLO_20230422_215726](https://user-images.githubusercontent.com/65138215/233808255-a0bdebd9-bcb6-4cf0-a4e3-1531fc3f14ca.png)

Gorestone always spawns at this location, with the red palette, and those two torches on the wall. Yours looks different. Did you load the save with vanilla at all? Did you go to another dungeon level and come back to 7? Did you save the game, quit, and resume later?

**Comment by AJenbo** [comment] 2023-04-22 22:32
@galaxyhaxz object placement and monster placment is not retained between versions as the save game will overwrite this data. So we allow fixing bugs that affects things like that. But monster types should be fixed so it's odd that you got different monster types apparently.

Interesting, allowing them to attack you or pushing them via TK causes them to work correctly again.

**Comment by galaxyhaxz** [comment] 2023-04-22 22:41
Right, but the fact a unique monster spawns exactly in the same location as those frozen overlords, OP suggesting they missed a leader, I find suspicious. I didn't have a debug build of DevX handy to test a fresh roll of the map, so used vanilla Hellfire.

**Comment by AJenbo** [comment] 2023-04-22 22:45
I was unable to replicate this after resetting the level, so it might have been a temp issue in an earlier build or cosmic rays :shrug:

**Comment by AJenbo** [comment] 2023-04-23 10:03
If you have a debug version open the chat and write:
- goto 0
- restart <dlvl>
- goto <dlvl>

**Comment by AJenbo** [comment] 2023-06-04 21:49
@Chance4us for getting the seed just type `/seedinfo`

**Comment by StephenCWills** [comment] 2023-07-21 03:36
In this case, it seems that Blighthorn Steelmace spawns here in vanilla.

![image](https://github.com/diasurgical/devilutionX/assets/9203145/1ce580c7-1f63-4191-8433-5b1284a45527)

**Comment by StephenCWills** [comment] 2023-07-21 14:23
The unique monsters in vanilla is just a red herring. `MonsterIdle()` increments `Monster::var2` every frame, and there is no bounds checking. DevilutionX reduced the size of the data type from `int` to `int16_t` so it only takes a little over 27 minutes for the variable to overflow. I checked @NiteKat's VOD and confirmed that he actually did spend a little over 30 mins on dlvl 7 before encountering these Overlords.

**Closed** 2023-07-26 19:48 UTC
Labels: Insufficient information
