### ISSUE TITLE
Crash on New 3DS XL

### ISSUE THREAD

**Issue by DrakeVanLyon** [diasurgical/devilutionX#3690] opened 2021-12-06 18:43 UTC
Playing in Hellfire mode all the way up to level 13 it went smoothly up until now, aside from the occasional crash I'd get when exiting the game.

I experience this crash as soon as I enter the stairwell leading to level 14 of the labyrinth. And there doesn't seem to be anything I can do to change the outcome.

**Comment by glebm** [comment] 2021-12-06 21:47
This could be another instance of the bug in the dungeon generator https://github.com/diasurgical/devilutionX/issues/1614

@DrakeVanLyon Can you please attach a save game just before the stairs to lvl 14?

**Comment by DrakeVanLyon** [comment] 2021-12-07 05:06
[save.zip](https://github.com/diasurgical/devilutionX/files/7665617/save.zip)
Here it is

**Comment by StephenCWills** [comment] 2021-12-07 05:54
Reproduced on 3DS using 1.3.0, but could not reproduce on master. I feel it's highly likely this is the same as the issue described in #3540. Regardless, since this appears to be resolved in master, I'm closing this issue.

---

@DrakeVanLyon You are free to use the latest test build in which the issue has been fixed. However, keep in mind that there is currently another bug in an upstream library that is causing crashes due to audio race conditions. You'll have to [play with audio disabled](https://github.com/diasurgical/devilutionX/wiki/DevilutionX-diablo.ini-configuration-guide#Audio) to avoid the crashes.

https://74661-143324737-gh.circle-artifacts.com/0/devilutionx.cia

**Closed by StephenCWills** 2021-12-07 05:54 UTC
Labels: 3DS

**Comment by DrakeVanLyon** [comment] 2021-12-07 17:16
@StephenCWills Thank you for the test build. I'm glad to continue my game so far :)
