### ISSUE TITLE
Beeps if I try to move the mouse

### ISSUE THREAD

**Issue by BF3000** [diasurgical/devilutionX#192] opened 2019-07-20 14:25 UTC
Windows 10, last public 0.4.0 build.
Everything fine in the game menus, but ingame it work quite strange. If I try to move the mouse, game work really slowly and system gives me "critical error" beeps.
Looks like some mouse input related bug.
And it works fine on my second pc.
Edit:
How it look
https://youtu.be/RrJK2pZeNgM

**Comment by AJenbo** [comment] 2019-07-20 15:09
Check your CPU temperature. Any idea what's different between the two systems?

**Comment by BF3000** [comment] 2019-07-20 15:51
Well, everything is different.
Main PC
Cpu: Intel® Core™ i5-4570 Processor (6M Cache, 3.2GHz, tb up to 3.60GHz)
Cooler: GlacialTech Igloo H58 PWM
M.b.: ASUS Z87-A
Ram: 16 Gb (2x4Gb Corsair XMS3 CL9 1600MHz + 2x4Gb Corsair Vengeance CL9 1600MHz)
Video: Palit PA-GTX1060 Jetstream 6G
SSD Kingston 240Gb HyperX Savage SHSS37A/240G (SATA3)
HDD 640Gb Seagate ST3640323AS (SATA2)
HDD 1Tb Samsung EcoGreen SMH-HD105SI (SATA2)
HDD 1.5Tb Samsung EcoGreen HD154UI F2 (SATA2)
HDD 3Tb Seagate ST3000DM001 7200.14 (SATA3)
SB: X-Fi Titanium OEM PCI-e (880).
Mouse Logitech G500

Cecond PC
Core i3 6100
Gigabyte GA-H110M-S2
MSI GeForce GT750 Ti
8Gb DDR4
SSD Silicon Power SP120GBSS3V55S25 (SATA3)
HDD Hitachi 320Gb (SATA)
HDD WD 1Tb (SATA)
SB: Schiit Fulla USB
Mouse Microsoft (Razer) Habu
Both with Windows 10 x64

**Comment by AJenbo** [comment] 2019-07-20 16:35
I'm not so much asking what is different about the computers specs but more about there configurations. Try narrowing it down either by making sure the installations are identical (could install Linux on a USB and test it on both machines).

Since the main suspect for me would be the temperature (if the cooler is incorrectly attached it doesn't matter how over-dimensioned it is) then it would at least help to disprove that theory if you can get your CPU core temperature from while this is happening.

Also, check the games console for warnings/errors and check your event viewer and other logs to see if it list some messages that correspond to the warning beeps.

**Comment by BF3000** [comment] 2019-07-20 16:56
![Coretremp](https://user-images.githubusercontent.com/1564077/61581533-b76f5580-ab49-11e9-89f4-f0ca63aa95d5.jpg)
I dont know why you continue to blame my cpu temperature, but there is nothing wrong with it.

**Comment by BF3000** [comment] 2019-07-20 16:59
> DUMMY: SetUnhandledExceptionFilter @ /home/mk/src/diasurgical-devilutionX.git/SourceX/miniwin/misc.cpp:507
DUMMY: GetSystemInfo @ /home/mk/src/diasurgical-devilutionX.git/SourceX/miniwin/misc.cpp:573
DUMMY: CreateFileMappingA @ /home/mk/src/diasurgical-devilutionX.git/SourceX/miniwin/misc.cpp:665
DUMMY: FindWindowA : class: DIABLO window: (null)
DUMMY: LoadIconA @ /home/mk/src/diasurgical-devilutionX.git/SourceX/miniwin/misc.cpp:431
DUMMY: LoadCursorA @ /home/mk/src/diasurgical-devilutionX.git/SourceX/miniwin/misc.cpp:446
DUMMY: LoadImageA @ /home/mk/src/diasurgical-devilutionX.git/SourceX/miniwin/misc.cpp:440
DUMMY: RegisterClassExA @ /home/mk/src/diasurgical-devilutionX.git/SourceX/miniwin/misc.cpp:399
DUMMY: UpdateWindow @ /home/mk/src/diasurgical-devilutionX.git/SourceX/miniwin/misc.cpp:382
DUMMY: UiAppActivate @ /home/mk/src/diasurgical-devilutionX.git/SourceX/DiabloUI/diabloui.cpp:422
DUMMY: GetWindowLongA @ /home/mk/src/diasurgical-devilutionX.git/SourceX/miniwin/misc.cpp:778
DUMMY: SetWindowLongA @ /home/mk/src/diasurgical-devilutionX.git/SourceX/miniwin/misc.cpp:784
DUMMY: SDrawRealizePalette @ /home/mk/src/diasurgical-devilutionX.git/SourceX/storm/storm.cpp:705
DUMMY: DefWindowProcA @ /home/mk/src/diasurgical-devilutionX.git/SourceX/miniwin/misc.cpp:769
DUMMY: SetCooperativeLevel @ /home/mk/src/diasurgical-devilutionX.git/SourceX/miniwin/ddraw.cpp:100
DUMMY: SetDisplayMode @ /home/mk/src/diasurgical-devilutionX.git/SourceX/miniwin/ddraw.cpp:106
DUMMY: CreateSurface @ /home/mk/src/diasurgical-devilutionX.git/SourceX/miniwin/ddraw.cpp:57
DUMMY: CreatePalette @ /home/mk/src/diasurgical-devilutionX.git/SourceX/miniwin/ddraw.cpp:42
DUMMY: SetPalette @ /home/mk/src/diasurgical-devilutionX.git/SourceX/miniwin/ddraw.cpp:203
DUMMY: GdiSetBatchLimit @ /home/mk/src/diasurgical-devilutionX.git/SourceX/miniwin/misc.cpp:270
DUMMY: GetCaps @ /home/mk/src/diasurgical-devilutionX.git/SourceX/miniwin/ddraw.cpp:159
DUMMY: CreateSurface @ /home/mk/src/diasurgical-devilutionX.git/SourceX/miniwin/ddraw.cpp:57
DUMMY: SDrawManualInitialize @ /home/mk/src/diasurgical-devilutionX.git/SourceX/storm/storm_dx.cpp:19
DUMMY: WaitForVerticalBlank @ /home/mk/src/diasurgical-devilutionX.git/SourceX/miniwin/ddraw.cpp:116
DUMMY: BltFast @ /home/mk/src/diasurgical-devilutionX.git/SourceX/miniwin/ddraw.cpp:136
DUMMY: Unlock @ /home/mk/src/diasurgical-devilutionX.git/SourceX/miniwin/ddraw.cpp:209
DUMMY: sound_DirectSoundCreate @ /home/mk/src/diasurgical-devilutionX.git/SourceX/sound.cpp:409
DUMMY: SVidInitialize @ /home/mk/src/diasurgical-devilutionX.git/SourceX/storm/storm.cpp:424
DUMMY: GetFileVersionInfoSizeA @ /home/mk/src/diasurgical-devilutionX.git/SourceX/miniwin/misc.cpp:167
DUMMY: GetFileVersionInfoA @ /home/mk/src/diasurgical-devilutionX.git/SourceX/miniwin/misc.cpp:175
DUMMY: VerQueryValueA @ /home/mk/src/diasurgical-devilutionX.git/SourceX/miniwin/misc.cpp:183
BasePath: F:\Games\Diablo\
DUMMY: SFileSetBasePath @ /home/mk/src/diasurgical-devilutionX.git/SourceX/storm/storm.cpp:699
BasePath: F:\Games\Diablo\
DUMMY: SFileSetBasePath @ /home/mk/src/diasurgical-devilutionX.git/SourceX/storm/storm.cpp:699
DUMMY: sound_CreateSoundBuffer @ /home/mk/src/diasurgical-devilutionX.git/SourceX/sound.cpp:274
DUMMY: InvalidateRect @ /home/mk/src/diasurgical-devilutionX.git/SourceX/miniwin/misc.cpp:373
DUMMY: UpdateWindow @ /home/mk/src/diasurgical-devilutionX.git/SourceX/miniwin/misc.cpp:382
DUMMY: PeekMessageA : unknown SDL message 0x1100
DUMMY: false_avail : return false although event avaliable
DUMMY: PeekMessageA : unknown SDL message 0x1100
DUMMY: false_avail : return false although event avaliable
DUMMY: PeekMessageA : unknown SDL message 0x1100
DUMMY: false_avail : return false although event avaliable
DUMMY: PeekMessageA : unknown SDL message 0x1100
DUMMY: false_avail : return false although event avaliable
DUMMY: false_avail : return false although event avaliable
DUMMY: false_avail : return false although event avaliable
DUMMY: false_avail : return false although event avaliable
DUMMY: false_avail : return false although event avaliable
DUMMY: false_avail : return false although event avaliable
DUMMY: PeekMessageA : unknown SDL message 0x302
DUMMY: false_avail : return false although event avaliable
DUMMY: false_avail : return false although event avaliable
DUMMY: DispatchMessageA @ /home/mk/src/diasurgical-devilutionX.git/SourceX/miniwin/misc_msg.cpp:290
DUMMY: false_avail : return false although event avaliable
DUMMY: false_avail : return false although event avaliable
DUMMY: false_avail : return false although event avaliable
DUMMY: SDrawGetFrameWindow @ /home/mk/src/diasurgical-devilutionX.git/SourceX/storm/storm.cpp:307
DUMMY: UiProfileGetString @ /home/mk/src/diasurgical-devilutionX.git/SourceX/DiabloUI/diabloui.cpp:386
DUMMY: UiSetupPlayerInfo @ /home/mk/src/diasurgical-devilutionX.git/SourceX/DiabloUI/diabloui.cpp:394
DUMMY: SNetGetGameInfo @ /home/mk/src/diasurgical-devilutionX.git/SourceX/storm/storm_net.cpp:72
DUMMY: SNetGetGameInfo @ /home/mk/src/diasurgical-devilutionX.git/SourceX/storm/storm_net.cpp:72
DUMMY: Lock @ /home/mk/src/diasurgical-devilutionX.git/SourceX/miniwin/ddraw.cpp:184
DUMMY: IsLost @ /home/mk/src/diasurgical-devilutionX.git/SourceX/miniwin/ddraw.cpp:178
DUMMY: CreateFileA : file: c:\users\bf300\appdata\roaming\diasurgical\devilution\single_0.sv (c:/users/bf300/appdata/roaming/diasurgical/devilution/single_0.sv)
DUMMY: SDrawRealizePalette @ /home/mk/src/diasurgical-devilutionX.git/SourceX/storm/storm.cpp:705
DUMMY: false_avail : return false although event avaliable
DUMMY: false_avail : return false although event avaliable
DUMMY: false_avail : return false although event avaliable
DUMMY: false_avail : return false although event avaliable
DUMMY: false_avail : return false although event avaliable
DUMMY: false_avail : return false although event avaliable

**Comment by BF3000** [comment] 2019-07-20 17:00
DUMMY: SetUnhandledExceptionFilter @ /home/ajenbo/code/diablo/devilutionX/SourceX/miniwin/misc.cpp:507
DUMMY: GetSystemInfo @ /home/ajenbo/code/diablo/devilutionX/SourceX/miniwin/misc.cpp:573
DUMMY: CreateFileMappingA @ /home/ajenbo/code/diablo/devilutionX/SourceX/miniwin/misc.cpp:665
DUMMY: FindWindowA : class: DIABLO window: (null)
DUMMY: LoadIconA @ /home/ajenbo/code/diablo/devilutionX/SourceX/miniwin/misc.cpp:431
DUMMY: LoadCursorA @ /home/ajenbo/code/diablo/devilutionX/SourceX/miniwin/misc.cpp:446
DUMMY: LoadImageA @ /home/ajenbo/code/diablo/devilutionX/SourceX/miniwin/misc.cpp:440
DUMMY: RegisterClassExA @ /home/ajenbo/code/diablo/devilutionX/SourceX/miniwin/misc.cpp:399
DUMMY: UpdateWindow @ /home/ajenbo/code/diablo/devilutionX/SourceX/miniwin/misc.cpp:382
DUMMY: UiAppActivate @ /home/ajenbo/code/diablo/devilutionX/SourceX/DiabloUI/diabloui.cpp:422
DUMMY: GetWindowLongA @ /home/ajenbo/code/diablo/devilutionX/SourceX/miniwin/misc.cpp:778
DUMMY: SetWindowLongA @ /home/ajenbo/code/diablo/devilutionX/SourceX/miniwin/misc.cpp:784
DUMMY: SDrawRealizePalette @ /home/ajenbo/code/diablo/devilutionX/SourceX/storm/storm.cpp:705
DUMMY: DefWindowProcA @ /home/ajenbo/code/diablo/devilutionX/SourceX/miniwin/misc.cpp:769
DUMMY: SetCooperativeLevel @ /home/ajenbo/code/diablo/devilutionX/SourceX/miniwin/ddraw.cpp:100
DUMMY: SetDisplayMode @ /home/ajenbo/code/diablo/devilutionX/SourceX/miniwin/ddraw.cpp:106
DUMMY: CreateSurface @ /home/ajenbo/code/diablo/devilutionX/SourceX/miniwin/ddraw.cpp:57
DUMMY: CreatePalette @ /home/ajenbo/code/diablo/devilutionX/SourceX/miniwin/ddraw.cpp:42
DUMMY: SetPalette @ /home/ajenbo/code/diablo/devilutionX/SourceX/miniwin/ddraw.cpp:203
DUMMY: GdiSetBatchLimit @ /home/ajenbo/code/diablo/devilutionX/SourceX/miniwin/misc.cpp:270
DUMMY: GetCaps @ /home/ajenbo/code/diablo/devilutionX/SourceX/miniwin/ddraw.cpp:159
DUMMY: CreateSurface @ /home/ajenbo/code/diablo/devilutionX/SourceX/miniwin/ddraw.cpp:57
DUMMY: SDrawManualInitialize @ /home/ajenbo/code/diablo/devilutionX/SourceX/storm/storm_dx.cpp:19
DUMMY: WaitForVerticalBlank @ /home/ajenbo/code/diablo/devilutionX/SourceX/miniwin/ddraw.cpp:116
DUMMY: BltFast @ /home/ajenbo/code/diablo/devilutionX/SourceX/miniwin/ddraw.cpp:136
DUMMY: Unlock @ /home/ajenbo/code/diablo/devilutionX/SourceX/miniwin/ddraw.cpp:209
DUMMY: sound_DirectSoundCreate @ /home/ajenbo/code/diablo/devilutionX/SourceX/sound.cpp:409
DUMMY: SVidInitialize @ /home/ajenbo/code/diablo/devilutionX/SourceX/storm/storm.cpp:424
DUMMY: GetFileVersionInfoSizeA @ /home/ajenbo/code/diablo/devilutionX/SourceX/miniwin/misc.cpp:167
DUMMY: GetFileVersionInfoA @ /home/ajenbo/code/diablo/devilutionX/SourceX/miniwin/misc.cpp:175
DUMMY: VerQueryValueA @ /home/ajenbo/code/diablo/devilutionX/SourceX/miniwin/misc.cpp:183
BasePath: F:\Games\Diablo\
DUMMY: SFileSetBasePath @ /home/ajenbo/code/diablo/devilutionX/SourceX/storm/storm.cpp:699
BasePath: F:\Games\Diablo\
DUMMY: SFileSetBasePath @ /home/ajenbo/code/diablo/devilutionX/SourceX/storm/storm.cpp:699
DUMMY: sound_CreateSoundBuffer @ /home/ajenbo/code/diablo/devilutionX/SourceX/sound.cpp:274
DUMMY: InvalidateRect @ /home/ajenbo/code/diablo/devilutionX/SourceX/miniwin/misc.cpp:373
DUMMY: UpdateWindow @ /home/ajenbo/code/diablo/devilutionX/SourceX/miniwin/misc.cpp:382
DUMMY: PeekMessageA : unknown SDL message 0x1100
DUMMY: false_avail : return false although event avaliable
DUMMY: PeekMessageA : unknown SDL message 0x1100
DUMMY: false_avail : return false although event avaliable
DUMMY: PeekMessageA : unknown SDL message 0x1100
DUMMY: false_avail : return false although event avaliable
DUMMY: PeekMessageA : unknown SDL message 0x1100
DUMMY: false_avail : return false although event avaliable
DUMMY: false_avail : return false although event avaliable
DUMMY: false_avail : return false although event avaliable
DUMMY: false_avail : return false although event avaliable
DUMMY: false_avail : return false although event avaliable
DUMMY: false_avail : return false although event avaliable
DUMMY: PeekMessageA : unknown SDL message 0x302
DUMMY: false_avail : return false although event avaliable
DUMMY: false_avail : return false although event avaliable
DUMMY: DispatchMessageA @ /home/ajenbo/code/diablo/devilutionX/SourceX/miniwin/misc_msg.cpp:284
DUMMY: false_avail : return false although event avaliable
DUMMY: false_avail : return false although event avaliable
DUMMY: PostMessageA @ /home/ajenbo/code/diablo/devilutionX/SourceX/miniwin/misc_msg.cpp:294
DUMMY: SDrawGetFrameWindow @ /home/ajenbo/code/diablo/devilutionX/SourceX/storm/storm.cpp:307
DUMMY: UiProfileGetString @ /home/ajenbo/code/diablo/devilutionX/SourceX/DiabloUI/diabloui.cpp:386
DUMMY: UiSetupPlayerInfo @ /home/ajenbo/code/diablo/devilutionX/SourceX/DiabloUI/diabloui.cpp:394
DUMMY: SNetGetGameInfo @ /home/ajenbo/code/diablo/devilutionX/SourceX/storm/storm_net.cpp:72
DUMMY: SNetGetGameInfo @ /home/ajenbo/code/diablo/devilutionX/SourceX/storm/storm_net.cpp:72
DUMMY: Lock @ /home/ajenbo/code/diablo/devilutionX/SourceX/miniwin/ddraw.cpp:184
DUMMY: IsLost @ /home/ajenbo/code/diablo/devilutionX/SourceX/miniwin/ddraw.cpp:178
DUMMY: CreateFileA : file: c:\users\bf300\appdata\roaming\diasurgical\devilution\single_0.sv (c:/users/bf300/appdata/roaming/diasurgical/devilution/single_0.sv)
DUMMY: SDrawRealizePalette @ /home/ajenbo/code/diablo/devilutionX/SourceX/storm/storm.cpp:705
DUMMY: translate_sdl_key : unknown key: name=Left Alt sym=0x400000E2 scan=226 mod=0x1100
DUMMY: false_avail : return false although event avaliable
DUMMY: translate_sdl_key : unknown key: name=Left Alt sym=0x400000E2 scan=226 mod=0x1000
DUMMY: false_avail : return false although event avaliable
DUMMY: false_avail : return false although event avaliable
DUMMY: false_avail : return false although event avaliable
DUMMY: false_avail : return false although event avaliable
DUMMY: false_avail : return false although event avaliable
DUMMY: false_avail : return false although event avaliable
DUMMY: false_avail : return false although event avaliable

**Comment by AJenbo** [comment] 2019-07-20 17:17
> I dont know why you continue to blame my cpu temperature, but there is nothing wrong with it.
wine wine 

I'm not blaming it just trying to rule out potential sources.

The console didn't reveal anything useful, did you find anything in the event viewer?

I have attached a build of the latest master, please test it to see if you have the same issue there.
[devilutionx.zip](https://github.com/diasurgical/devilutionX/files/3413841/devilutionx.zip)
It should have better logging to the console so if you still experience the issue then please post the console from it.

**Comment by AJenbo** [comment] 2019-07-20 17:22
P.s. try turning your music and sound volume in-game to 0, that should make it easier to hear when it happens. and what it sounds like. Since you refer to it as "critical error" beeps are you familiar with what it means and what would normally cause it?

**Comment by BF3000** [comment] 2019-07-21 03:57
DUMMY: SetUnhandledExceptionFilter @ /home/ajenbo/code/diablo/devilutionX/SourceX/miniwin/misc.cpp:513
DUMMY: GetSystemInfo @ /home/ajenbo/code/diablo/devilutionX/SourceX/miniwin/misc.cpp:579
DUMMY: CreateFileMappingA @ /home/ajenbo/code/diablo/devilutionX/SourceX/miniwin/misc.cpp:671
DUMMY: FindWindowA : class: DIABLO window: (null)
DUMMY: LoadIconA @ /home/ajenbo/code/diablo/devilutionX/SourceX/miniwin/misc.cpp:437
DUMMY: LoadCursorA @ /home/ajenbo/code/diablo/devilutionX/SourceX/miniwin/misc.cpp:452
DUMMY: LoadImageA @ /home/ajenbo/code/diablo/devilutionX/SourceX/miniwin/misc.cpp:446
DUMMY: RegisterClassExA @ /home/ajenbo/code/diablo/devilutionX/SourceX/miniwin/misc.cpp:405
DUMMY: UpdateWindow @ /home/ajenbo/code/diablo/devilutionX/SourceX/miniwin/misc.cpp:388
INFO: That operation is not supported
DUMMY: UiAppActivate @ /home/ajenbo/code/diablo/devilutionX/SourceX/DiabloUI/diabloui.cpp:431
DUMMY: GetWindowLongA @ /home/ajenbo/code/diablo/devilutionX/SourceX/miniwin/misc.cpp:789
DUMMY: SetWindowLongA @ /home/ajenbo/code/diablo/devilutionX/SourceX/miniwin/misc.cpp:795
DUMMY: SDrawRealizePalette @ /home/ajenbo/code/diablo/devilutionX/SourceX/storm/storm.cpp:750
DUMMY: DefWindowProcA @ /home/ajenbo/code/diablo/devilutionX/SourceX/miniwin/misc.cpp:780
DUMMY: SetCooperativeLevel @ /home/ajenbo/code/diablo/devilutionX/SourceX/miniwin/ddraw.cpp:101
DUMMY: SetDisplayMode @ /home/ajenbo/code/diablo/devilutionX/SourceX/miniwin/ddraw.cpp:107
DUMMY: CreateSurface @ /home/ajenbo/code/diablo/devilutionX/SourceX/miniwin/ddraw.cpp:56
DUMMY: CreatePalette @ /home/ajenbo/code/diablo/devilutionX/SourceX/miniwin/ddraw.cpp:41
DUMMY: SetPalette @ /home/ajenbo/code/diablo/devilutionX/SourceX/miniwin/ddraw.cpp:204
DUMMY: GdiSetBatchLimit @ /home/ajenbo/code/diablo/devilutionX/SourceX/miniwin/misc.cpp:272
DUMMY: GetCaps @ /home/ajenbo/code/diablo/devilutionX/SourceX/miniwin/ddraw.cpp:160
DUMMY: CreateSurface @ /home/ajenbo/code/diablo/devilutionX/SourceX/miniwin/ddraw.cpp:56
DUMMY: SDrawManualInitialize @ /home/ajenbo/code/diablo/devilutionX/SourceX/storm/storm_dx.cpp:19
DUMMY: WaitForVerticalBlank @ /home/ajenbo/code/diablo/devilutionX/SourceX/miniwin/ddraw.cpp:117
DUMMY: BltFast @ /home/ajenbo/code/diablo/devilutionX/SourceX/miniwin/ddraw.cpp:137
DUMMY: Unlock @ /home/ajenbo/code/diablo/devilutionX/SourceX/miniwin/ddraw.cpp:210
DUMMY: sound_DirectSoundCreate @ /home/ajenbo/code/diablo/devilutionX/SourceX/sound.cpp:407
DUMMY: SVidInitialize @ /home/ajenbo/code/diablo/devilutionX/SourceX/storm/storm.cpp:426
DUMMY: GetFileVersionInfoSizeA @ /home/ajenbo/code/diablo/devilutionX/SourceX/miniwin/misc.cpp:168
DUMMY: GetFileVersionInfoA @ /home/ajenbo/code/diablo/devilutionX/SourceX/miniwin/misc.cpp:176
DUMMY: VerQueryValueA @ /home/ajenbo/code/diablo/devilutionX/SourceX/miniwin/misc.cpp:184
BasePath: F:\Games\Diablo\
DUMMY: SFileSetBasePath @ /home/ajenbo/code/diablo/devilutionX/SourceX/storm/storm.cpp:744
BasePath: F:\Games\Diablo\
DUMMY: SFileSetBasePath @ /home/ajenbo/code/diablo/devilutionX/SourceX/storm/storm.cpp:744
DUMMY: sound_CreateSoundBuffer @ /home/ajenbo/code/diablo/devilutionX/SourceX/sound.cpp:272
DUMMY: InvalidateRect @ /home/ajenbo/code/diablo/devilutionX/SourceX/miniwin/misc.cpp:379
DUMMY: UpdateWindow @ /home/ajenbo/code/diablo/devilutionX/SourceX/miniwin/misc.cpp:388
DUMMY: PeekMessageA : unknown SDL message 0x1100
DUMMY: false_avail : return false although event available
DUMMY: PeekMessageA : unknown SDL message 0x1100
DUMMY: false_avail : return false although event available
DUMMY: PeekMessageA : unknown SDL message 0x1100
DUMMY: false_avail : return false although event available
DUMMY: PeekMessageA : unknown SDL message 0x1100
DUMMY: false_avail : return false although event available
DUMMY: false_avail : return false although event available
DUMMY: false_avail : return false although event available
DUMMY: false_avail : return false although event available
DUMMY: false_avail : return false although event available
DUMMY: false_avail : return false although event available
DUMMY: PeekMessageA : unknown SDL message 0x302
DUMMY: false_avail : return false although event available
DUMMY: false_avail : return false although event available
DUMMY: DispatchMessageA @ /home/ajenbo/code/diablo/devilutionX/SourceX/miniwin/misc_msg.cpp:373
DUMMY: false_avail : return false although event available
DUMMY: false_avail : return false although event available
DUMMY: PostMessageA @ /home/ajenbo/code/diablo/devilutionX/SourceX/miniwin/misc_msg.cpp:383
DUMMY: SDrawGetFrameWindow @ /home/ajenbo/code/diablo/devilutionX/SourceX/storm/storm.cpp:310
DUMMY: UiProfileGetString @ /home/ajenbo/code/diablo/devilutionX/SourceX/DiabloUI/diabloui.cpp:395
DUMMY: UiSetupPlayerInfo @ /home/ajenbo/code/diablo/devilutionX/SourceX/DiabloUI/diabloui.cpp:403
DUMMY: SNetGetGameInfo @ /home/ajenbo/code/diablo/devilutionX/SourceX/storm/storm_net.cpp:72
DUMMY: SNetGetGameInfo @ /home/ajenbo/code/diablo/devilutionX/SourceX/storm/storm_net.cpp:72
DUMMY: Lock @ /home/ajenbo/code/diablo/devilutionX/SourceX/miniwin/ddraw.cpp:185
DUMMY: IsLost @ /home/ajenbo/code/diablo/devilutionX/SourceX/miniwin/ddraw.cpp:179
DUMMY: CreateFileA : file: C:\Users\bf300\AppData\Roaming\diasurgical\devilution\single_0.sv (C:/Users/bf300/AppData/Roaming/diasurgical/devilution/single_0.sv)
DUMMY: SDrawRealizePalette @ /home/ajenbo/code/diablo/devilutionX/SourceX/storm/storm.cpp:750
DUMMY: false_avail : return false although event available
DUMMY: false_avail : return false although event available
DUMMY: false_avail : return false although event available
DUMMY: false_avail : return false although event available
DUMMY: false_avail : return false although event available
DUMMY: false_avail : return false although event available

**Comment by BF3000** [comment] 2019-07-21 04:01
1) That happens if I try to move the mouse, like I told in first post. Until I move it everything is fine.
2) My main job is fixing PCs, so yes I hear sounds like that a lot. ;)

**Comment by AJenbo** [comment] 2019-07-21 04:02
There still isn't really anything in the console log that would explain it, I really think we need to look into your systems event viewer to see what the issue is.

**Comment by BF3000** [comment] 2019-07-21 06:31
Well, I finally update my windows to 1903, and the problem was solved
 I cant update earlier because of my X-Fi Titanium sound card, proper driver was released just recently.

**Comment by sskras** [comment] 2019-07-21 07:15
So the root cause is left unknown, right?

**Comment by BF3000** [comment] 2019-07-21 09:00
Yep.
The dig in the event viewer gave me nothing exept maybe this:
https://www.ghacks.net/2018/12/29/windows-10-user-profile-service-event-id-1534-warnings/
So I decided to finally update system to 1903, and it helps.

**Comment by AJenbo** [comment] 2019-07-21 12:05
@cdcseacave you might also want to take a look here.

**Comment by BF3000** [comment] 2019-07-22 12:32
And the next day it reappear again.
But I was able to fix it by disabling of "grab input" option in the diablo.ini

**Comment by Effeevee** [comment] 2019-07-23 09:35
I have the same problem on my Windows 10 machine, but as i mainly play on my Mac I haven't really had the energy to look into this.
I did a search for similar problems and I found people having the same issue back in 2016 and the problem was with Xinput on Windows 10 systems. But I think a later update fixed this or maybe it still is an issue?

https://www.reddit.com/r/Windows10/comments/49uq1o/windows_10_mouse_lagbeeping_bug/
https://www.tenforums.com/drivers-hardware/42753-random-mouse-lagging-beeping.html

**Comment by kaincenteno** [comment] 2019-07-28 07:14
My fiancee has this issue before. Let me ask and see how we resolved the issue.

**Comment by kaincenteno** [comment] 2019-08-06 20:30
@BF3000 I couldn't get much information from the fiancee but I think it was related to stuff connected to the machine.

Can you try maybe running on safe mode and running the program? Afterwards try disconnecting everything on the machine except the mouse and keyboard? see if that works?

**Comment by AJenbo** [comment] 2019-09-15 14:16
Closing this as there is no clear way to replicate it.

**Closed by AJenbo** 2019-09-15 14:16 UTC
Labels: Insufficient information
