### ISSUE TITLE
Game Crash on Load while In Game

### ISSUE THREAD

**Issue by NiteKat** [diasurgical/devilutionX#2839] opened 2021-09-10 22:33 UTC
**Important information**
Windows 10 / 1.2.1 / Downloaded Release

**Describe**
Game is crashing under specific circumstances when loading while in game.

**To Reproduce**
1. Load the attached save game.
2. Click to enter the first floor (Down to Dungeon)
3. Click the monster that's on the same tile as you so that you attack at least once.
4. Bring up the game menu while you're mid attack animation.
5. Select Load Game. Congrats your game has crashed after fading out!

**Expected behavior**
Game should load with no crash.

**Additional context**
If you do not attack, the game will not crash on load. If you let the attack animation complete, the game will not crash. If you move and attack the monster, and load mid animation it _will_ crash. If you shift attack a random tile not containing a monster, and load while mid attack animation, it _will _not__ crash. I suspect this is related to loading while in the middle of an attack on a monster that is next to you. Doing a shift attack with more than 1 tile distance does not seem to trigger the crash.

[single_0.zip](https://github.com/diasurgical/devilutionX/files/7146744/single_0.zip)

**Comment by NiteKat** [comment] 2021-09-10 22:35
Confirmed this is not a vanilla bug, and is exclusive to DevX.

**Comment by julealgon** [comment] 2021-09-10 23:00
Assigning to @obligaron on the suspicion that this is animation related.

**Comment by obligaron** [comment] 2021-09-11 05:20
I tested it in 1.2.1 and could reproduce the bug, but in master there is no crash.
So I think some of the animation changes that happened since 1.2.1 fixed this. 🙂

**Closed** 2021-09-11 15:06 UTC
Labels: bug, savegame attached
