### ISSUE TITLE
Lazarus Chamber map generation error

### ISSUE THREAD

**Issue by CaptainCosmotic** [diasurgical/devilutionX#2059] opened 2021-05-25 12:41 UTC
**Important information**
Windows 10 / DevilutionX v1.2.1 / download release
**Describe**
I was able to get out of bound in Lazarus Chamber

**To Reproduce**
1. Load the attached savegame 
2. Teleport out of bounds

**Expected behavior**
There should be solid wall

**Screenshots**
![LAZAZARUSoutofbound](https://user-images.githubusercontent.com/57239116/119497951-68a62e80-bd65-11eb-97dd-b420978cbc11.jpg)

**Savegame**
[outofbound.zip](https://github.com/diasurgical/devilutionX/files/6539232/outofbound.zip)

**Comment by AJenbo** [comment] 2021-05-25 13:06
Duplicate of https://github.com/diasurgical/devilutionX/issues/1970

**Closed by AJenbo** 2021-05-25 13:06 UTC
