### ISSUE TITLE
Items not dropping and becomming invalid when no save games are present

### ISSUE THREAD

**Issue by SoundChaser83** [diasurgical/devilutionX#1367] opened 2021-04-04 21:55 UTC
**Important information**
Windows/Wine 64/32, version 1.2.0

**Describe**
Items become invalid when dropped in town on the very first game. This is caused the additional full `heroitems` file not being saved in the save game archive on Windows, which also means that migrating heros between diablo and hellfire will cause morphing on new game.

**To Reproduce**
1: delete all saves before starting devilutionx.
2: create a warrior
3: enter the church
4: leave the church
5: drop the club
6: the item will be stuck in mid air

**Expected behavior**
The item should drop to the ground, and it should be possible to pick it up.

**Screenshots**
![image](https://user-images.githubusercontent.com/204594/113957825-480b2f00-9820-11eb-9c18-56df2e0ee2fd.png)

**Workaround**
Simply create a save game (enter town go to the menu and select save) and then restart the game. New games should now work properly.

**Comment by AJenbo** [comment] 2021-04-04 22:20
It looks like `gbIsHellfire` ended up being `false` in the middle of a hellfire game.

If this happened in relation to the oil, or it was just the first hellfire item to drop after it happened isn't clear.

**Comment by AJenbo** [comment] 2021-04-05 08:09
I'm not able to replicate the catastrophic game state, despite the one item in town clearly being broken in the save. Tested both on Linux and a 64bit windows build using Wine.

One thing i do note is that when ever you return from a town portal to Leoric Tomb the light radious is significantly reduced and not fully processed.

But I think this shows that the issue stems from the game memory having become corrupt on the specific machine where this happened.

If someone on Windows could test what happens if they create a new game, go to Leoric Tomb and tp to and from town that would be appreciated.

**Comment by AJenbo** [comment] 2021-04-05 09:32
The lighting issue was also there in 1.1.0 and probably vanilla as well (needs verification).

**Comment by Chance4us** [comment] 2021-04-05 15:34
@SoundChaser83 Thank you very much for playtesting.That is very much appreciated here.
As I saw you played the barbarian for the first time.
The recommended strategy is an axe. The axe is faster and more damage with the barbarian.
However, you also need an item with a chance to hit or an axe with chance to hit.
Vitality goes up to 150 and that should almost always be built up.

**Comment by Chance4us** [comment] 2021-04-05 15:44
@AJenbo
Since you already talked about the damage caused by lightning wall / fire wall in the video, I  tried a game with the sorcerer on hell difficulty. I used lightning wall and fire wall to keep Leoric away.
In addition, I fired with Level 3 Holy Bolt spell.
Leoric suffered no harm. I found it strange that there was hardly any damage.
Unfortunately I didn't try it in vanilla.

**Comment by Chance4us** [comment] 2021-04-05 15:49
@AJenbo Concerning the memory corruption bug, I can say that I also experienced it, even in diablo.
Sometimes the levels were normal and I defeated every opponent in them.
Then I went on playing a lot more of the levels.
When I sometimes returned to the same level again, the doors and objects were sometimes shifted.

**Comment by glebm** [comment] 2021-04-05 16:15
I've just merged a very surprising VS2019 bugfix https://github.com/diasurgical/devilutionX/pull/1371

**Comment by Chance4us** [comment] 2021-04-05 16:35
@glebm What does it change?

**Comment by qndel** [comment] 2021-04-05 17:02
Please try to keep unrelated stuff out of issues and use discord/discussions instead @Chance4us

**Comment by AJenbo** [comment] 2021-04-05 19:07
> @AJenbo Concerning the memory corruption bug, I can say that I also experienced it, even in diablo.
> Sometimes the levels were normal and I defeated every opponent in them.
> Then I went on playing a lot more of the levels.
> When I sometimes returned to the same level again, the doors and objects were sometimes shifted.

Are you saying this happened in vanilla for you?

**Comment by glebm** [comment] 2021-04-05 20:10
> im not sure what you are asking glebm, he isnt mentioned in this issue.

I posted an unrelated comment here by mistake and deleted it immediately, that's probably what it was

**Comment by Chance4us** [comment] 2021-04-05 20:31
> We did some further testing with lightning wall / fire wall and the deal the expected damage (not the same as hellfire 1.01). ore are you saying Holy Bolt is not doing damage?

Lightning Wall / Fire Wall and Holy Bolt did not doing enough damage.
I was not able to kill Leoric at all also because he regenerated too fast.
I'm going to retest also in vanilla hellfire and to give you more precise information.

**Comment by AJenbo** [comment] 2021-04-05 21:25
@Chance4us please let me know if you meant that you had also seen this type of game corruption in vanilla Diablo as this is pivottabel regarding us moving ahead with the release.

**Comment by Chance4us** [comment] 2021-04-05 22:10
> @Chance4us please let me know if you meant that you had also seen this type of game corruption in vanilla Diablo as this is pivottabel regarding us moving ahead with the release.

I experienced it in "devilutionX Diablo", not in vanilla diablo.

**Comment by AJenbo** [comment] 2021-04-05 22:26
> > @Chance4us please let me know if you meant that you had also seen this type of game corruption in vanilla Diablo as this is pivottabel regarding us moving ahead with the release.
> 
> I experienced it in "devilutionX Diablo", not in vanilla diablo.

What version was that, or roughly how long ago (1.1.0 release, or a recent beta)?

**Comment by Chance4us** [comment] 2021-04-05 22:34
It has been a while. I experienced it twice.
"DevilutionX Diablo" was the least 1.0.0 version as I experienced it.
"DevilutionX Hellfire" was the least 1.1.0 version as I experienced it.

**Comment by AJenbo** [comment] 2021-04-05 22:39
Ok, if you have seen it as fare back as 1.0.0 it is at least not a regression and probably something that we will get fixed along with all the planned cleanups and improvments. Thanks for the insight.

**Comment by Chance4us** [comment] 2021-04-06 18:31
Attached eight parts of playtesting. Some videos have artifacts because the recording is not fast enough. Sorry for that.
Part 1: Vanilla Hellfire kill butcher [hell] [firewall level 1]:
[butcher_firewall_vanilla-hellfire.mkv.zip](https://github.com/diasurgical/devilutionX/files/6266717/butcher_firewall_vanilla-hellfire.mkv.zip)
Part 2: DevilutionX Hellfire kill butcher [hell] [firewall level 1]:
[butcher_firewall_devilutionx_hellfire.mkv.zip](https://github.com/diasurgical/devilutionX/files/6266745/butcher_firewall_devilutionx_hellfire.mkv.zip)
Part 3: Vanilla Hellfire kill butcher [hell] [lightning wall level 1]:
[butcher_lightning_vanilla-hellfire.mkv.zip](https://github.com/diasurgical/devilutionX/files/6266765/butcher_lightning_vanilla-hellfire.mkv.zip)
Part 4: DevilutionX Hellfire kill butcher [hell] [lightning wall level 1]:
[butcher_lightning_devilutionx_hellfire.mkv.zip](https://github.com/diasurgical/devilutionX/files/6266815/butcher_lightning_devilutionx_hellfire.mkv.zip)
Savegame before kill:
[single_1.hsv.zip](https://github.com/diasurgical/devilutionX/files/6266819/single_1.hsv.zip)

I happened to notice a difference in experience gain.
As you can see, in vanilla the character has no experience gain when killing the butcher.
I have to say that I started the game in DevilutionX and then transferred it to Vanilla. Unclear whether it has anything to do with it regarding experience gain. The effect of the damage seems to be the same in this case.
The next parts for Leoric will follow soon.

**Comment by qndel** [comment] 2021-04-07 03:31
@Chance4us butcher gave no xp because of a bug we fixed in devilutionx
@AJenbo I don't think he has experienced actual memory corruption but the regular catas level reroll

**Comment by AJenbo** [comment] 2021-04-07 04:32
> As you can see, in vanilla the character has no experience gain when killing the butcher.

This issue is about corrupt game states where items become invalid and the levels morph. Not XP or butcher.

> The next parts for Leoric will follow soon.

What we need for this issue is to see if using town portals in Leorics Tomb has an affect on lighting in Vanilla.

**Comment by Chance4us** [comment] 2021-04-07 07:14
> This issue is about corrupt game states where items become invalid and the levels morph. Not XP or butcher. I dont see anything related to this issue in the videos?

Since SoundChaser83 mentioned that in his opinion there was too little damage when using fire wall / lightning wall, I tried to determine a difference in damage. It has nothing to do with memory corruption / lighting.

> What we need for this issue is to see if using town portals in Leorics Tomb has an affect on lighting in Vanilla.

I'll test that too. I will test everything in all possible combinations so that we are on the safe side.

**Comment by Chance4us** [comment] 2021-04-07 09:53
> If someone on Windows could test what happens if they create a new game, go to Leoric Tomb and tp to and from town that would be appreciated.

@AJenbo Do you think it is Windows related only? Doesn't it help if I try on Linux?

**Comment by AJenbo** [comment] 2021-04-07 10:41
Since I already tested it on Linux that won't be needed.

**Comment by AJenbo** [comment] 2021-04-07 19:39
The issue is that on Windows `saveheroitems` is not present after saving (loading the file from the archive return 0 bytes). The game relied on this to be working for it to set the correct game state.

The good news is that the workaround is pretty simple, simply create a save game (enter town go to the menu and select save) and then restart the game. New games should now work properly.

**Comment by Chance4us** [comment] 2021-04-07 20:12
Reproducing lighting bug:
[vanilla-run.mkv.zip](https://github.com/diasurgical/devilutionX/files/6274156/vanilla-run.mkv.zip)

The lighting is visible after change level between town/tomb.
[light-difference.mkv.zip](https://github.com/diasurgical/devilutionX/files/6274165/light-difference.mkv.zip)

Picture before entering town:
![before-town](https://user-images.githubusercontent.com/45902449/113927506-e16d1d80-97ed-11eb-8d68-96dc6491c371.png)

Picture Image after returning to the tomb. 
![after-town](https://user-images.githubusercontent.com/45902449/113927765-2c873080-97ee-11eb-8a7f-dcb48fb49a09.png)

So the bug is obviously  not related to memory corruption.

**Comment by Chance4us** [comment] 2021-04-07 20:13
> The good news is that the workaround is pretty simple, simply create a save game (enter town go to the menu and select save) and then restart the game. New games should now work properly.

How difficult is it to fix code that no workaround is needed?

**Comment by Chance4us** [comment] 2021-04-07 20:21
I would like to say one more thing about the bug with the dropping.
It also happened to me on Linux that I dropped an object in the town and couldn't pick it up.
There may be in a context and I hope that a possible fix works on all platforms.

**Comment by AJenbo** [comment] 2021-04-08 02:00
> > The good news is that the workaround is pretty simple, simply create a save game (enter town go to the menu and select save) and then restart the game. New games should now work properly.
> 
> How difficult is it to fix code that no workaround is needed?

I still don't know why this doesn't work on windows so don't know what it would take to fix.

**Comment by AJenbo** [comment] 2021-04-08 02:03
> I would like to say one more thing about the bug with dropping items.
> It also happened to me on Linux that I dropped an item in town and couldn't pick it up.
> I could pickup this item only after save/load.
> There may be in a context and I hope that a possible fix works on all platforms.

if that's the case it's a different issue and we need to find a consistent way to replicate it. I'm adding the steps to reproduce this one to the first post in this issue so that it's clear what this one is about.

Thanks for testing the lighting issue in the tomb.

**Closed** 2021-04-11 13:42 UTC
Labels: bug, platform support
