### ISSUE TITLE
[Issue Report]: Devil Kin Brute, rotation error

### ISSUE THREAD

**Issue by Chonkblonk** [diasurgical/devilutionX#6899] opened 2024-01-14 22:45 UTC
### Operating System

Windows x64

### DevilutionX version

1.5.1

### Describe

I can't really show this in a screenshot, because you'd only see it in motion, but it appears that the Devil Kin Brutes (found in the Crypt in Hellfire), do not properly call all rotations when they're supposed to.
When they are walking straight to the right, they do not display that rotation set, but rather the frames for diagonally down to the right, which looks off.

Taking a quick look at a ripped sprite sheet, it would seem that these frames do actually exist (and I'll just use these two rows to illustrate the issue):
![bild](https://github.com/diasurgical/devilutionX/assets/114463804/b9277737-d5a0-4ec2-a1c3-0ac1ac491173)

EDIT: Also, when I minimized the window to report this, DevX froze and won't respond. This happens occasionally when I shift to another window, not sure what causes that.

### To Reproduce

1. Go to Crypt with a seed which has Devil Kin Brutes
2. Get in a rightwards position from them, then watch them walk towards you.
3. I don't actually know if this happens every time, I only now noticed this, but if you don't see it, maybe there's still an error somewhere.

**Comment by StephenCWills** [comment] 2024-01-15 04:10
> Taking a quick look at a ripped sprite sheet...

Where did your sprite sheet come from? My data files from `diabdat.mpq` don't have the `expected` set of frames that you showed here.

**Comment by StephenCWills** [comment] 2024-01-15 04:44
See also #3071

**Comment by Chonkblonk** [comment] 2024-01-15 14:17
Ah, yes, some of the sheets on TSR are indeed sourced from The Hell (there's a number of issues with the posted sheets on the site tbh). Did just a quick search for "brute" and didn't see that one.

I suppose if this rotation is simply missing, the quick and dirty Doom style approach of just mirroring the left facing direction would still look better than the awkward 'strafing' it currently does.

**Comment by StephenCWills** [comment] 2024-01-15 14:30
I agree that they would look better, but I don't know that I can advocate for fixing this issue in DevilutionX. AFAIK, we'd either need to supply a replacement for `fallgw.cl2` that is mostly the same or else programmatically correct the sprites for this one animation. Both solutions feel like they're out of scope.

**Closed** 2024-01-15 15:49 UTC

**Comment by Chonkblonk** [comment] 2024-01-15 19:04
I agree that providing the graphics would be outside of DevilutionX's own scope.
However, if I one day were able to cook up a "Diablo Graphics Fix" .mpq patch for this kind of issue, and the other ones discussed in #3071 , would you guys be open to add support for using it? Like just allow the program to load the .mpq if the user provides it?

**Comment by Chonkblonk** [comment] 2024-01-15 22:18
Could such a mod be used without interfering with multiplayer or getting in the way of backwards compatibility?

**Comment by StephenCWills** [comment] 2024-01-15 22:24
If you're just overriding visual assets, then yeah. It won't interfere with anything.

**Comment by pionere** [comment] 2024-08-03 07:10
I think it is worth noting that the issue is listed in #1147.

Also the death animation (NE/NW) of "Satyr Lord" monsters (`goatld.cl2`) is also messed up.
