### ISSUE TITLE
[Issue Report]: Amulet of Warding issue

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#7450] opened 2024-10-01 12:46 UTC
### Operating System

Linux x64

### DevilutionX version

Other (commit 1078598226b0b154415ffca51ab29b619cbd04e6)

### Describe

The hero had 80 hit points thanks to all sorts of improvements.
After he was equipped with the "Amulet of Warding" in town, the save game was broken after saving.

The hit points showed the number 1, although the amulet subtracts 100 from it.
So we are actually in the negative area of the hit points.
Despite this, the hero did not die in the town.

After saving and loading the game, the game is always crashing.

Save game:
[warding.zip](https://github.com/user-attachments/files/17209543/warding.zip)

### To Reproduce

Load attached game

### Expected Behavior

No crash when loading the game

### Additional context

In vanilla the save game can be loaded flawlessly.
Attached is also a save game with the mentioned amulet in the inventory.
[single_1.hsv.zip](https://github.com/user-attachments/files/17241982/single_1.hsv.zip)

**Comment by Chance4us** [comment] 2024-10-04 11:59
Bisected and and found that the game cannot be loaded since commit 961866e1c49f03c5156514cb103f9e3b92284494.
Please also note that the game can be loaded between V. 1.4.0 and commit bd689e935987eb04a22d580822603ad81ae81d32, but the hero is invisible at first.
Only when the hero starts moving he become visible.

**Comment by kphoenix137** [comment] 2024-10-05 16:40
What's the crash message? Maybe the game is confused as the player is Schrodinger's cat at this point?

**Comment by Chance4us** [comment] 2024-10-06 18:44
> What's the crash message? Maybe the game is confused as the player is Schrodinger's cat at this point?

The following message appears in debug version.

![message](https://github.com/user-attachments/assets/34923a0b-7a1f-4540-a305-085e7fd222f1)

**Comment by kphoenix137** [comment] 2024-10-06 23:01
I've seen this kind of issue before, where the game is treating the player as if they are in a death state due to < 0 life, however they are still alive, and there is a conflict that causes the game to attempt to select a graphic that doesn't exist.

**Comment by kphoenix137** [comment] 2024-10-06 23:04
https://github.com/diasurgical/devilutionX/pull/5777

**Comment by StephenCWills** [comment] 2024-10-06 23:06
This is technically a duplicate. #6520

**Comment by kphoenix137** [comment] 2024-10-06 23:30
Duplicate of: https://github.com/diasurgical/devilutionX/issues/6520

**Closed by kphoenix137** 2024-10-06 23:30 UTC

**Comment by Chance4us** [comment] 2024-10-07 10:36
Thanks for the fix. The game can be loaded.
After I loaded the game and went into the dungeon, I took off the amulet.
But after I put it back on, the hero died.
Since then, the game can no longer be loaded.
It crashes immediately.

**Comment by Chance4us** [comment] 2024-10-07 17:31
I can't reproduce this thing anymore for now.

**Comment by AJenbo** [comment] 2025-06-06 10:00
Thanks for testing, bisecting and follow up regarding fallout
