### ISSUE TITLE
Crash when switching audio source on a Russian operating system

### ISSUE THREAD

**Issue by Venyam-N** [diasurgical/devilutionX#7452] opened 2024-10-02 21:26 UTC
### Operating System

Windows x64

### DevilutionX version

1.5.3

### Describe

The game is started sounding from my laptop's built-in speakers. Then I plug in my headphones and the game crashes (A). Or, if I start the game sounding from my headphones, unplugging them (and auto-switching to speakers) glitches the sound (B).

### To Reproduce
A:
1. Start the game sounding from speakers with unplugged headphones 
2. Plug your headphones in
3. Game crashes. Or else, sound starts to glitch, and when you unplug the headhones and the game crashes anyway. 

B:
1. Start the games with plugged headphones
2. Unplug them -- sound stream switches to speakers and starts to glitch
3. Plug headphones back -- game sounds ok
4. Unplug them again -- sound glitches
etc

### Expected Behavior

It should sound ok both ways

### Additional context

PC Configuration (according to HWiNFO):
HP ProBook 445 G7 on HP 8730 motherboard
AMD Zen Audio Processor / HD Audio Controller with Realtek High Definition Audio driver v. 6.0.9703.1
Windows 10 Pro 22H2 build 19045.4780
In-game audio settings are default.

**Comment by StephenCWills** [comment] 2024-10-04 17:53
Also, you shared your PC setup, but nothing about your headphones. Are these USB/Bluetooth/Aux? Can you share the make/model?

**Comment by Venyam-N** [comment] 2024-10-05 18:41
> likely a SDL issue, I tested on Android and it didn't have the issue so it's probably platform dependent.
> 
> could you test the latest win9x build (it uses a different SDL version so might not h

I don't have a real 9x setup in reach. I've tried to launch the game on my PCem VM with Windows 98, but the game said that my OS is too old to run it.



> Also, you shared your PC setup, but nothing about your headphones. Are these USB/Bluetooth/Aux? Can you share the make/model?

Sorry for that. Headphones were connected to AUX port (3.5mm jack)

**Comment by AJenbo** [comment] 2024-10-05 18:56
It should also run on newer Windows systems as well, it's just stripped of any features that require a new version of Windows.

**Comment by StephenCWills** [comment] 2024-10-05 21:46
> Sorry for that. Headphones were connected to AUX port (3.5mm jack)

I was unable to reproduce. Following the steps labeled `A`, the audio transferred to my headphones with no audio distortion or game crash. Following the steps labeled `B`, the audio transferred to my speakers with no glitches.

Windows x64
Windows 10 Home (22H2 19045.4894)
HP Spectre x360 (2017)
Realtek High Definition Audio(SST) 6.0.1.8110

```ini
[Audio]
Music Volume=-675
Sound Volume=-675
Walking Sound=1
Auto Equip Sound=0
Sample Rate=22050
Channels=2
Buffer Size=2048
Resampling Quality=3
Item Pickup Sound=1
Resampler=Speex
Device=
```

**Comment by Venyam-N** [comment] 2024-10-05 21:51
> I was unable to reproduce. Following the steps labeled `A`, the audio transferred to my headphones with no audio distortion or game crash. Following the steps labeled `B`, the audio transferred to my speakers with no glitches.

I'll try to record video tomorrow

**Comment by AJenbo** [comment] 2024-10-05 23:12
Can you try using SDL instead of Speex for the Resampler. I don't think it will really make a difference but worth trying.

Also try running it from a command prompt so that you can see the log messages, there might be something interesting here. You should probably also run it with `--verbose` so all are enabled.

**Comment by StephenCWills** [comment] 2024-10-06 15:49
At this point I've tried watching the video and reproducing the steps exactly, and also switching SDL audio drivers over to `directsound` and `winmm`. I'm still completely unable to reproduce the issue on my HP laptop. It seems to me that your Windows OS must be making changes to your audio setup when you plug in your headphones that mine is not. Perhaps you can use Sound Control Panel to observe whether any of your sound settings are changed between plugged and unplugged.

**Comment by AJenbo** [comment] 2024-10-06 18:17
I would guess that it switches between the two sound devices in his system possibly makes the other one unavailable making us write to the previous one a fault

**Comment by Venyam-N** [comment] 2024-10-06 20:01
> Can you try using SDL instead of Speex for the Resampler. I don't think it will really make a difference but worth trying.

Even with SDL It's still the same both in A and B cases ((

**Comment by AJenbo** [comment] 2024-10-06 20:06
Ok, I think we need to get the log messages to be able to progress here

**Comment by Venyam-N** [comment] 2024-10-06 21:13
> Ok, I think we need to get the log messages to be able to progress here

Done. Added logs to my web-folder: https://disk.yandex.ru/d/_SSus1T15Xmyww

**Comment by AJenbo** [comment] 2024-10-06 22:44
Here is what felt relevant from the two logs.
A:
```
INFO: Created renderer: direct3d
VERBOSE: Aulib sampleRate=22050 channels=2 frameSize=236 format=0x8120
VERBOSE: SVid audio depth=16 channels=1 rate=22050
VERBOSE: Unhandled SDL event: SDL_AUDIODEVICEADDED 0
VERBOSE: Unhandled SDL event: SDL_AUDIODEVICEADDED 0
VERBOSE: Control: device None -> KeyboardAndMouse, mode None -> KeyboardAndMouse
```
B:
```
INFO: Created renderer: direct3d
VERBOSE: Aulib sampleRate=22050 channels=2 frameSize=221 format=0x8120
VERBOSE: SVid audio depth=16 channels=1 rate=22050
VERBOSE: Unhandled SDL event: SDL_AUDIODEVICEADDED 0
VERBOSE: Unhandled SDL event: SDL_AUDIODEVICEADDED 1
VERBOSE: Unhandled SDL event: SDL_AUDIODEVICEADDED 0
VERBOSE: Unhandled SDL event: SDL_AUDIODEVICEADDED 1
VERBOSE: Control: device None -> KeyboardAndMouse, mode None -> KeyboardAndMouse
```

**Comment by StephenCWills** [comment] 2024-10-06 22:56
My logs match up with `Log A.txt`. The extra device added in `Log B.txt` probably indicates that there is a separate audio device your system uses when the headphones are plugged in (my system does not). It would be helpful if you could use the Sound Control Panel to compare the settings between those two audio devices.

**Comment by Venyam-N** [comment] 2024-10-06 23:36
I've made screenshots of my Device Manager and Audio Control Panel windows and updated my web-folder with them. Also, I've recorded a new video of case A -- with the game in winnowed mode and the device manager opened side by side: https://disk.yandex.ru/d/_SSus1T15Xmyww

P.S. I have another audio device in my setup (USB DAC Furutech ADL GT40), but it was never connected to the system when the bug occurred. I never tried to run the game with ADL GT40.

**Comment by AJenbo** [comment] 2024-10-06 23:43
We where more so hoping for a screen shot for the game audio settings where it shows the audio device when started with either headphones or speakers:

![image](https://github.com/user-attachments/assets/d588bf96-3442-42ca-93b7-30cbf5780705)

**Comment by StephenCWills** [comment] 2024-10-06 23:44
No, this is close to what I wanted. There are clearly two audio devices in the Sound Control Panel. I want to see how they differ in their settings. I'm not sure which settings will be relevant so maybe just show off the `Advanced` tab and maybe also the `Enhancements` tab.

**Comment by Venyam-N** [comment] 2024-10-06 23:54
> We where more so hoping for a screen shot for the game audio settings where it shows the audio device when started with either headphones or speakers

Added those screenshots to the folder. In both cases it's the same "system default" audio device. 

> No, this is close to what I wanted. There are clearly two audio devices in the Sound Control Panel. I want to see how they differ in their settings. I'm not sure which settings will be relevant so maybe just show off the `Advanced` tab and maybe also the `Enhancements` tab.

Those screenshots are added to.

LINK: https://disk.yandex.ru/d/_SSus1T15Xmyww

**Comment by Venyam-N** [comment] 2024-10-07 00:05
Oh... Got it! There is no tab, there's a checkbox  --"Enable audio enhancements". I've unchecked it and now everything works fine!

**Comment by Venyam-N** [comment] 2024-10-07 00:07
Oh... Got it! There is no tab, there's a checkbox --"Enable audio enhancements". I've tried to unckeck it for both devices, but the big is still occurs.

**Comment by Venyam-N** [comment] 2024-10-07 00:21
> I've tried to unckeck it for both devices, but the big is still occurs.
Oh, something changed! Now jacking my headphones in don't crash the game, but the sound still glitches.

**Comment by AJenbo** [comment] 2024-10-07 14:58
Do you have the Russian voice pack installed (and is it the one we provide)?

**Comment by Venyam-N** [comment] 2024-10-07 17:51
> Do you have the Russian voice pack installed (and is it the one we provide)?

No, I use English (MPQ files from GOG version).

**Comment by AJenbo** [comment] 2024-10-07 18:58
Odd, it's hard to see how that would have an affect on audio then

**Comment by Venyam-N** [comment] 2024-10-07 20:54
> Odd, it's hard to see how that would have an affect on audio then

I've recorded a video of case A with system language switch -- it's in the folder, as usual: https://disk.yandex.ru/d/_SSus1T15Xmyww

I think this oddity is somehow connected with my audio devices' names -- for some reason, system recorded both of them in Russian! Even if I switch system language, names stay in Russian -- you can see it comparing two screenshots: "Device Manager.png" (system language is RU) and "Headphones - Advanced tab.png" (system language is EN). Maybe, when the game addresses them, Cyrillic symbols get into into some function's parameters and cause this error?

**Comment by Venyam-N** [comment] 2024-10-07 21:16
Also, I've checked Events tab in Realtek Audio device properties and called Event Manager -- there are no events for this month at all. Screenshot uploaded.

**Comment by AJenbo** [comment] 2024-10-07 22:30
Oh wait, you are saying system as in Windows, not the game. Yeah then probably the Sound card name is the issue. This is probably something we can look at.

**Comment by AJenbo** [comment] 2024-10-07 22:31
p.s it would be easier if you could post screen shots etc directly rather then upload it to your site.

**Comment by Venyam-N** [comment] 2024-10-07 22:39
> p.s it would be easier if you could post screen shots etc directly rather then upload it to your site.

Ok, got it.

**Comment by Venyam-N** [comment] 2024-10-07 22:43
> Oh wait, you are saying system as in Windows, not the game. Yeah then probably the Sound card name is the issue. This is probably something we can look at.

But there is on more thing: audio glitches! They appear when I switch audio output device even when OS language is set to English.

**Comment by AJenbo** [comment] 2024-10-07 23:24
Yeah not sure about that part 

Yes you can post videos, but if you can't then link to the specific one and not the folder as it's hard at this point to know what files belongs too which text

**Comment by Venyam-N** [comment] 2024-10-09 12:14
Today I've tried to use another audio output device with the game -- my external USB DAC Furutech ADL GT40. When I plug it in/out and system switches to/from built-in speaker, glitches appear, but the game don't crash even with OS language set to RU. 

Also, I've tried to switch between USB DAC and headphones. When the game is started on DAC and then I plug the headphones, everything works just fine -- no glitches, correct audio output switch. When I start the game with the sound coming from my headphones and then plug in the DAC, OS don't switch the output and the sound stays in headphones.  

So, I suppose that my speakers are troublemakers, not the headphones.

**Comment by AJenbo** [comment] 2024-10-09 12:18
We have moved the issue upstream: https://github.com/libsdl-org/SDL/issues/11122

**Closed by AJenbo** 2024-10-09 12:18 UTC
Labels: Insufficient information

**Comment by Venyam-N** [comment] 2024-10-09 12:23
> We have moved the issue upstream: [libsdl-org/SDL#11122](https://github.com/libsdl-org/SDL/issues/11122)

But there is a link leading to this tread -- hope, they'll see my little update. I'm not feeling comfortable to post comments there because I can’t deal with such a complex tech info, like @StephenCWills provided.

**Comment by StephenCWills** [comment] 2024-10-09 12:24
> So, I suppose that my speakers are troublemakers, not the headphones.

FYI, this makes sense based on what I found. :+1:

I have three audio devices, and they all use a frame size of 221 according to logs so that seems to be the more common case. Your speakers have a less common frame size of 236 so the issue is highly likely to occur when switching between your speakers and another audio device.

**Comment by AJenbo** [comment] 2024-11-01 23:43
@Venyam-N if you update the sdl2.dll to the latest version it should fix the crash: https://github.com/libsdl-org/SDL/releases/tag/release-2.30.9 if you still have issues afterwards then feel free to open a new issue.

**Comment by Venyam-N** [comment] 2024-11-02 12:55
Updated. The game's behavior when plugging/unplugging headphones changed a little bit: the sound don't glitch anymore, but switching audio output device still crashes the game(( I'll describe how it works with new SDL in a couple of hours.
