### ISSUE TITLE
crashing when entering church

### ISSUE THREAD

**Issue by nsklaus** [diasurgical/devilutionX#54] opened 2019-03-23 11:07 UTC
compiled the game, 
got diabdat.mpg from gog release (using wine to install then copy over in devilutionX/build/).
stated the game, created a new warrior, talked to cain an the innkeeper, then i went toward the church, i saw the victim on the floor, talked to him, all was fine so far, i tried to enter the church aand.. crash. please see attached crashlog.txt

my environment is ubuntu 18.10, kernel 5.0.1 

[crashlog.txt](https://github.com/diasurgical/devilutionX/files/2999244/crashlog.txt)

**Comment by AJenbo** [comment] 2019-03-23 13:26
You most likely compiled a 64bit version of the game, there is still a lot that needs to be cleaned up before the render will fully work under 64bit. See the readme for how to compile a 32bit version and also see #20 for how to run 32bit SDL applications on Ubuntu.

https://github.com/diasurgical/devilutionX#building-deviltuionx-32-bit-on-64-bit-linux-multilib-platforms

**Comment by AJenbo** [comment] 2019-03-23 13:57
Closing this as it is a duplicate of #53

**Closed by AJenbo** 2019-03-23 13:57 UTC
