### ISSUE TITLE
big bug bag

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#445] opened 2019-11-11 15:52 UTC
Description:
I have not tested the game for a long time.
Now I've finally tested it again and discovered enormous stability problems.

Three bugs have caught my eye.
There are two minor bugs and one huge enormous bug.

I tested commit 813b68bffb020d97117f8f49c85050ff61434722 I encoutered them first time.
Then I tested commit f4496aa7f9077ea50e37b980c5954a742839373b and experienced them again.

First minor bug:
<s>When clicking on shrines the displayed message is shown for extremely short time.</s>

Second minor bug:
When you enter the circle when entering the Lazarus quest the sound is being played too short time.

Huge bug:
This one I experienced in two times.
First time after entering the Lazarus quest the keyboard didn't respond at all.
The mouse input was extremely laggy.
The color of the hud has changed like in the picture below.
The color of the mana potions has changed into the color of the healing potions.
So I could not save the character. But maybe the colors were wrong when the caracter already died.

[single_0.sv.zip](https://github.com/diasurgical/devilutionX/files/3836919/single_0.sv.zip)
[single_0.sv.2.zip](https://github.com/diasurgical/devilutionX/files/3836918/single_0.sv.2.zip)

**Comment by Chance4us** [comment] 2019-11-11 15:53
First bug picture.
![shrine](https://user-images.githubusercontent.com/45902449/68600994-c0db4f80-04a3-11ea-99f2-79fba4f3dbac.png)

**Comment by Chance4us** [comment] 2019-11-11 15:55
Second bug picture.
![circle](https://user-images.githubusercontent.com/45902449/68601153-1283da00-04a4-11ea-9b95-775098777ea1.png)

**Comment by Chance4us** [comment] 2019-11-11 15:56
Third bug picture.
![dead](https://user-images.githubusercontent.com/45902449/68601216-2fb8a880-04a4-11ea-98ff-d8c431abf50d.png)

**Comment by Chance4us** [comment] 2019-11-11 15:57
I notice the colors have changed before death.

**Comment by Chance4us** [comment] 2019-11-11 15:57
The second time I experienced it the colors didn't change.

**Comment by Chance4us** [comment] 2019-11-11 15:58
Two savegames.

**Comment by Chance4us** [comment] 2019-11-11 15:58
[single_0.sv.zip](https://github.com/diasurgical/devilutionX/files/3832097/single_0.sv.zip)

**Comment by Chance4us** [comment] 2019-11-11 15:58
Above is the second and below the first.

**Comment by qndel** [comment] 2019-11-11 15:59
Don't spam pls, all of this could be in a single comment

**Comment by Chance4us** [comment] 2019-11-11 15:59
[single_0.sv(2).zip](https://github.com/diasurgical/devilutionX/files/3832103/single_0.sv.2.zip)

**Comment by Chance4us** [comment] 2019-11-11 15:59
Git log:

**Comment by Chance4us** [comment] 2019-11-11 15:59
[gitlog.txt](https://github.com/diasurgical/devilutionX/files/3832106/gitlog.txt)

**Comment by Chance4us** [comment] 2019-11-11 16:00
@qndel I' sorry. Too late I fear.

**Comment by AJenbo** [comment] 2019-11-11 16:11
Why are you posting the git log? It just lists the commits that are here in GitHub. Did you intend to post the application log?

**Comment by AJenbo** [comment] 2019-11-11 16:12
> Above is the second and below the first.

Put the message in the same comment as the attachment, I can't see what this relates.

**Comment by AJenbo** [comment] 2019-11-11 16:14
Please report one bug per issue having multiple bugs in one issue makes it hard to track, and figure out what belongs to which issue.

**Comment by Chance4us** [comment] 2019-11-11 16:32
Ok Ok. Linux 5.3.0-1-amd64 #1 SMP Debian 5.3.7-1 (2019-10-19) x86_64 GNU/Linux.
DevilutionX is compiled 64 bit executable from master.

**Comment by Chance4us** [comment] 2019-11-12 14:56
I bisected a little bit and got the following result:

a2e821d2413d6ed2bb254b8798e6fd3b5d95aed1 is the first bad commit
commit a2e821d2413d6ed2bb254b8798e6fd3b5d95aed1
Author: Gleb Mazovetskiy <glex.spb@gmail.com>
Date:   Sat Oct 26 14:32:29 2019 +0100

    Game controller support
    
    Initial game controller support.
    
    Actions are based on the Switch branch but the controller code itself is
    implemented differently, allowing for easy remapping and minimizing
    changes to the Source/ directory.
    
    Many subtle and not so subtle controller bugs have been fixed
    in this implementation, including:
    
    1. Smoother & more responsive movement with the joysticks.
    2. Consistent controls for all the menus in the game (stores, quest log,
    etc).
    3. Cursor appearance / disappearance at appropriate times.
    
    Low-level controls are abstracted and 3 SDL interfaces are supported:
    game controller, joystick, and keyboard. See SourceX/controls/ for more
    details on this.
    
    Wishlist for the future:
    
    1. Primary button and use button should attack continously.
       This is hard as it requires checking the cooldowns / attack speed.
    2. Quick spell menu navigation is very buggy. It is also buggy in the
       switch branch. I haven't had a change to investigate.

:100644 100644 edce03ce6327f1df9875072f64f18412598332d8 3aa0258aa87e6ebe70a3cd0bca9567e72bfa8f69 M	CMakeLists.txt
:040000 040000 6fb3fc08168bf2a06e6c3baa9ee5873ddec2464d 814b09a0f2f7da99aa994bd22c078529db178529 M	Source
:040000 040000 51212fe30c77d81e747f99a09b386b7f1169e864 847cca2cc6bb8a41ecc2c4f8c9b17bee4eb53593 M	SourceS
:040000 040000 1bd46c2626a636f554eabf9b66dbf636e0fb3d23 401ca10c3e26bf7583995ae22adf8eded2467e1b M	SourceX

/****************************************************************************************************/

While compiling the broken version I got the following message:
/home/user/Schreibtisch/devilutionX/SourceX/miniwin/misc_msg.cpp: In function ‘dvl::SHORT dvl::GetAsyncKeyState(int)’:
/home/user/Schreibtisch/devilutionX/SourceX/miniwin/misc_msg.cpp:555:23: error: ‘SDLC_GetKeyboardState’ was not declared in this scope; did you mean ‘SDL_GetKeyboardState’?
  555 |  const Uint8 *state = SDLC_GetKeyboardState();
      |                       ^~~~~~~~~~~~~~~~~~~~~
      |                       SDL_GetKeyboardState
make[2]: *** [CMakeFiles/devilutionx.dir/build.make:219: CMakeFiles/devilutionx.dir/SourceX/miniwin/misc_msg.cpp.o] Fehler 1
make[2]: *** Es wird auf noch nicht beendete Prozesse gewartet....
/home/user/Schreibtisch/devilutionX/SourceX/DiabloUI/dialogs.cpp:77:8: warning: ‘dvl::{anonymous}::SPAWNERR_DIALOG’ defined but not used [-Wunused-variable]
   77 | UiItem SPAWNERR_DIALOG[] = {
      |        ^~~~~~~~~~~~~~~
/home/user/Schreibtisch/devilutionX/SourceX/DiabloUI/dialogs.cpp:72:8: warning: ‘dvl::{anonymous}::SELOK_DIALOG’ defined but not used [-Wunused-variable]
   72 | UiItem SELOK_DIALOG[] = {
      |        ^~~~~~~~~~~~
/home/user/Schreibtisch/devilutionX/SourceX/DiabloUI/dialogs.cpp:62:8: warning: ‘dvl::{anonymous}::PROGRESS_DIALOG’ defined but not used [-Wunused-variable]
   62 | UiItem PROGRESS_DIALOG[] = {
      |        ^~~~~~~~~~~~~~~
make[1]: *** [CMakeFiles/Makefile2:77: CMakeFiles/devilutionx.dir/all] Fehler 2
make: *** [Makefile:84: all] Fehler 2
/**************************************************************************************/

There seem to be some typos like SDLC_GetKeyboardState instead SDL_GetKeyboardState or
generally SDLC instead of SDL.

**Comment by AJenbo** [comment] 2019-11-12 15:08
Sounds odd considering that all the issues you described relates to audio or graphics and that commit is about input. But also which of the 3 issues are you saying is caused but this commit?

**Comment by Chance4us** [comment] 2019-11-12 15:14
If you were to read thoroughly again, you would find that I already wrote that the keyboard did not react at all and the mouse input was laggy.

**Comment by AJenbo** [comment] 2019-11-12 15:31
> If you were to read thoroughly again, you would find that I already wrote that the keyboard did not react at all and the mouse input was laggy.

You really do not need to bring attitude to this. I did read it but as I have said you need to split it up. in to several issues. Tracking multiple bug in a single issue is not a good way to handle ting. I can't tell if you where saying that a2e821d2413d6ed2bb254b8798e6fd3b5d95aed1 changed the color of your mana potions or caused the keyboard to stop respond.

**Comment by AJenbo** [comment] 2019-11-12 15:38
> There seem to be some typos like SDLC_GetKeyboardState instead SDL_GetKeyboardState or
> generally SDLC instead of SDL.

SDLC is our SDL1/2 **c**ompatability layer. There is probably a missing header reference, but that is fixed now. If you cannot compile it then you cannot verify that it is the one causing the issue. Use `bisect skip` when you encounter a commit that doesn't compile.

**Comment by AJenbo** [comment] 2019-11-12 16:06
@Chance4us could you run the game with `-f` and tell us what frame rate it is running at?

Do you have a game controller or similar device attached to your computer?

**Comment by Chance4us** [comment] 2019-11-12 16:41
Maybe we should split the bug report if nothing important is to be done.
First, I'll bisect using "bisect skip". Maybe another commit will appear as bad.
At the moment there is no game controller connected but the issue with input tough.

Following usb devices are listed:
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 003: ID 8087:0025 Intel Corp. 
Bus 003 Device 002: ID 1462:7b85 Micro Star International 
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 004: ID 1532:006b Razer USA, Ltd 
Bus 001 Device 003: ID 045e:07f8 Microsoft Corp. Wired Keyboard 600 (model 1576)
Bus 001 Device 002: ID 0bda:0151 Realtek Semiconductor Corp. Mass Storage Device (Multicard Reader)
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

Content of ini file:
[devilutionx] 
upscale=0
fullscreen=1
grab input=1
scaling quality=1
[Diablo] 
Intro=0
Gamma Correction=100
Color Cycling=1
Sound Volume=0
Music Volume=0

The latest stable version without input issue runs at 99 fps.
When I just minimized / maximized window, the hud has turned blue and I could paint over with the mouse pointer to redraw it. I'm going to attach a couple of pictures including the version number.
![fps](https://user-images.githubusercontent.com/45902449/68691164-91941380-0573-11ea-8a42-2631951eb717.png)
![blue](https://user-images.githubusercontent.com/45902449/68691173-9658c780-0573-11ea-8a39-9d10cec9ed3c.png)
![version](https://user-images.githubusercontent.com/45902449/68691177-9bb61200-0573-11ea-8ea7-c430707732a9.png)

The bisecting I will do later today.

**Comment by AJenbo** [comment] 2019-11-12 17:04
> Maybe we should split the bug report if nothing important is to be done.

It should be split up period. Not sure what you mean by "if nothing important is to be done", it makes it sound like you feel we are not take it seriously.

> upscale=0

Ok this might explain some of the issues, most people will be running with it enabled and the code path is a bit different.

> The latest stable version without input issue runs at 99 fps.

Looks like we do not get vertical sync when upscaling is disabled, 99 is the highest the counter goes so you are probably running at something way higher than that. I'll uncap it, it looks like my system runs at about 250fps in windowed mode with `upscale=0`.

> When I just minimized / maximized window, the hud has turned blue and I could paint over with the mouse pointer to redraw it. I'm going to attach a couple of pictures including the version number.

We probably have to redraw the panel when the window regains focus as the original did, this isn't an issue when upscaling is enabled. The blue color appears to be specific to your graphics system, but would probably be solved by the same change.

**Comment by Chance4us** [comment] 2019-11-12 18:02
I do not believe why you think that I think you are not serious.
You and your friends have contributed so much to the project, why should I mean something bad?
I mean without any assessment that we could divide the bug report for more clarity, if time permits.
Let us please end nonsensical disputes and discussions for more effectiveness.

**Comment by AJenbo** [comment] 2019-11-12 18:09
It would be best to split them up as a. they are not related and b. they might not be easy to solve

**Comment by AJenbo** [comment] 2019-11-12 18:21
> When clicking on shrines the displayed message is shown for extremely short time.

Fixed here https://github.com/diasurgical/devilutionX/commit/def6ee472b6dc1a02dd04beca962aea4ce04e52b

**Comment by Chance4us** [comment] 2019-11-12 18:59
Nice.

**Comment by Chance4us** [comment] 2019-11-12 19:00
I bisected a little bit again by using "skip" with following result.

[d830969898ccb1cc750d4d1e4c9669659a49e2be] Compiling instructions for OpenBSD
user@3600:~/Schreibtisch/devilutionX$ git bisect good
binäre Suche: danach noch 11 Commits zum Testen übrig (ungefähr 4 Schritte)
[882e9f0fbfd3dd2a9fce3dd1ec6d713ab4d19ad7] Game controller: Fix spell selection
user@3600:~/Schreibtisch/devilutionX$ git bisect bad
binäre Suche: danach noch 5 Commits zum Testen übrig (ungefähr 3 Schritte)
[3e03404ebbf5d72b7392933605a7748622425ca0] Keyboard and Controller support for Diablo 1
user@3600:~/Schreibtisch/devilutionX$ git bisect good
binäre Suche: danach noch 2 Commits zum Testen übrig (ungefähr 2 Schritte)
[93203fa445f670d9aa674acac4d9cb473c0d39fc] Controller: implement spellcasting
user@3600:~/Schreibtisch/devilutionX$ git bisect skip
binäre Suche: danach noch 2 Commits zum Testen übrig (ungefähr 2 Schritte)
[a2e821d2413d6ed2bb254b8798e6fd3b5d95aed1] Game controller support
user@3600:~/Schreibtisch/devilutionX$ git bisect skip
binäre Suche: danach noch 2 Commits zum Testen übrig (ungefähr 2 Schritte)
[6f3cc2a4400aedf4c614b01baf018b2cb7c6901b] SDL1 fixes
user@3600:~/Schreibtisch/devilutionX$ git bisect bad
binäre Suche: danach noch 1 Commit zum Testen übrig (ungefähr 1 Schritt)
[a1d7fe196a3ab32e40c547c71754538a766f1dda] Fix increasing player stats infinitely
user@3600:~/Schreibtisch/devilutionX$ git bisect good
There are only 'skip'ped commits left to test.
The first bad commit could be any of:
93203fa445f670d9aa674acac4d9cb473c0d39fc
a2e821d2413d6ed2bb254b8798e6fd3b5d95aed1
6f3cc2a4400aedf4c614b01baf018b2cb7c6901b
Keine binäre Suche mehr möglich!
![commits](https://user-images.githubusercontent.com/45902449/68701466-1d636b00-0587-11ea-9580-b29251cc8a03.png)

**Comment by Chance4us** [comment] 2019-11-12 19:03
To reproduce the input issue you could try to load attached save game above and to kill Lazarus.

**Comment by AJenbo** [comment] 2019-11-12 19:30
Check if this fixes you miss colored panel: https://github.com/diasurgical/devilutionX/commit/c5bca03e5a9f609382b193ada91e2790b449a30c

**Comment by Chance4us** [comment] 2019-11-12 19:48
c5bca03 not fixed it.
![redraw](https://user-images.githubusercontent.com/45902449/68705133-cca34080-058d-11ea-9447-02a6196a0c34.png)

**Comment by Chance4us** [comment] 2019-11-12 19:56
I just notice the panel is slightly shifted to the right as well.

**Comment by AJenbo** [comment] 2019-11-12 20:03
**please** split up the issue.

I cannot reproduce the issue, once you have split up the issues please provide a detailed step by step way to reproduce them.

![Uploading Screenshot from 2019-11-12 21-01-47.png…]()

**Comment by Chance4us** [comment] 2019-11-12 20:19
Splitted first -> Input issue when entering Lazarus quest #457

**Comment by Chance4us** [comment] 2019-11-12 20:33
Splitted second -> Panel redraw and position issue when minimizing window #458

**Comment by Chance4us** [comment] 2019-11-12 20:47
Splitted third -> Sound effect too short when entering the circle #459
The fourth issue is already solved by def6ee4.

**Closed** 2019-11-12 20:47 UTC
Labels: savegame attached

**Comment by AJenbo** [comment] 2019-11-12 21:04
Thanks, nice work it's much clear now.
