### ISSUE TITLE
dull staff with +65531% chance to hit

### ISSUE THREAD

**Issue by Tmkrth** [diasurgical/devilutionX#2916] opened 2021-09-21 20:24 UTC
Hello, we found a dull staff of firewall with a +65531% chance to hit in DevilutionX 1.2.1

![screen23](https://user-images.githubusercontent.com/1104628/134242086-272ba294-9a04-45d1-8528-0e2484eac778.jpg)
![screen25](https://user-images.githubusercontent.com/1104628/134242092-c2c1665a-f94d-490d-8b9a-704acda6b843.jpg)

If this is already a known issue, please ignore.

**Comment by StephenCWills** [comment] 2021-09-21 20:26
Duplicate of #2842

**Closed by StephenCWills** 2021-09-21 20:26 UTC
