### ISSUE TITLE
Unable to obtain quest gear after creating more than 1 character

### ISSUE THREAD

**Issue by localappdata** [diasurgical/devilutionX#6398] opened 2023-07-21 23:10 UTC
### Operating System

Windows x64

### DevilutionX version

1.5.0 (latest release)

### Describe

Unique quest gear doesn't drop anymore after the second character created, random blue (magic) gear drops instead even if the quest gear was never obtained by any character. This only seems to apply to equippable uniques; all other quest items drop as intended.

### To Reproduce

1. Create a character with an existing one already in the list.
2. Complete any plotline quest at Normal difficulty for the sake of speed.
3. Check the journal as some quests won't be marked as finished either if they require collecting the gear.

### Expected Behavior

Getting the original Diablo+Hellfire quest rewards, both for plotline quests and secret quests.

### Additional context

The bug was tested on Hell difficulty with vanilla Diablo classes and then reproduced with the Hellfire Monk class and with the Bard and Barbarian classes. It was tested on both plotline and secret quests.

Exporting the HSV to Hellfire 1.01 produces the normal result and can then be imported back to DevilutionX but remembering to save right before reaching the end of a quest can be a bit of a stretch.

**Comment by julealgon** [comment] 2023-07-21 23:37
Does the problem persist if you quit the game and open it again in-between games?

**Comment by StephenCWills** [comment] 2023-07-21 23:44
> Complete any plotline quest at Normal difficulty for the sake of speed.

> The bug was tested on Hell difficulty...

What you describe is the expected behavior for Hell difficulty, but not for Normal difficulty. Did you test on Normal difficulty?

**Comment by StephenCWills** [comment] 2023-07-22 00:49
> Thanks for reminding me of this! I did test it on both just in case. I wonder if Hell difficulty carried over somehow, one thing I didn't try is wiping all my HSV files and config (after making a backup) and restarting from a clean state to see if that fixes it, I'll make sure to try this as that would help pinpoint what happened.

Well, I am completely unable to reproduce the issue using the Arkaine's Valor quest. Every Hell difficulty game gives me a magic item and every Normal difficulty game gives me Arkaine's Valor. It doesn't matter what character slot I use, how many times I've found it on how many different characters, the behavior is 100% consistent. I'm going to close this for now.

If you can provide a more accurate and detailed description of how to reproduce the issue, we can reopen the issue.

**Closed by StephenCWills** 2023-07-22 00:49 UTC
Labels: Insufficient information
