### ISSUE TITLE
[Feature Request]: Add, river and birds sprites, from PS1 version.

### ISSUE THREAD

**Issue by SODIX** [diasurgical/devilutionX#7203] opened 2024-07-23 09:12 UTC
### Feature Type

Quality of Life

### Describe

In PS1 version there is river ripple, reflection and birds sprites in Tristram. PLS port it to PC.

**Comment by qndel** [comment] 2024-07-23 10:41
Duplicate of https://github.com/diasurgical/devilutionX/issues/3545

**Closed by qndel** 2024-07-23 10:41 UTC
Labels: enhancement
