### ISSUE TITLE
Applying oil of accuracy does not update char sheet before re-equipping the item

### ISSUE THREAD

**Issue by AJenbo** [diasurgical/devilutionX#2506] opened 2021-08-05 17:25 UTC
- find oil of accuracy
- open char
- apply to an equipped item
- notice numbers did not update
- re-equip item
- see change

This is probably a vanilla issue

**Comment by ThomasChr** [comment] 2021-08-06 14:49
I'll would like to try it.
I think it's allowed to Modify RndItem() to just give me the oil of accuracy?

**Comment by ThomasChr** [comment] 2021-08-06 14:56
Can't reproduce. Barb, Level 1, just the starting sword. I opened char stats and inventory and applied the oil. Chance to hit changed from a white 60% to a blue 62% immediatly.
I also tried with a club. Also did work.

**Comment by qndel** [comment] 2021-08-06 14:59
> Can't reproduce. Warrior, Level 1, just the starting sword. I opened char stats and inventory and applied the oil to the equiped sword. Chance to hit changed from a white 60% to a blue 62% immediately.
> I also tried with a club. Also did work.
> Also tried with a completely new character. Did still work, the numbers updated immediately.

can you upload save? ;)

**Comment by ThomasChr** [comment] 2021-08-06 15:08
Of course, I could do that. What savefile do you want? After I have a few oils in the inventory, or after I applied one?

**Comment by qndel** [comment] 2021-08-06 15:16
With oils ofc

**Comment by ThomasChr** [comment] 2021-08-06 15:17
Enough oils, before applying any...
[single_2.zip](https://github.com/diasurgical/devilutionX/files/6946383/single_2.zip)

**Comment by AJenbo** [comment] 2021-08-06 17:42
Ok, maybe we where wrong, I will have to check the details with my brother tomorrow :D

**Comment by julealgon** [comment] 2021-08-06 20:36
Wasn't this fixed by one of @qndel 's changes recently? I remember there was something which required you to unequip/re-equip to update the character info and that was fixed.

**Comment by AJenbo** [comment] 2021-08-06 20:37
It's possible, we where playing 1.2.1 so there are some fixes that are already done that we did not have.

**Comment by qndel** [comment] 2021-08-07 09:35
> Wasn't this fixed by one of @qndel 's changes recently? I remember there was something which required you to unequip/re-equip to update the character info and that was fixed.

nope, my change was only for updating damage on leveling up

**Comment by qndel** [comment] 2021-10-01 15:01
Works fine for me.

**Closed by qndel** 2021-10-01 15:01 UTC
Labels: bug, good first issue, invalid
