### ISSUE TITLE
Diablo in normal is harder than diablo in fast mode.  

### ISSUE THREAD

**Issue by Fartbringer** [diasurgical/devilutionX#6943] opened 2024-02-06 06:53 UTC
### Operating System

Windows x64

### DevilutionX version

1.5.1

### Describe

I find him in normal is harder than in fastest. Seems our movement and strikes are slowed greatly in normal. Can someone verify. Couldnt beat him in normal. 

### To Reproduce

Go to diablo in normal and fight him. Your movements and strikes are slower. 
Go to diablo in fast and fight him. Your strikes are faster and seem to strike him more often.

### Expected Behavior

Make normal Diablo easier to kill if my theory is correct.

### Additional context

None

**Comment by AJenbo** [comment] 2024-02-06 07:45
We run continuous tests where the gameplay is tested at higher speeds then it was recorded so this is likely just an illusion and not an actual issue.

To confirm it you can record a demo and play it back at a higher speed, that way you can confirm it if the replay goes out of sync. Since you have not confirmed this I will close the issue, but we can open it again if you can confirm that it actually is an issue.

Also please update to 1.5.2

**Closed by AJenbo** 2024-02-06 07:45 UTC
