### ISSUE TITLE
Holy Shrine teleports out of bounds with Phasing or crashes the game

### ISSUE THREAD

**Issue by serpinio** [diasurgical/devilutionX#1566] opened 2021-04-17 04:37 UTC
**Important information**
Using latest DevilutionX 1.2.1 on Switch and PC with Diablo and Hellfire MPQs.

**Description**
Discovered a Holy Shrine - "Wherever you go, there you are", that casts Phasing. If used, depending on the client platform it either crashes the game (Switch, firmware 10.2.0) or teleports the character out of bounds (PC, Win7/10).

**To Reproduce**
1. Load save
2. Use nearby shrine

**Expected behavior**
Phasing should only happen within the bounds of the level.

**Screenshots**
PC version screens (before, after) and the save file attached.

![before](https://user-images.githubusercontent.com/82693390/115101742-60312b80-9f4f-11eb-85cc-b3d09eae9dc8.jpg)
![after](https://user-images.githubusercontent.com/82693390/115101744-62938580-9f4f-11eb-89e8-ff2e067700c8.jpg)

[single_0_holy_shrine_out_of_bounds.zip](https://github.com/diasurgical/devilutionX/files/6328624/single_0_holy_shrine_out_of_bounds.zip)

**Comment by FitzRoyX** [comment] 2021-04-17 06:10
Shoulda been called Wandering Shrine smh

**Comment by qndel** [comment] 2021-04-17 11:27
![image](https://user-images.githubusercontent.com/14297035/115111433-a2269580-9f80-11eb-8670-3b7a308edc04.png)
That's the save you sent, are you sure you sent the correct one?

**Comment by qndel** [comment] 2021-04-17 11:38
```cpp
void AddRndTeleport(int mi, int sx, int sy, int dx, int dy, int midir, char mienemy, int id, int dam)
{
	int pn, r1, r2, nTries;

	nTries = 0;
	do {
		nTries++;
		if (nTries > 500) {
			r1 = 0;
			r2 = 0;
			break; //BUGFIX: warps player to 0/0 in hellfire, change to return or use 1.09's version of the code
		}
		```
		this is the cause ;)

**Comment by serpinio** [comment] 2021-04-17 11:47
> 
> 
> ![image](https://user-images.githubusercontent.com/14297035/115111433-a2269580-9f80-11eb-8670-3b7a308edc04.png)
> That's the save you sent, are you sure you sent the correct one?

That's certainly _not_ what I sent. Re-sending it again just in case.

[single_0_shrine_crash.zip](https://github.com/diasurgical/devilutionX/files/6329156/single_0_shrine_crash.zip)

Are you sure you're loading the game with both Diablo and several Hellfire MPQs present in the directory? Here's proof that it's the one: https://user-images.githubusercontent.com/82693390/115111965-cfc50c00-9f8b-11eb-8c35-0c0e8b4df29e.mp4

**Comment by qndel** [comment] 2021-04-17 11:54
well, there was a .sv and .hsv in the zip you sent ;) .sv was on the screenshot, .hsv contained the proper save, send only the save with the bug in the future 🤪

**Comment by serpinio** [comment] 2021-04-17 12:15
> well, there was a .sv and .hsv in the zip you sent ;) .sv was on the screenshot, .hsv contained the proper save, send only the save with the bug in the future zany_face
> 
> > Great find, thanks! Hope it makes into the Master.
> 
> No need to hope, it's going into master, there aren't many more obvious bugs than teleporting to 0/0 coords laughing

Oh, now I see! .SV is a vanilla save and .HSV is a _Hellfire save_. I never knew that! Wonder why it still writes SV's at all since I never started the game without Hellfire MPQs in the first place, and SV seems to still be kept updated at the same time as the HSV is written...

**Comment by qndel** [comment] 2021-04-17 12:16
That's weird ...

**Comment by FitzRoyX** [comment] 2021-04-17 13:47
Should this be marked vanilla bug? Or is it a bug introduced by hellfire?

**Comment by qndel** [comment] 2021-04-17 13:48
vanilla hellfire

**Comment by FitzRoyX** [comment] 2021-04-17 13:49
Why did hellfire change phasing?

**Comment by qndel** [comment] 2021-04-17 13:55
Ask hellfire devs

**Comment by FitzRoyX** [comment] 2021-04-17 14:04
Sorry for one extra question, but where is the "gbIsHellfire" boolean to alternate behaviors?

**Comment by AJenbo** [comment] 2021-04-17 21:38
> Sorry for one extra question, but where is the "gbIsHellfire" boolean to alternate behaviors?

There isn't alternate behavior but various bug fixes that have all been applied.

**Comment by AJenbo** [comment] 2021-05-31 05:17
The proper fix for this would likely be something like generating a list of all possible locations and then picking on at random, instead of the current one where it fires off a series of random attempts that may or may not fail.

**Comment by AJenbo** [comment] 2021-08-29 05:11
this should now be fixed

**Closed by AJenbo** 2021-08-29 05:11 UTC
Labels: bug, help wanted, good first issue, savegame attached, vanilla
