### ISSUE TITLE
some gossips got mixed up

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#6132] opened 2023-05-21 22:23 UTC
If you click on the npcs and want to gossip, the conversations of other npcs are often played back. For example. Ogden speaks as Cain, Cain speaks as Farnham. Not all npcs and no causing commit tested.

**Comment by StephenCWills** [comment] 2023-05-21 23:01
Unable to reproduce so far. Can we get even a little more info, like whether the build you were running was before or after #6080 was merged?

**Comment by Chance4us** [comment] 2023-05-22 07:55
> Unable to reproduce so far. Can we get even a little more info, like whether the build you were running was before or after https://github.com/diasurgical/devilutionX/pull/6080 was merged?

Yes, caused by commit b7b9996.
To reproduce:
1. load following game
[single_1.hsv.zip](https://github.com/diasurgical/devilutionX/files/11528445/single_1.hsv.zip)

2. Click on Cain, talk to cain, gossip and see the following impact.
![Bildschirmfoto vom 2023-05-22 09-51-07](https://github.com/diasurgical/devilutionX/assets/45902449/3a79c8cd-aab1-4b98-a6b8-46d209623784)

3. The speech should be the following.
![Bildschirmfoto vom 2023-05-22 09-45-47](https://github.com/diasurgical/devilutionX/assets/45902449/c4649ae2-46f8-493f-be5f-181f07cde322)

**Comment by ephphatha** [comment] 2023-05-22 12:01
Fixed in #6136 but I didn't use the right keyword to auto-link it 😂

**Closed by ephphatha** 2023-05-22 12:01 UTC
