### ISSUE TITLE
AI upscale textures

### ISSUE THREAD

**Issue by dcworldwide** [diasurgical/devilutionX#491] opened 2019-11-23 09:26 UTC
[Re-word/close as appropriate]

Is it possible to use AI to upscale the game's textures? I assume it's been discussed already, is it within scope of DevilutionX? 

https://www.youtube.com/watch?v=FsoyC9j9MV0
https://www.youtube.com/watch?v=zpwG2uNWhiQ
https://github.com/xinntao/ESRGAN

**Comment by AJenbo** [comment] 2019-11-23 11:39
Duplicate of https://github.com/diasurgical/devilutionX/issues/3

**Closed by AJenbo** 2019-11-23 11:39 UTC
