### ISSUE TITLE
[Feature Request]: "Co-op" Health Indicators

### ISSUE THREAD

**Issue by Chonkblonk** [diasurgical/devilutionX#6917] opened 2024-01-29 19:59 UTC
### Feature Type

Quality of Life

### Describe

An optional toggle which puts health indicators for other players somewhere on screen, either as complete HP values or maybe just an incremented bar for percentage.
It would be helpful for helping you know for sure when to rush to someone's aid to heal them, when it's not really possible to mouse over them to see their health (because there's monsters or items in the way).

**Comment by StephenCWills** [comment] 2024-01-30 00:14
Duplicate of #6541

**Closed by StephenCWills** 2024-01-30 00:14 UTC
Labels: enhancement
