### ISSUE TITLE
Lazarus staff skip

### ISSUE THREAD

**Issue by beelzebielsk** [diasurgical/devilutionX#6369] opened 2023-07-15 16:08 UTC
### Operating System

PlayStation Vita

### DevilutionX version

1.5.0 (latest release)

### Describe

I can skip getting the staff of Lazarus by walking to where the portal will be after I give the staff to Cain. If I walk through that tile or press circle while on that tile, I go straight to where Lazarus is.

### To Reproduce

1. Go to level 15
2. Find the pentagram
3. Walk on to the tile where the portal would be after you give the staff of Lazarus to Cain. You should be transported to lazarus's lair. Once or twice that has not worked for me, what worked is pressing circle near the tile.

I've done this on like 4 or 5 different saves, so I don't think the save or the seed number matters.

### Expected Behavior

I expect to not be able to pass through the portal until I give the staff of Lazarus to Cain.

**Comment by StephenCWills** [comment] 2023-07-15 16:10
Duplicate of #6217

This issue is already resolved.

**Closed by StephenCWills** 2023-07-15 16:10 UTC

**Comment by beelzebielsk** [comment] 2023-07-15 16:12
Oh, okay. Strange, I didn't see it when I looked through the existing issues.
