### ISSUE TITLE
[Issue Report]: Golem with negative HP not targeted by monsters

### ISSUE THREAD

**Issue by kphoenix137** [diasurgical/devilutionX#6664] opened 2023-09-28 03:03 UTC
### Operating System

Windows x64

### DevilutionX version

1.5.1

### Describe

Summoning a Golem with negative life causes monsters to ignore the Golem entirely.

I would imagine this is a vanilla bug.

`golem.maxHitPoints = 2 * (320 * missile._mispllvl + player._pMaxMana / 3);`

This is the formula for Golem HP. In this scenario, `missile._misplvl` is `0` and `player._pMaxMana` is `-12`. Therefore the Golem HP resolves to `-8` (Golem HP is signed)

https://github.com/diasurgical/devilutionX/assets/68359262/78883883-07fd-4f91-9968-80852f798f70

### To Reproduce

1. Get negative maximum current mana (Easiest by using a fresh Barbarian and equipping an item with -Mana, such as Cranium Basher)
2. Obtain a method for casting slvl 0 Golem (Staff or Scroll. Rod of Onan is easiest as there is no magic requirement)
3. Cast golem spell and observe the combat

**Comment by StephenCWills** [comment] 2023-09-28 04:17
Duplicate of #1521

**Closed** 2023-09-28 04:36 UTC
