### ISSUE TITLE
[PS TV] Impossible to properly name character.

### ISSUE THREAD

**Issue by Kiiro-Yakumo** [diasurgical/devilutionX#5356] opened 2022-09-17 23:50 UTC
### Operating System

PlayStation Vita

### DevilutionX version

1.4.1 (latest release)

### Describe

When trying to name character on PS TV the system keyboard appears to type in the name. To this point it's ok but now is the tricky point. Square button removes letters, that's good, but the Cross button enters letter and also exits from the menu even tough the keyboard is still there. Same goes for Circle button which confirms the menu even tough the keyboard is still there.

Workaround to this is to make a character on other working system and then copy it to PS TV but it's a bit of a hassle.

### To Reproduce

1. Turn on the game on the PS TV like usual.
2. Single Player.
3. New Hero (if applicable)
4. Select the Hero
5. Attempt to name character

### Expected Behavior

Possibility to enter the name and start the game with it.

### Additional context

On PS Vita the buttons don't double actions, even without touch input it is possible to properly name character.

**Comment by tsunamistate** [comment] 2022-09-18 15:10
@isage looks like this is in your ballpark, could you please test?

**Comment by isage** [comment] 2022-09-18 15:49
Will do. I don't have pstv, but i can "emulate" it on vita and test

**Comment by isage** [comment] 2022-09-18 17:12
Can confirm. I think that's a bug on sdl2 side, though

**Comment by isage** [comment] 2022-09-18 18:02
Confirmed as sdl2/vitasdk bug. Closing here.

**Closed by isage** 2022-09-18 18:02 UTC
Labels: bug

**Comment by isage** [comment] 2022-09-18 19:57
https://github.com/libsdl-org/SDL/pull/6257
