### ISSUE TITLE
[Android]: Cursor and virtual mouse button.

### ISSUE THREAD

**Issue by ErickN13** [diasurgical/devilutionX#7163] opened 2024-06-25 02:57 UTC
I'm not able to use the Telekinesis spell, because for that you need the Mouse Cursor and Button, so, Add this in the Next Version of Devilution x

**Comment by kphoenix137** [comment] 2024-06-25 02:59
say please

**Comment by Trihedraf** [comment] 2024-06-25 03:00
Duplicate of #3359

**Comment by ErickN13** [comment] 2024-06-25 03:01
Huh?

**Closed** 2024-06-25 03:01 UTC
