### ISSUE TITLE
No sound effects after the ending cutscene

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#480] opened 2019-11-17 21:17 UTC
After the ending cutscene remains only music since the last few PR's.

**Comment by AJenbo** [comment] 2019-11-17 22:11
So there are no sounds in the menu? What do you mean by last few PRs? Less then 5?

**Comment by Chance4us** [comment] 2019-11-17 22:18
These PR's are within the last 10. So there are no sounds in the menu and after starting new game also no sound in game. To be precise, bisecting would be necessary.

**Comment by Chance4us** [comment] 2019-11-17 22:21
I would say about since bc88560b410ddd9a5b75ff13e25505140f8b4e32

**Comment by AJenbo** [comment] 2019-11-17 22:22
Ok, refering to the number of PRs is a very loose way to define things are they are not merged in the same order as they are created or there committed. There are also commits that get added with out there being a PR.

What commit are you on?

**Comment by AJenbo** [comment] 2019-11-17 22:24
> I would say about since [bc88560](https://github.com/diasurgical/devilutionX/commit/bc88560b410ddd9a5b75ff13e25505140f8b4e32)

Ok, that's only two PRs back, maybe you are refering to commits then.

**Comment by Chance4us** [comment] 2019-11-17 23:13
I am sorry. I got it wrong. The problem has been around for a longer time i thought.
I did not notice it before. It have to be investigated.

**Comment by AJenbo** [comment] 2019-11-17 23:15
Is this a duplicate of https://github.com/diasurgical/devilutionX/issues/392 ?

**Comment by Chance4us** [comment] 2019-11-17 23:27
It is not a duplicate. To reproduce the bug you need to watch or  to skip the ending cutscene.
After watching you will not have any sound in the menu. You will not have any sound in game when fighting or picking or dropping items. I'm building a 64 bit build wit following two commands.
cmake -DBINARY_RELEASE=ON -DASAN=OFF -DDEBUG=OFF ..
cmake --build . -j $(nproc)

**Comment by AJenbo** [comment] 2019-11-18 00:41
`-DASAN=OFF -DDEBUG=OFF` are implicit when specifying `-DBINARY_RELEASE=ON`, could you test it with `cmake ..`.

**Comment by Chance4us** [comment] 2019-11-18 16:23
No difference with cmake..
The proof is attached.
[0.mkv.zip](https://github.com/diasurgical/devilutionX/files/3859554/0.mkv.zip)

To reproduce I would ask you to try following.
1. Load following savegame.
[single_0.sv.zip](https://github.com/diasurgical/devilutionX/files/3859562/single_0.sv.zip)
2. Now you will hear a fireball.
3. After skipping the ending cutscene first the sound in the main menu is no longer available
4. If you try a new game there will be no sound in game also

Thank you for your efforts.
If there are any questions I'm happy to answer.

**Comment by glebm** [comment] 2019-11-18 16:35
@Chance4us By the way, you need to `rm CMakeCache.txt` before passing different flags to `cmake`.

**Comment by Chance4us** [comment] 2019-11-19 16:16
I did:
rm -rf *
including CMakeCache.txt in the build folder.
Please try to reproduce like described as well.
I am sure to be not alone to experience the issue.

**Comment by AJenbo** [comment] 2019-12-30 20:00
Adjusting the audio volume fixes the issues, we might need to reset audio when entering the menu. It's also possible to go to the menu and have NPC dialogs still playing.

**Comment by AJenbo** [comment] 2019-12-30 21:54
It looks like this issue only happens if you have a save game of diablo in his death throes and load it in a session where you haven't killed him. This would skip `sgbSaveSoundOn = gbSoundOn;` leaving `sgbSaveSoundOn` to be a default (probably 0) value and thus audio is turned off when PrepDoEnding is called just before the movie starts. So as best I can tell this is also a bug that would have been in the original game.

**Closed** 2019-12-30 21:59 UTC
Labels: savegame attached

**Comment by AJenbo** [comment] 2019-12-30 23:20
Indeed this bug was also in the original game.
