### ISSUE TITLE
Feature Request: Preserve Monster count for MP characters (and perhaps some statisticts more?)

### ISSUE THREAD

**Issue by xGnoSiSx** [diasurgical/devilutionX#4339] opened 2022-04-04 16:05 UTC
There was a very tedious method that this was supported in D1, haven't tried it here. From the Diablo Wiki you can read it below.
You could say that this was cheaty as you were transfering the count from a session between an MP and SP character - which should not be allowed and is tedious as hell.

I'm not asking to break save compatibility here, just save the counts data alongside the save, on a seperate file for each MP character and be done with it. You could even add more statistics in it, that don't affect gameplay, but would be insteresting for the player: total kill counts, time played, total games, death counts and so on.

I and many would love this, as we only play MP characters all of the time.

```
Monster Counter Work Around

There's a slightly complicated way to trick the game into counting your monster kills forever with a multiplayer character. Thanks to Lochnar for the following method:

The first time you play your multi player character and want to tally kill counts:

    Start the game(s) as always and play through for that session
    When done with the game gather up all your goodies as you would any other time you finished a game
    Instead of selecting Quit Diablo from the menu, select New Game
    Cancel out of each selection until you get back to the screen for single or multi play
    Select single player
    Select new hero and create your kill count character
    When the game is started, don't bother playing
    Select save game from the menu
    Quit Diablo

All games after that which you want to tally:

    Select single player
    Load your saved game for your kill counter character (not new game)
    When the game has loaded select new game from the menu
    Cancel back to the single or multi player selection
    Start your multi player game (any difficulty)
    When done with session (can be any number of multi games but no single player loads) select new game
    Cancel back to single player selection
    Pick your kill counter character but select new game NOT load saved game (load will revert kill count to that save)
    When new game with kill counter character has started, select save game
```

**Comment by AJenbo** [comment] 2022-04-04 16:31
Isn't this a duplicate of https://github.com/diasurgical/devilutionX/issues/3831

**Comment by qndel** [comment] 2022-04-04 17:07
yes

**Closed by qndel** 2022-04-04 17:07 UTC
Labels: enhancement
