### ISSUE TITLE
Inventory items morphing in hellfire mode 

### ISSUE THREAD

**Issue by joewis** [diasurgical/devilutionX#981] opened 2021-01-20 01:40 UTC
**Describe**
All found items in the inventory are morphing when starting a new game in hellfire mode

**To Reproduce**
1. Start game in (default) hellfire mode, create a new character 
2. Go to cathedral and obtain a few items from the church personnel approaching you there
3. start a new game
4. Open inventory and see morphed items
5. Start new game again and see different morphed items

**Expected behavior**
Items shouldn't morph

**Screenshots**
![hellfire1](https://user-images.githubusercontent.com/74438661/105114486-f3e68d80-5b01-11eb-99d2-bc0dbbf14092.png)
![hellfire2](https://user-images.githubusercontent.com/74438661/105114502-f943d800-5b01-11eb-8b57-b5e24ab5c31e.png)

[multi_0.hsv.gz](https://github.com/diasurgical/devilutionX/files/5839616/multi_0.hsv.gz)

**Additional context**
Built from a freshly cloned version DevilutionX v1.1.0-290098fd buillt pn 32bit Linux

**Comment by Trihedraf** [comment] 2021-01-20 05:57
Confirm happens in MinGW x86 and MSVC x86 and x64. Only Hellfire Multiplayer. Hellfire Singleplayer and Diablo Single and Multi are fine.

**Comment by AJenbo** [comment] 2021-01-20 08:14
Thanks, the cause of this is that at the moment all multiplayer save games are considered to be Diablo. I still have to decide research if there is a way to detect a Hellfire hero, or if we have to add our own flag for this.
Note this issue also affect new hellfire single player heros loaded in diablo, but nothing is really lost there as all you would have to redo is enter the hero name.

**Comment by galaxyhaxz** [comment] 2021-01-20 10:12
I think it would be good to unify multi and single saves. The way it currently sits, the packed player save is the same size and there isn't a reliable way to ensure a new save is hellfire or diablo. There are reserved fields you may set a flag in :P

**Comment by qndel** [comment] 2021-01-20 10:16
being able to use same character to play both in single and multi is indeed an interesting idea

**Comment by galaxyhaxz** [comment] 2021-01-20 10:17
They separated them with the intention it would help prevent cheating on battle.net. Only to realize everyone just used trainers that modify the in game memory ;P

**Comment by AJenbo** [comment] 2021-02-21 23:17
Fixed in https://github.com/diasurgical/devilutionX/commit/a5ca521f0d96921d431e17666b3e07944f0673e0

**Closed by AJenbo** 2021-02-21 23:17 UTC
