### ISSUE TITLE
High CPU utilization

### ISSUE THREAD

**Issue by ajes** [diasurgical/devilutionX#116] opened 2019-05-20 11:59 UTC
Game use between 90-100% of core CPU time.

**Comment by AJenbo** [comment] 2019-05-20 12:30
Currently the game appears to be running as fast as the CPU will allow, there is a temporary fix for it that can be enabled by setting SLEEPFIX during build. The reason we don't enable this at the moment is that it's not in intelligent about the system performance and so could cause issues on slow machines.

https://github.com/diasurgical/devilutionX/blob/0c4b4719b88d7b226eaca2a9fa2cb1ef22e971cd/Source/diablo.cpp#L166

**Comment by FooSoft** [comment] 2019-08-05 00:56
While I don't have the problem on my own machine (devilutionx uses about 20% of one core), adding a `Sleep(1)` is never a bad idea, pretty much all games do this in the update loop to avoid hoarding the CPU. It should not be a problem on slow machines either.

**Comment by galaxyhaxz** [comment] 2019-08-05 01:30
Since DevilutionX requires a more modern computer anyway, it shouldn't be a problem. Diablo is a low-requirement game. Diablo 2 has similar sleep code in its' loop and requires more CPU.

For me the issue is that on laptops it can cause heating problems. The high usage makes the CPU-chip get very hot so the fan is going full blast at all times. This is noisy and annoying, puts strain on the fan motor, and also wears away the heat sync-paste on the chip faster. Consistent usage can actually physically damage your computer.

**Comment by OrangBuangan** [comment] 2019-08-05 11:18
Yes, a tick based solution would be good!

**Comment by AJenbo** [comment] 2019-09-15 14:42
Fixed in https://github.com/diasurgical/devilutionX/commit/927b6be8f84b3ee80e1fa0b970e1f121e819e96c

**Closed by AJenbo** 2019-09-15 14:42 UTC
Labels: enhancement
