### ISSUE TITLE
[Issue Report]: RUNE can't use while use gamepad

### ISSUE THREAD

**Issue by jinyukyo** [diasurgical/devilutionX#6591] opened 2023-09-11 04:01 UTC
### Operating System

Windows x64

### DevilutionX version

1.5.1

### Describe

RUNE can't use while use gamepad

### To Reproduce

Put Rune In Belt,Use GamePad,Can't Use

**Comment by StephenCWills** [comment] 2023-09-11 04:29
Duplicate of #3359

Also, this is a very poor description of the problem.

**Closed by StephenCWills** 2023-09-11 04:29 UTC
