### ISSUE TITLE
devilutionX freezes

### ISSUE THREAD

**Issue by lkubaski** [diasurgical/devilutionX#915] opened 2020-11-13 14:03 UTC
[single_0.sv.zip](https://github.com/diasurgical/devilutionX/files/5537177/single_0.sv.zip)

Using Mac OS Catalina (10.15.7) and devilutionX v1.1.0, loading the attached saved game will freeze the whole game after 2s. The only way to exit it is to "Force Quit" it.

**Comment by rayhern** [comment] 2020-12-27 18:18
I can confirm this

**Comment by rayhern** [comment] 2020-12-27 18:19
3ds version also freezes in town only after so long of idling or talking to pepin cain or blacksmith

**Comment by rayhern** [comment] 2020-12-27 18:20
must be level 20 and up, it happened to me with warrior character. Starting the game is fine. Playing up until level 20 about never freezes. This affects both Diablo and Hellfire builds.

**Comment by qndel** [comment] 2020-12-27 18:21
character or dungeon level?

**Comment by rayhern** [comment] 2020-12-30 09:21
Here is my save game. I know it is freezing during the following situations:

Platforms:
New Nintendo 3DS XL
RG351P (Arkos OS)

While in town (these things happen randomly, may not be on the first try):
opening and closing inventory (reordering items)
talking to Pepin the healer and moving the cursor.
talking to Cain and moving the cursor.
also after idling for a period of time the game will also freeze.

While in the dungeon:
I have not noticed a game freeze yet on any platform.

When the game freezes I cannot exit the game and I have to force shut down both systems.

I notice the game does not freeze at all until I get to around level 20 with the warrior class. I am not sure if it is due to a memory limitation on said devices or not. I can try to increase the swap on the RG351P, but I am not sure if that will help. If there is anything else you would like me to test or try out on any platform let me know. I have a MacBook, RG351P, and New 3DS.

Another thing I would like to note is I also tried this same save file on Mac OS X and it seemed to work perfectly. So it is definitely something wrong with the New 3DS, and RG351P (RG350) versions.

My next test is to try leveling a warrior class on multiplayer mode using loopback on the 3ds and RG351P. I will let you know if I experience any freezes there. Thanks for all your help.

[single_0.sv.zip](https://github.com/diasurgical/devilutionX/files/5753660/single_0.sv.zip)

**Comment by rayhern** [comment] 2020-12-30 11:17
> character or dungeon level?

20 character level, sorry for the late reply.

**Comment by AJenbo** [comment] 2020-12-30 12:59
is this also an issue using an older release?

**Comment by rayhern** [comment] 2020-12-30 13:00
I have not tried an older release yet, trying now...

**Comment by rayhern** [comment] 2020-12-30 13:39
I can confirm that the 3ds version 1.0.1 does not freeze when loading in the save game file and doing the things that cause it to freeze. This version does have other issues like not being able to exit the game properly etc. I am sure the RG351P will be the same if I downgrade. Let me know if there is anything else I can do.

**Comment by rayhern** [comment] 2020-12-30 13:41
Something added to version 1.1.0 is causing the game to freeze randomly in town, its really strange. Still no freezes, even character idling is working with the older version.

**Comment by rayhern** [comment] 2020-12-30 14:02
Exhausted system memory with the old version. Looks like memory might be the issue?


[IMG_2878.HEIC.zip](https://github.com/diasurgical/devilutionX/files/5754429/IMG_2878.HEIC.zip)

**Comment by rayhern** [comment] 2020-12-30 14:03
right after i got the black mushroom for the black mushroom quest lol, not sure if that has anything to do with it.

**Comment by AJenbo** [comment] 2020-12-30 14:06
I would say it's safe to assume that this isn't related to any specific event :)

**Comment by rayhern** [comment] 2020-12-30 21:10
I know this is going to sound completely insane, but I am closer to figuring out the problem area. After trying so many things (even turning off the background music) which gives around an extra 20mb of ram, I was still crashing every time I went to identify an item with Cain, or repair an item with Griswold. I was finally able to identify my items, and repair my gear... This is how I did it, I had to strip all my gear off before heading to town. Not the gear in my inventory, the actual gear I was wearing. After I took it off, I was able to visit the shops like normal without freezing on the RG351P with the newest build. I hope this helps someone in need! Also with the item, I was trying to identify it was a shield and I was actually holding it, which gave me the idea to strip, lol. Sorry guys, I just really love Diablo.

**Comment by rayhern** [comment] 2020-12-30 21:12
Hopefully, this info gets a dev closer to the goal.

**Comment by AJenbo** [comment] 2020-12-30 21:24
I'm guessing it is some sort of overflow that might take a little bit before it results in something catastrophic situation, possibly related to store code since you only experience it in town and your inventory content affects it. PC's are much more resilient to issues like that (I'm guessing that they waist a bit of memory on padding to deal with faulty programs in general).

Not going to focus on it right away as I'm working my way through finishing the Hellfire implementation first. Of cause, if anyone else can look into it that would be much appreciated.

**Comment by GlottisLT** [comment] 2021-01-01 09:54
To not create separate topic I can confirm in my own save that at lvl15 i cannot get back to town center to talk with Cain (save file attached).
[single_0.zip](https://github.com/diasurgical/devilutionX/files/5758785/single_0.zip)

Tried to drop all loot that is with me now (go naked) but it didn't help.
Character - Warrior 23lvl
Tried on PC, Android and Switch - v.101, 103 and 110

Don't want to start all game from scratch, when end is just around the corner.

**Comment by qndel** [comment] 2021-01-01 11:40
pc = windows?

**Comment by qndel** [comment] 2021-01-01 11:41
Great success! 1.1.0 freezes for me too! But master doesn't, so we can hope the issues will get fixed in next release

**Comment by qndel** [comment] 2021-01-01 11:56
![image](https://user-images.githubusercontent.com/14297035/103438148-22bec180-4c30-11eb-9aea-2220c76299e4.png)
that's the freeze
so atm I'm closing with 
**Fixed in 1.2.0**
We'll reopen if that's not the case but I managed to load your save fine and it didn't freeze anymore

**Closed by qndel** 2021-01-01 11:56 UTC
Labels: savegame attached
