### ISSUE TITLE
[Issue Report]: Info Panel Mistake with Mouseover on Experience Bar

### ISSUE THREAD

**Issue by NiteKat** [diasurgical/devilutionX#7328] opened 2024-08-12 00:13 UTC
### Operating System

Windows x64

### DevilutionX version

1.5.2

### Describe

If you mouse over the EXP bar, it looks like it might be trying to print the text twice? This happens with all characters, in both Single Player and Multi Player.

![image](https://github.com/user-attachments/assets/2be498b6-3758-49f4-bfd2-f5d3b8cd8380)

### To Reproduce

1. Create a new character in either Single Player or Multi Player.
2. Mouse over the EXP bar and notice it looks like it's printing the message twice in the info pane.

### Expected Behavior

The information should only print once in the info pane.

**Comment by Trihedraf** [comment] 2024-08-12 00:35
Already fixed in #7055

**Closed** 2024-08-12 00:36 UTC

**Comment by NiteKat** [comment] 2024-08-12 00:41
> Already fixed in #7055

Awesome, thanks for linking the fix! I searched opened issues, forgot to search for closed ones. :)

**Comment by qndel** [comment] 2024-08-12 10:37
Duplicate of https://github.com/diasurgical/devilutionX/pull/7055
