### ISSUE TITLE
Default controller binds are inconsistent with using A/Cross and B/Circle for confirm and cancel

### ISSUE THREAD

**Issue by k4gi** [diasurgical/devilutionX#6453] opened 2023-08-12 14:43 UTC
### Operating System

Windows x64

### DevilutionX version

1.5.0 (latest release)

### Describe

In the main menu and pause menu the default controller settings are A for confirm and B for cancel.

cool cool. except.

everywhere "ingame", meaning character, inventory, spell menus etc as well as talking to NPCs, has more of a vibe of using B for confirm and A for cancel

i switched around "Primary Action" and "Cancel", and now things are consistent but I would like it to be the other way around,

### To Reproduce

use a controller in every menu you can get your hands on

### Expected Behavior

all menus should follow the same controller bindings

**Comment by StephenCWills** [comment] 2023-08-12 15:54
Duplicate of #5467

**Closed by StephenCWills** 2023-08-12 15:54 UTC
