### ISSUE TITLE
Implement music fade-in / fade-out for transitions

### ISSUE THREAD

**Issue by julealgon** [diasurgical/devilutionX#800] opened 2020-09-11 00:13 UTC
Coming from playing Diablo 2 to Diablo 1, one of the things I noticed recently is how harsh music transitions are in the original game. They abruptly stop, and then the next music abruptly starts.

I propose we implement a smoother transition when music needs to change, by making the current music fade-out, and the next one fade-in.

While I have no idea exactly on how this could be implemented (maybe changing music volume linearly from 100% to 0% and vice-versa, or something like that), conceptually it sounds like a simple idea and a simple change.

One thing I did notice about Diablo 2 is that these transitions are _very_ long and that the previous and current music actually merge into one another. I'm not entirely sure this would be the best approach here but is something we could discuss. To me, a faster transition without overlap would work fine and is probably a bit simpler to implement.

Think of this as a sort of animation for sound: when the music is told to stop, it "animates" to that state instead of changing instantly. Same thing for starting a new music.

Optionally, we could look into this depending on the music. I know some of the music in D1 actually has this "native" fade-in embedded into the song itself (the beginning of the cathedral music is just so awesome to me), so maybe introducing a programmatic fade-in would impact on the song too much. Perhaps we could implement only fade-out and leave standard music to work as the fade-in element? Surely the worst offender is when a music abruptly stops, IMHO.

This has similar benefits to #799, basically making the overall experience smoother.

Let me know what you think.

**Comment by AJenbo** [comment] 2020-09-11 00:28
Probably calling Mix_FadeOutMusic would do the trick.

Regarding music, something that would be really valuable is if we could implement streaming music and dialog like the original did, since we use a lot more memory because fully loading the wave files.

**Comment by julealgon** [comment] 2020-09-11 00:35
> streaming music and dialog like the original did

Can you elaborate a bit more on this? Do you mean we are playing music in a different way compared to vanilla in DevilutionX? Sorry about my ignorance, just honestly curious as I haven't even opened any of the code related to sound yet.

If that's the case, sounds like it would be valuable to keep track of "streaming music" as a separate issue, right?

**Comment by AJenbo** [comment] 2020-09-11 01:17
Storm contains a function to start streaming a given wave file, this is called when playing music and for one time sounds like player dialog. We lazily implemented this to simply load the whole audio file in memory and then play it like any other sound in the game. But obviously this eats ups a lot more ram (this is exactly why they did streamed it instead).
https://github.com/diasurgical/devilutionX/blob/master/SourceX/storm/storm.cpp#L93

> If that's the case, sounds like it would be valuable to keep track of "streaming music" as a separate issue, right?

yes

**Comment by AJenbo** [comment] 2020-09-28 05:13
Closing, the transitions are as intended, and I have a hard time seeing how we could consistently improve it.

**Closed by AJenbo** 2020-09-28 05:13 UTC
Labels: enhancement, proposal
