### ISSUE TITLE
Map keyboard binds to controller/WASD movement

### ISSUE THREAD

**Issue by gitdrug** [diasurgical/devilutionX#6469] opened 2023-08-15 06:36 UTC
Allow mapping keyboard buttons to the options in the controller mappings settings to allow WASD movement and playing with only a keyboard.

**Comment by qndel** [comment] 2023-08-15 07:33
Duplicate of https://github.com/diasurgical/devilutionX/issues/6451

**Closed by qndel** 2023-08-15 07:33 UTC
