### ISSUE TITLE
[Issue Report]: Toggling upscale crashes devilutionX

### ISSUE THREAD

**Issue by h3xOo** [diasurgical/devilutionX#7376] opened 2024-08-28 12:48 UTC
### Operating System

Linux x64

### DevilutionX version

1.5.2

### Describe

When toggling upscale "on -> off -> on", game crashes on "off -> on" with window:
![obraz](https://github.com/user-attachments/assets/de9bc120-57a2-4326-8fa3-77a3c466e268)
I'm using river on wayland from Artix Linux. (when I switch "on -> off", window moves from center to bottom left corner).

I also have installed devilutionx-fonts and devilutionx-voices (all three packages from are AUR).

### To Reproduce

1. With default configuration, go to Settings -> Graphics
2. Toggle Upscale On -> Off
3. Window should (?) move to bottom left corner
4. Toggle again
5. Game crashes

### Expected Behavior

Game wouldn't crash

**Comment by StephenCWills** [comment] 2024-08-28 13:11
Duplicate of #5168, #6055, #6387, #7141, and probably a few others.

**Closed by StephenCWills** 2024-08-28 13:11 UTC
