### ISSUE TITLE
Monster Stuck In Missile State (Save From Vanilla)

### ISSUE THREAD

**Issue by NiteKat** [diasurgical/devilutionX#2877] opened 2021-09-16 19:19 UTC
**Important information**
Windows 10 / tested with 1.2.1 and fa3499432f7fde0a2635f8b1ff96f8e50c49bb65 / release downloaded, commit compiled myself

**Describe**
While playing Vanilla Diablo two snakes became bugged as missiles on floor 13. One was able to be fixed using the telekinesis spell. The other was not. This is the first time I've seen this where TK could NOT fix the bugged monster. Tried loading in DevilutionX, 1.2.1, and commit fa3499432f7fde0a2635f8b1ff96f8e50c49bb65. Not sure if DevX is supposed to fix monsters that are bugged in save files (I thought so?), but it does not fix this one, and TK still doesn't resolve the problem.

**To Reproduce**
1. Load the save file, and see the snake that is bugged right next to the player character.

**Expected behavior**
Either TK should fix the monster, or loading the save in DevX should fix the monster? Not sure on the latter, but I think this monster got messed up in a way I haven't seen before. 😆 

**Screenshots**
![image](https://user-images.githubusercontent.com/28605404/133672106-3d45949f-6507-4385-90fb-e82ff8580f40.png)
![image](https://user-images.githubusercontent.com/28605404/133672130-22d4d4b2-8812-4b07-896d-fe26589a29f0.png)
Screenshots made using 1.2.1 for ease of launching.

**Additional context**
Save file:
[single_2.zip](https://github.com/diasurgical/devilutionX/files/7180449/single_2.zip)

**Comment by julealgon** [comment] 2021-09-16 20:05
This should also happen to horned demons right? Didn't we have a similar issue with them becoming stuck?

This issue describes something really similar (even though that one was fixable with TK as you say):
- #2463

**Comment by qndel** [comment] 2021-09-16 20:08
> This should also happen to horned demons right? Didn't we have a similar issue with them becoming stuck?
> 
> This issue describes something really similar (even though that one was fixable with TK as you say):
> 
> * [Charging monsters ends up in an invalid state on level change #2463](https://github.com/diasurgical/devilutionX/issues/2463)

Yes, the ONLY difference is that this isn't fixable with TK.

**Comment by qndel** [comment] 2021-09-16 20:28
```cpp
void M_GetKnockback(int i)
{
	auto &monster = Monsters[i];

	Direction d = Opposite(monster._mdir);
	if (!DirOK(i, d)) {
		SDL_Log("FAILED DIR CHECK");
		return;
	}
```
`INFO: FAILED DIR CHECK`
This is the same old bug, just the monster got stuck in such a place that knockback wasn't possible = can't unstuck manually, closing as a duplicate of https://github.com/diasurgical/devilutionX/issues/2463.

**Closed by qndel** 2021-09-16 20:28 UTC
Labels: bug, savegame attached, vanilla
