### ISSUE TITLE
[Issue Report]: Controller Mapping not working for A & B buttons

### ISSUE THREAD

**Issue by kanjieater** [diasurgical/devilutionX#7557] opened 2024-11-25 23:04 UTC
### Operating System

PlayStation Vita

### DevilutionX version

1.5.3

### Describe

I cannot swap my x & o buttons. I have a japanese style playstation layout where O is select and X is cancel. I tried using the pad mapper like my ini shows below, but even if the change shows there the select and back button do not change from the original behavior.

Viewing this, I also tried to use the deprecated Controller section, but also had no results
https://github.com/diasurgical/devilutionX/blob/master/docs/manual/platforms/vita.md

Other ini behavior like disabling the rear touchpad via config work just fine.

### To Reproduce

1. Use the diablo.ini
2. Try to swap the A & B buttons (B being select and A being cancel)
3. Notice nothing changed

### Expected Behavior

A & B buttons should be swappable in menu and game

### Additional context

```ini

[devilutionx]
integer scaling=0
fullscreen=1
grab input=0
original aspect ratio=0
game speed=20


[Diablo]
Intro=0
LastSinglePlayerHero=0
LastMultiplayerHero=0


[Hellfire]
Intro=0
LastSinglePlayerHero=0
LastMultiplayerHero=0
SItem=


[Game]
Run in Town=1
Theo Quest=1
Cow Quest=1
Test Bard=1
Test Barbarian=1
Experience Bar=1
Enemy Health Bar=1
Auto Gold Pickup=1
Adria Refills Mana=1
Auto Equip Weapons=1
Auto Equip Armor=1
Auto Equip Helms=1
Auto Equip Shields=1
Auto Equip Jewelry=1
Randomize Quests=1
Show Monster Type=1
Disable Crippling Shrines=1
Speed=20
Friendly Fire=1
MultiplayerFullQuests=0
Quick Cast=0
Show Item Graphics in Stores=0
Show health values=0
Show mana values=0
Show Item Labels=0
Enable floating numbers=0
Auto Refill Belt=0
Auto Elixir Pickup=0
Auto Oil Pickup=0
Heal Potion Pickup=0
Full Heal Potion Pickup=0
Mana Potion Pickup=0
Full Mana Potion Pickup=0
Rejuvenation Potion Pickup=0
Full Rejuvenation Potion Pickup=0
Auto Pickup in Town=0
Grab Input=0


[Language]
Code=ja


[StartUp]
Game=2
Shareware=0
Diablo Intro=0
Hellfire Intro=0
Splash=2


[Graphics]
Width=960
Height=544
Fit to Screen=1
Upscale=1
Scaling Quality=2
Integer Scaling=0
Vertical Sync=1
Gamma Correction=100
Zoom=0
FPS Limiter=1
Show FPS=0
Color Cycling=1
Alternate nest art=0
Hardware Cursor=1
Hardware Cursor For Items=0
Hardware Cursor Maximum Size=128


[Audio]
Sound Volume=0
Music Volume=0
Walking Sound=1
Auto Equip Sound=0
Item Pickup Sound=0
Sample Rate=22050
Channels=2
Buffer Size=2048
Resampler=Speex
Resampling Quality=3
Device=


[Network]
Port=6112
Bind Address=0.0.0.0
Previous Game ID=
Previous Host=


[Keymapping]
BeltItem1=1
BeltItem2=2
BeltItem3=3
BeltItem4=4
BeltItem5=5
BeltItem6=6
BeltItem7=7
BeltItem8=8
QuickSpell1=F5
QuickSpell2=F6
QuickSpell3=F7
QuickSpell4=F8
QuickSpell5=
QuickSpell6=
QuickSpell7=
QuickSpell8=
QuickSpell9=
QuickSpell10=
QuickSpell11=
QuickSpell12=
UseHealthPotion=
UseManaPotion=
DisplaySpells=S
QuickSave=F2
QuickLoad=F3
StopHero=
Item Highlighting=LALT
Toggle Item Highlighting=RCONTROL
Toggle Automap=TAB
Inventory=I
Character=C
QuestLog=Q
SpellBook=B
QuickMessage1=F9
QuickMessage2=F10
QuickMessage3=F11
QuickMessage4=F12
Hide Info Screens=SPACE
Zoom=Z
Pause Game=P
DecreaseGamma=G
IncreaseGamma=F
Help=F1
Screenshot=PRINT
GameInfo=V
ChatLog=L


[Padmapping]
BeltItem1=
BeltItem2=
BeltItem3=
BeltItem4=
BeltItem5=
BeltItem6=
BeltItem7=
BeltItem8=
QuickSpell1=
QuickSpell2=
QuickSpell3=
QuickSpell4=
QuickSpell5=
QuickSpell6=
QuickSpell7=
QuickSpell8=
QuickSpell9=
QuickSpell10=
QuickSpell11=
QuickSpell12=
PrimaryAction=B
SecondaryAction=Y
SpellAction=X
CancelAction=A
MoveUp=Up
MoveDown=Down
MoveLeft=Left
MoveRight=Right
StandGround=
ToggleStandGround=
UseHealthPotion=LB
UseManaPotion=RB
Character=LT
Inventory=RT
QuestLog=Select+LT
SpellBook=Select+RT
DisplaySpells=B
Toggle Automap=LS
MouseUp=Select+Up
MouseDown=Select+Down
MouseLeft=Select+Left
MouseRight=Select+Right
LeftMouseClick1=RS
LeftMouseClick2=Select+LB
RightMouseClick1=Select+RS
RightMouseClick2=Select+RB
PadHotspellMenu=Select
PadMenuNavigator=Start
ToggleGameMenu1=Select+Start
ToggleGameMenu2=Start+Select
QuickSave=
QuickLoad=
Item Highlighting=
Toggle Item Highlighting=
Hide Info Screens=
Zoom=
Pause Game=
DecreaseGamma=
IncreaseGamma=
Help=
Screenshot=
GameInfo=
ChatLog=


[NetMsg]
QuickMessage1=助け​て​ください。ここ​に​来​て​!
QuickMessage2=つい​て​き​て。
QuickMessage3=これ​は、あなた​の​ため​に​用意​し​た​もの​です。
QuickMessage4=さあ、死ぬ​ん​だ​!


[Controller]
Mapping=y:b0,b:b2,a:b1,x:b3,leftshoulder:b4,rightshoulder:b5,dpdown:b6,dpleft:b7,dpup:b8,dpright:b9,back:b10,start:b11,leftx:a0,lefty:a1,rightx:a2,righty:a3
deadzone=0.070000
Enable Rear Touchpad=0

```

**Comment by Trihedraf** [comment] 2024-11-25 23:08
Duplicate of #5467

**Closed** 2024-11-25 23:08 UTC
