### ISSUE TITLE
A couple of bugs with the new menu rendering

### ISSUE THREAD

**Issue by glebm** [diasurgical/devilutionX#591] opened 2020-02-09 02:17 UTC
After #587 , I've noticed a couple of issues on RG300

A couple of bugs with the new menu rendering (as seen on RG300):
1. When going Multiplayer->Loopback, the hero image flashes green
2. All text disappears during the transition back from Single Player to main menu

(1) is reproducible on PC as well (SDL1)
(2) not sure, PC is too fast

@AJenbo

**Comment by AJenbo** [comment] 2020-02-09 02:37
1: Probably because BlackPalette() nolonger clear the screen. Possibly the palette is lacking behind by a frame. I also see this on SDL2 when upscaling is enabled.
2: Is it gone for the full transition or just the first frame?

**Comment by glebm** [comment] 2020-02-09 02:39
(1) The green flash only happens on the first transition to that screen. Subsequent transitions are OK.
(2) Full transition, or most of it

**Comment by AJenbo** [comment] 2020-02-09 02:40
2: If you add a SDL_Delay(100) to the start of UiFadeIn() does this give you the same issue?

**Comment by glebm** [comment] 2020-02-09 02:45
(2) Yes, and it makes it possible to see the issue on PC as well.

```diff
diff --git a/SourceX/DiabloUI/diabloui.cpp b/SourceX/DiabloUI/diabloui.cpp
index dc927ddd..a419017f 100644
--- a/SourceX/DiabloUI/diabloui.cpp
+++ b/SourceX/DiabloUI/diabloui.cpp
@@ -577,6 +577,7 @@ void LoadBackgroundArt(const char *pszFile)
 
 void UiFadeIn()
 {
+	SDL_Delay(100);
 	if (fadeValue < 256) {
 		if (fadeValue == 0 && fadeTc == 0)
 			fadeTc = SDL_GetTicks();
```

**Comment by AJenbo** [comment] 2020-02-09 02:47
Ok, there is not supposed to be a transition going back, the screen should just go black. This is definatly caused by BlackPalette() not blanking the screen any more

**Comment by AJenbo** [comment] 2020-02-09 03:16
1: appears to have been a missing call to blackpalette(), both are now fixed with a little bit of clean up.

**Closed** 2020-02-09 13:39 UTC
Labels: bug
