### ISSUE TITLE
Crash on exit

### ISSUE THREAD

**Issue by GrayFace** [diasurgical/devilutionX#2220] opened 2021-06-23 22:23 UTC
**Important information**
Operating system Win 7 x64/ DevilutionX version 1.2.1 / official release

**Describe**
Sometimes (not often) it crashes upon pressing Alt+F4.

**To Reproduce**
1. Press Alt+F4.

**Additional context**
Here's a crash dump: [devilutionx crash.zip](https://github.com/diasurgical/devilutionX/files/6705153/devilutionx.crash.zip)

**Comment by julealgon** [comment] 2021-06-23 22:32
Does it _only_ happen when closing via Alt+F4?

**Comment by GrayFace** [comment] 2021-06-23 23:00
I don't know, I only exit via Alt+F4.

**Comment by AJenbo** [comment] 2021-06-23 23:08
Could you test by selecting exit game in the main menu and and in-game so that we have a better chance of tracing down the issue.

**Comment by ephphatha** [comment] 2021-06-24 02:08
I have been able to reliably reproduce this by clicking the close button when running devilutionx in windowed mode. Haven't exactly tracked the cause down but it seems to be one of the cleanup routines gets called twice and the second call tries to clear a vector that has already been freed.

**Comment by ThomasChr** [comment] 2021-08-10 17:31
Easy to reproduce in windows. Didn‘t have problems in Linux. Simply close the window in windowed mode by clicking on the "Window close" X in the upper right corner.

**Closed** 2021-08-10 20:01 UTC
Labels: bug
