### ISSUE TITLE
Bisect objects being off by one tile when loading a save

### ISSUE THREAD

**Issue by AJenbo** [diasurgical/devilutionX#2082] opened 2021-05-30 03:56 UTC
As can be seen in the screen shots in https://github.com/diasurgical/devilutionX/issues/2028

Objects are shifted 1 tile position when loading a save game, this has happened some time between `1.2.0` and https://github.com/diasurgical/devilutionX/commit/a1281d8b5459625ea47678d77d4d97cac7bb1f2d and needs to be bisected.

https://github.com/diasurgical/devilutionX/files/6519081/single_0.hsv.zip can probably be used as a test.

**Comment by Chance4us** [comment] 2021-05-30 16:09
@AJenbo I think the problem already exists with commit a1281d8, because the misaligned lava tiles are already present with it.
I didn't check before commit a1281d8 because Hellfire support was very early at that time.
I suspect that it could be difficult and that it may have to be checked in the devilution branch.

**Comment by AJenbo** [comment] 2021-05-30 16:21
> @AJenbo I think the problem already exists with commit [a1281d8](https://github.com/diasurgical/devilutionX/commit/a1281d8b5459625ea47678d77d4d97cac7bb1f2d), because the misaligned lava tiles are already present with it.
> I didn't check before commit [a1281d8](https://github.com/diasurgical/devilutionX/commit/a1281d8b5459625ea47678d77d4d97cac7bb1f2d) because Hellfire support was very early at that time.
> I suspect that it could be difficult and that it may have to be checked in the devilution branch/repo.

Different issue, you are talking about #2028, this is #2082

**Comment by Chance4us** [comment] 2021-05-30 18:04
If, for example, a shifted sarcophagus is meant, then it is caused by commit 239a43cc1c6bb720aba80027daa400bc31ff2abd.

**Comment by AJenbo** [comment] 2021-05-30 19:06
@obligaron any ideas :)

**Closed** 2021-05-31 01:31 UTC
Labels: bug, savegame attached
