### ISSUE TITLE
Save game Segfault

### ISSUE THREAD

**Issue by CubeTheThird** [diasurgical/devilutionX#227] opened 2019-08-09 03:26 UTC
Loading a previously saved game causes a segfault. The save is functional on the original Diablo, and was made in 32 bit release.

Current DevilutionX release: 0.4.0.r307.gf1da6e6a

Output log is found here:
[output.txt](https://github.com/diasurgical/devilutionX/files/3484609/output.txt)

Save game file here:

[single_0.sv.zip](https://github.com/diasurgical/devilutionX/files/3484613/single_0.sv.zip)

**Comment by AJenbo** [comment] 2019-09-15 15:14
Can you check if this save game works with vanilla 1.09?

**Comment by AJenbo** [comment] 2019-09-15 15:17
Can you try this with a release build instead of a debug build since the overflow might be a bug in the original game that is triggering the address sanitizer

**Comment by CubeTheThird** [comment] 2019-09-15 21:27
Yes, I can confirm that the save file works correctly on release 0.4.0, so you may be correct in that assessment.

**Comment by AJenbo** [comment] 2019-09-15 21:56
Oh I was thinking of you compiling for release instead of debug (see Readme).

**Comment by AJenbo** [comment] 2019-09-19 22:23
I can confirm that this also crashes on release builds

**Comment by AJenbo** [comment] 2019-09-21 20:52
This issue is fixed as of https://github.com/diasurgical/devilutionX/commit/b90ef1336d0fa23288768b420fb2cbe5356fbfdd

**Closed by AJenbo** 2019-09-21 20:52 UTC
Labels: bug, help wanted, savegame attached
