### ISSUE TITLE
Game crashes when opening inventory after picking up specific item(s)

### ISSUE THREAD

**Issue by FelixMoelder** [diasurgical/devilutionX#38] opened 2019-03-14 09:15 UTC
While it is possible to open the inventory all the time I have the issue, breaking the game when opening the inventory after picking up a "Book of Holy Bold".
After that happened the first time, I started a new run and checked if I can open the inventory in the dungeons. While that was no problem it crashed directly after picking up that book and opening the inventory.

This issue occurred for me playing with a 32bit build on macOS Mojave.

**Comment by AJenbo** [comment] 2019-03-14 09:22
Could you please provide a console log from the crash and possibly a save game that makes this easy to replicate?

**Comment by FelixMoelder** [comment] 2019-03-14 09:41
Sure!
I just tried it again and created a save directly in front of a book lieing on the floor. That bug seems to affect different (all?) kind of books.
[single_0.sv.zip](https://github.com/diasurgical/devilutionX/files/2965686/single_0.sv.zip)
[devilutionX_crashreport.txt](https://github.com/diasurgical/devilutionX/files/2965690/devilutionX_crashreport.txt)

**Comment by AJenbo** [comment] 2019-03-14 11:12
Thanks this is very helpful, the log makes it clear that the issue is with rendering red items (higher stats required the the player has), it should be easy enough to solve.

**Comment by FelixMoelder** [comment] 2019-03-16 17:56
Sounds great!
I was able to reach level 13 on macOS without any new issues besides the ones that were already reported.
I might be able to test the patch tomorrow and check if the crashes are solved.

**Comment by FelixMoelder** [comment] 2019-03-17 16:04
The patch solves this issue indeed.
Picking up items which the character can not use and opening the inventory is now possible.

**Comment by AJenbo** [comment] 2019-03-17 16:46
Thank for testing, that's good hear I'll prioritize getting this merged when ready and then close this issue.

**Closed** 2019-03-17 23:16 UTC

**Comment by AJenbo** [comment] 2019-03-17 23:23
It's now in master, now we just need the 32bit Mac part :)
