### ISSUE TITLE
[Issue Report]: Lazarus starting sequence issues

### ISSUE THREAD

**Issue by locksoft** [diasurgical/devilutionX#7025] opened 2024-03-16 16:16 UTC
### Operating System

Nintendo Switch

### DevilutionX version

1.5.2

### Describe

Here are some more details about the Lazarus event triggering. The short video, where camera zooms into the cathedral, plays (randomly) like one time every three (this time it didn't happen). Most of the times I teleport in the room all mobs are like frozen. They just look at me, rotating to follow my movements, but nothing happens until I interact (click) with Lazarus (didn't try to do with other mobs, maybe it's the same).
At this point, if I move out of view (like going in another room) while Lazarus is still talking, I think the procedure sorts of "resets", and Lazarus starts talking again from the beginning if I return back. I remember he did that at least three times in a previous run.
If I stay in the room while he's speaking, at the end they literally fry me (the fight correctly starts). :)

https://github.com/diasurgical/devilutionX/assets/204594/2ff58192-e257-44f8-be25-b12d7e450d4f

### To Reproduce

Teleport in Lazarus room (Nintendo Switch's version) and don't click anywhere.

### Expected Behavior

I guess the video should start and, at the end, Lazarus sayng his bla bla bla and the fight starts.

**Comment by Sergei3000yt** [comment] 2024-03-16 16:39
In vanilla Diablo it works like this - the video plays when interacting with the teleportation circle in Lazarus' room. Then he reenacts his speech about why the hell you’ll save the boy, and then the fight begins. Also works on Android version DevX 1.5.2 and earlier versions

**Comment by locksoft** [comment] 2024-03-16 16:53
> In vanilla Diablo it works like this - the video plays when interacting with the teleportation circle in Lazarus' room. Then he reenacts his speech about why the hell you’ll save the boy, and then the fight begins. Also works on Android version DevX 1.5.2 and earlier versions

I don't have anymore that save game but, according to this video (https://www.youtube.com/watch?v=I6fQSUNR0Aw) the cinematic should start as soon as you teleport in Lazarus room. And, as it ends, Lazarus starts talking and the fight begin.
As you can see from my video, nothing happens and I'm just there in his room walking around freely.
This could be related to the fact that cinematic didn't start (next time it does, I'll check more carefully).

**Comment by Sergei3000yt** [comment] 2024-03-16 17:05
> To give more context I'm playing Hellfire, but I (almost) sure the issue was there even in vanilla Diablo.

Judging by the video, I can assume that in DevX, due to some long-standing error, we are teleported not to the circle in Lazarus’s room, but next to him, and the trigger in the video is located right on the circle. Well, or this error exists since a certain version of vanilla Diablo.

**Comment by locksoft** [comment] 2024-03-16 17:09
> > To give more context I'm playing Hellfire, but I (almost) sure the issue was there even in vanilla Diablo.
> 
> Judging by the video, I can assume that in DevX, due to some long-standing error, we are teleported not to the circle in Lazarus’s room, but next to him, and the trigger in the video is located right on the circle. Well, or this error exists since a certain version of vanilla Diablo.

Hmmm... it could be possible (I've just read the post about the mini map incorrect alignment of the player in the last developer version), even if the symbol on the ground seems selected when the character appears. I'm sure that in some previous run the video started, so there could be something that could slightly changes when interacting with the teleport the first time.

**Comment by kphoenix137** [comment] 2024-03-17 02:29
Can you reupload the video? It doesn't appear to be working

**Comment by locksoft** [comment] 2024-03-17 02:32
> Can you reupload the video? It doesn't appear to be working

The thumbnail isn’t showing for me either, I see a blank square (no idea why). But if I click it the video starts. It’s not the same for you?

**Comment by AJenbo** [comment] 2024-03-17 03:38
Yeah I had to downlaode it to play it.
Firefox didn't want to play it at all and Chrome only played the audio

**Comment by StephenCWills** [comment] 2024-03-17 04:26
I fixed it for you guys.

**Comment by AJenbo** [comment] 2024-03-17 05:10
> I fixed it for you guys.

Works in Firefox and Chrome, but not Chrome on my Android phone... 2024 and still video playback in the browser is as problematic as when we needed Flash for it :D


Any way back on topic, I do seem to remember having this issue at some point when testing using gamepad and it boiled down to being able to issue a move sooner then you can with a mouse allowing you to escape the event somehow. So I think @Sergei3000yt is right in his explanation.

**Comment by AJenbo** [comment] 2024-03-17 05:19
Here is where the video is initiated: https://github.com/diasurgical/devilutionX/blob/1.5/Source/monster.cpp#L2785

As you can see it triggered by Lazarus when see sees the player standing on the exact spot in the level. But there are several conditions that also must apply. I'm guessing that the player manages to move out of the tile before vision is updated, and at that point Lazarus changes move to Stand and so will no longer trigger the video even if the player returns to the tile.

**Comment by AJenbo** [comment] 2024-03-17 05:28
Arh, here we go: https://github.com/diasurgical/devilutionX/issues/512#issuecomment-565760612

I removed it from the list of gamepad issues since I found out that it can be done with the mouse as well, but never created an issue for it :D

**Comment by locksoft** [comment] 2024-03-17 16:57
Sorry for the problem, guys, I re-encoded it in h264. Now every browser should be able to play it (the one fixed by @StephenCWills doesn't open for me in Safari):

http://gofile.me/6RvCQ/Gj3RR5JN7

I used h265 because the file was too big to upload it (and still is, as it's 11 MB).

**Comment by locksoft** [comment] 2024-03-17 17:00
To be honest it's not that big issue. It's nice to explore the room with people staring at you. :)
The only problem is that neither the cinematic starts, but at the 10th run it's no more a problem anymore.

**Comment by AJenbo** [comment] 2024-03-17 17:38
I didn't have any issues uploading your video

**Comment by locksoft** [comment] 2024-03-17 17:50
> I didn't have any issues uploading your video

This is the problem I incurred in:

![Screenshot 36](https://github.com/diasurgical/devilutionX/assets/9337221/a764957a-3fa0-4ed4-8841-6a5aaabc2827)

The file is 11 MB. :)

**Comment by AJenbo** [comment] 2024-03-17 19:28
Yes, but I didn't. I probably have extra permissions, idk

**Comment by StephenCWills** [comment] 2024-05-05 04:05
I'm not sure what it was that resolved the issue, but it seems to be fixed in 1.6.0.

**Closed by StephenCWills** 2024-05-05 04:05 UTC
Labels: vanilla

**Comment by AJenbo** [comment] 2024-05-05 04:30
> I'm not sure what it was that resolved the issue, but it seems to be fixed in 1.6.0.

It's not always easy to trigger, especially not without a game controller. Did you replicate it on earlier builds?

**Comment by StephenCWills** [comment] 2024-05-05 04:43
Yes, I consistently reproduced on 1.5.2 on both Windows and Ryujinx. I couldn't do it on 1.6.0 on either platform.

**Comment by AJenbo** [comment] 2024-05-05 04:45
Well that is good news then :)
