### ISSUE TITLE
Toggle-able Autosave Feature 

### ISSUE THREAD

**Issue by TheWorldMachine** [diasurgical/devilutionX#6278] opened 2023-06-28 03:47 UTC
Sometimes when people get really engaged in their play session, they often forget to save at certain points  which can be very annoying when you go down 3 levels and end up realizing that you didn't save and lost all your progress. This is why I think a toggleable autosave feature should be placed.

This feature would be accessed through the in-game options, rather than the Main Menu options, for people that like to start new games looking for better gear from Griswold or Wirt, or just for leveling purposes. This feature would also always be disabled by default aswell.

Good points to have the game autosave would be:

Entering a new level,
Going into town through a Town Portal,
Killing a major boss (Butcher, Leoric, Lazurus, Na-Krul, etc),
Reading a book,
and Completing a quest

Bad points for an autosave would be:

Starting a new game,
Killing Diablo,
Exiting Town through a Town Portal,
In the middle of going through a level,
and Buying something or identifying something

I think this would be a MASSIVE time saver for people that often forget alot, or get really focused, engaged, or sidetracked. Anyone else on-board?

**Comment by FitzRoyX** [comment] 2023-06-28 04:31
Did you just make a new github account to request the same thing you did two weeks ago?

**Comment by StephenCWills** [comment] 2023-06-28 06:11
Duplicate of #6228

**Closed** 2023-06-28 06:11 UTC
