### ISSUE TITLE
Menu crash from invalid save file

### ISSUE THREAD

**Issue by Zakarrum** [diasurgical/devilutionX#6150] opened 2023-05-26 05:18 UTC
### Operating System

Windows x64

### DevilutionX version

1.4.1 (latest release)

### Describe

[single_0.zip](https://github.com/diasurgical/devilutionX/files/11571725/single_0.zip)

My power went out while I was somewhere on level 13. Now whenever I launch the game and click "Single Player", the game crashes to a black screen with no error message and I suspect the save file is corrupted.

I only have a single character, and when I remove single_0.sv from C:\Users\%USERNAME%\AppData\Roaming\diasurgical\devilution the game no longer crashes.

Attached is my only save file.

### To Reproduce

1. Add single_0.sv to save game folder: :\Users\%USERNAME%\AppData\Roaming\diasurgical\devilution
2. Launch game 
3. Click "Single Player"
4. Game Crash

### Expected Behavior

Brought to character selection screen.

**Comment by Zakarrum** [comment] 2023-05-27 01:50
I've been trying to figure out how to read the save file myself, are they any tools available for that?  I can't make heads or tales of the file in a hex editor. Been searching for the last day for some tips or tools and I've only found very sketchy sites.

**Comment by DakkJaniels** [comment] 2023-05-27 02:01
It's encrypted so you won't (easily) be able to.

**Comment by Korth999** [comment] 2023-05-27 19:02
Corrupt/damaged save file.

This is not an issue with the game. Although perhaps some sort of autosave/backup/restore feature might be worthwhile.

You can backup your save files by manually copying them into another folder.

**Comment by StephenCWills** [comment] 2023-05-27 19:16
I reproduced the crash in 1.4.1. Looks like the crash is already fixed in the latest test builds.

![image](https://github.com/diasurgical/devilutionX/assets/9203145/fd2588bc-b980-423d-8b4e-e55765d0f70f)

The test build basically behaves as if this is a new character and therefore doesn't allow you to Load Game. But the character can be used in a new game, no problem.

![image](https://github.com/diasurgical/devilutionX/assets/9203145/f5113bb7-0e35-4236-8a3b-97cb5398599d)

**Closed by StephenCWills** 2023-05-27 19:16 UTC
