### ISSUE TITLE
[Issue Report]: Cleared controller mappings still performing actions. Forced to use default control scheme.

### ISSUE THREAD

**Issue by Paranoid-Andy** [diasurgical/devilutionX#7329] opened 2024-08-12 10:13 UTC
### Operating System

Windows x64

### DevilutionX version

1.5.2

### Describe

*** Edit 8/15/2024 ***
While the issue isn't exactly solved, @StephenCWills did figure out a very good workaround.
TLDR: A controller with just a D-pad and no analog stick may be viewed by the game incorrectly and treat the D-pad as a stick. Stephen suggested "try increasing your deadzone to 1 in diablo.ini" and it fixed the issue immediately by essentially ignoring all input at that point allowing me to use Joy2Key instead.
*** End Edit ***

Windows 11
Devilution 1.5.2
Windows Device Name: "SFC/USB Pad" (It's a Super Nintendo controller to USB adapter)

Hi everyone. This seems like an issue, my apologies if it's not.

When I clear all of the controller mappings in the options menu I would expect any press of a button on my controller should do nothing at all. Instead the game still performs those actions anyway.

For example, even though 'LEFT' on the D-Pad is cleared in the options, when I press 'LEFT' on the D-Pad my character still moves to the left in game.

I didn't see any option to outright disable gamepad support in the options menu which would be the preferred fix.

Why do I want to be able to clear controller input entirely? Because I really prefer to use a program of my own like Joy2Key as it has additional features built into it that help me with my disability, but as of right now because the controller input can't be cleared, I'm not able to use Joy2Key without it performing a seemingly 'hard coded' action on each of the keys forcing me to use a sort of default controller scheme.

I'm not able to play the game at this time because of this but still I have to say it looks fantastic and it's so great to see such a classic game modernized. Thank you!

-Andy

### To Reproduce

1. Go to 'Options' on 'Main Menu'.
2. Clear all controller mappings.
3. Press any buttons on controller.

### Expected Behavior

Cleared controller input should result in nothing happening.

**Comment by Raj3110** [comment] 2024-08-12 10:31
hello! i am very much interested to solve this bug. its my first open source contribution, so could u assign it to me?

**Comment by qndel** [comment] 2024-08-12 10:34
> hello! i am very much interested to solve this bug. its my first open source contribution, so could u assign it to me?

We don't assign stuff, you can submit a pull request fixing this issue and if we like it, it will get merged

**Comment by Paranoid-Andy** [comment] 2024-08-14 19:00
I'd like to add an update. It seems as though it's specifically the D-Pad buttons that are acting more "hard coded". The other buttons are able to be unbound but even when they're empty, pressing the button still causes the mouse to momentarily disappear as if it's trying to perform some sort of action. Definitely odd.

**Comment by StephenCWills** [comment] 2024-08-14 20:25
I can't reproduce this issue. When I unbind my movement buttons, I cannot move my character unless I use the left analog stick.

**Comment by Paranoid-Andy** [comment] 2024-08-14 20:48
Hmmm. I wonder if it thinks the D-Pad on my SNES controller is an analog stick. Are you able to unbind movement from your analog stick?

**Comment by StephenCWills** [comment] 2024-08-14 21:11
Unfortunately, the analog stick is a special case since we need to interpret its events a lot differently from buttons. But maybe you can try increasing your deadzone to `1` in `diablo.ini`.

https://github.com/diasurgical/devilutionX/wiki/DevilutionX-diablo.ini-configuration-guide#Controller

**Comment by Paranoid-Andy** [comment] 2024-08-15 11:40
Well that answered some questions. Indeed yes, it does seem to think the D-Pad on my controller is an analog stick, which is probably why a couple of other games gave me trouble long ago.

That was a fantastic idea @StephenCWills to work around it. It worked like a charm. I love creative solutions like that.

I'm now able to play without any issues. Thank you so much!

**Comment by AJenbo** [comment] 2024-08-15 18:02
> Hmmm. I wonder if it thinks the D-Pad on my SNES controller is an analog stick. Are you able to unbind movement from your analog stick?

It sounds a lot like this is what is going on. I'm not really sure what we can do about that since it's a hardware thing.

**Closed** 2024-09-11 00:35 UTC
