### ISSUE TITLE
Ugly cursor/rectangle

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#5611] opened 2022-12-17 00:36 UTC
### Operating System

Linux x64

### DevilutionX version

Custom build (please specify commit ID: current master)

### Describe

After the Lazarus Quest cutscene, an ugly mouse pointer is briefly visible.
The issue is probably related to https://github.com/diasurgical/devilutionX/issues/5560

You can see it at the thirteenth second of the following scene.

https://user-images.githubusercontent.com/45902449/208213073-4a6ece7e-0cc6-468e-8dc0-423a18e06041.mp4

![ugly_cursor-00826](https://user-images.githubusercontent.com/45902449/208213158-797bf8eb-8fe4-42ca-8823-4c7346a6aa24.jpg)

### To Reproduce

1. Enter the teleporter area
2. Wait for the cutscene to end
3. See the ugly rectangle

### Expected Behavior

No ugly cursor/rectangle

### Additional context

The issue appears since commit 680ab5ec40fcc2078ed6ad4a48bf081e68b1c9a1

Savegame:
[ugly_cursor.zip](https://github.com/diasurgical/devilutionX/files/10250288/ugly_cursor.zip)

**Comment by StephenCWills** [comment] 2022-12-17 00:42
I believe this should have been fixed by #5581.

**Comment by Chance4us** [comment] 2022-12-17 01:05
> 

Unfortunately the bug still occurs in master.

**Comment by Chance4us** [comment] 2022-12-17 01:07
I retest quickliy

**Comment by Chance4us** [comment] 2022-12-17 01:10
I just tested again. The bug still occurs in master.

**Comment by AJenbo** [comment] 2022-12-17 04:54
which commit?

**Comment by qndel** [comment] 2022-12-17 06:53
oh well since it's cursor related, I might add another one - if you go to credits/support screen and quit it, the cursor is huge and orange for 1 frame : P

**Comment by Chance4us** [comment] 2022-12-17 07:49
In general, the issue has been occurring since commit 680ab5e.
Despite the fix https://github.com/diasurgical/devilutionX/pull/5581 it still occurs in master.

**Comment by glebm** [comment] 2022-12-17 10:40
Thanks for the save file, I'll try to fix this

**Closed** 2022-12-17 11:08 UTC

**Comment by glebm** [comment] 2022-12-17 11:26
@qndel I cannot reproduce that one, please open a separate issue with some more details (platform, hardware cursor setting, and ideally a video)
