### ISSUE TITLE
[Suggestion] Increase MaxGold per slot

### ISSUE THREAD

**Issue by dalvim** [diasurgical/devilutionX#128] opened 2019-06-06 21:02 UTC
Just 5000 will fill a lot of slots and typically we drop gold in town at the start of the game and take it back at the end.

Increasing the max amount would relieve this tedious operation :)

Considerations could be taken given the character level, i.e., the higher the char the greater the gold amount per slot... or just top it at a very comfortable value...

**Comment by VonKossa** [comment] 2019-06-07 20:17
My humble opinion is that such a move breaks the intended (or unintended) game mechanics. It would simply just not be Diablo anymore.
With time there will of course be more and more demands of this kind, might i suggest that all alterations in gameplay will be implemented as optional features?

**Comment by AJenbo** [comment] 2019-06-07 22:14
DevilutionX intention is to keep things vanilla, but make the game mod friendly.
The few changes that are introduced will in general be configurable and off by default in most cases

**Comment by galaxyhaxz** [comment] 2019-06-08 10:57
The easy way to fix this is to eventually replace all `2500/5000` with defines so you can change with one line of code. Hellfire added some hacky stuff to allow 10000 with that unique amulet (can't remember the name).

**Comment by Manuel-K** [comment] 2019-06-08 19:05
I'll create defines for 1000/2500/5000 (probably) tomorrow. Is `GOLD_SMALL_LIMIT`/`GOLD_MEDIUM_LIMIT`/`GOLD_LARGE_LIMIT` okay?

**Comment by dalvim** [comment] 2019-06-09 00:08
Wow! Amazing, thanks!

In the meantime i just tinkered with it and i think i've succeeded:

Here's what i did:

In enums.h i added the following enum
enum gold_quantity {
	GOLD_SMALL = 1000,
	GOLD_MEDIUM = 2500,
	GOLD_MAX = 10000, // Added this concept to allow artowrk for large gold starting in a lower number.
};

The i carefully grepped for 1000, 2500 and 5000 and sed-ed where appropriate (being careful not to change every instance blindly, hence some extra sed's)

#= devilutionX-master/Source folder = 


#player.cpp
sed -i 's/5000/GOLD_MAX/g' Source/player.cpp

#stores.cpp
sed -i 's/5000/GOLD_MAX/g' Source/stores.cpp
sed -i 's/2500/GOLD_MEDIUM/g' Source/stores.cpp
sed -i 's/_ivalue <= 1000/_ivalue <= GOLD_SMALL/g' Source/stores.cpp

#debug.cpp
sed -i 's/5000/GOLD_MAX/g' Source/debug.cpp


#inv.cpp
sed -i 's/5000/GOLD_MAX/g' Source/inv.cpp
  sed -i 's/sgdwLastTime >= GOLD_MAX/sgdwLastTime >= 5000/g' Source/inv.cpp # undoing the sole line where this 5000 doesn't refer to gold. (i know there are better sed ways but i'm no expert :) )
sed -i 's/2500/GOLD_MEDIUM/g' Source/inv.cpp
sed -i 's/1000/GOLD_SMALL/g' Source/inv.cpp

#items.cpp
sed -i 's/5000/GOLD_MAX/g' Source/items.cpp
sed -i 's/2500/GOLD_MEDIUM/g' Source/items.cpp
sed -i 's/ivalue <= 1000/ivalue <= GOLD_SMALL/g' Source/items.cpp
sed -i 's/rndv > 1000/rndv > GOLD_SMALL/g' Source/items.cpp

#control.cpp
sed -i 's/2500/GOLD_MEDIUM/g' Source/control.cpp
sed -i 's/1000/GOLD_SMALL/g' Source/control.cpp


... i think i found a bug here:


Source/items.cpp
    -> void CreatePlrItems(int p)
    -> line 930 & 931: 
        plr[p].HoldItem._ivalue = 100; <--- Probably here should be 1000? (and changed to GOLD_SMALL)
        plr[p].HoldItem._iCurs = ICURS_GOLD_SMALL;

I did change to GOLD_SMALL and things are looking good.

Just tried to top at 10000 and after reaching that limit it started adding gold on a new slot. I think i'll top that tp 50k :)  (int is 4 bytes here so there shouldn't be any problems but i'll post if there are)

**Comment by sskras** [comment] 2019-06-09 07:32
> ... i think i found a bug here:
> 
> Source/items.cpp
> -> void CreatePlrItems(int p)
> -> line 930 & 931:
> plr[p].HoldItem._ivalue = 100; <--- Probably here should be 1000? (and changed to GOLD_SMALL)
> plr[p].HoldItem._iCurs = ICURS_GOLD_SMALL;

This comes from the decompiler:
https://github.com/diasurgical/devilution/blob/dde68ff89e9a41d684d1bf533446ba11a2c321c6/Source/items.cpp#L1596

As the fn is marked as bin-exact, the bug (if real) is left by the original developers.  How does it manifest if at all?

**Comment by sskras** [comment] 2019-06-09 07:43
@AJenbo wrote:

> DevilutionX intention is to keep things vanilla, but make the game mod friendly.
> The few changes that are introduced will in general be configurable and off by default in most cases

IIRC, all modifications should go to the [devilution-plus-plus](https://github.com/diasurgical/devilution-plus-plus).  Which sadly isn't updated since Aug 18, 2018 already.

Maybe create an issue there, then ask @ApertureSecurity to rebase that repo to the current **devilution**?

**Comment by Manuel-K** [comment] 2019-06-09 08:27
@dalvim If you've already done the work, then I don't have to recreate it. Please create a PR against devilution that has the default values for all three constants. I would be happier with the names if they all contained `_LIMIT` somewhere.

**Comment by AJenbo** [comment] 2019-06-09 13:24
> > ... i think i found a bug here:
> > Source/items.cpp
> > -> void CreatePlrItems(int p)
> > -> line 930 & 931:
> > plr[p].HoldItem._ivalue = 100; <--- Probably here should be 1000? (and changed to GOLD_SMALL)
> > plr[p].HoldItem._iCurs = ICURS_GOLD_SMALL;
> 
> This comes from the decompiler:
> https://github.com/diasurgical/devilution/blob/dde68ff89e9a41d684d1bf533446ba11a2c321c6/Source/items.cpp#L1596
> 
> As the fn is marked as bin-exact, the bug (if real) is left by the original developers. How does it manifest if at all?

This is the function that creates the start equipment, all players start with a small pile of 100 gold pieces, so not a bug.

**Comment by Manuel-K** [comment] 2019-06-09 13:36
I should have known that, because I looked at the code yesterday and I still wondered if it was a bug. That's what happens if you only see a small slice of code.

**Comment by dalvim** [comment] 2019-06-09 14:32
> > > ... i think i found a bug here:
> > > Source/items.cpp
> > > -> void CreatePlrItems(int p)
> > > -> line 930 & 931:
> > > plr[p].HoldItem._ivalue = 100; <--- Probably here should be 1000? (and changed to GOLD_SMALL)
> > > plr[p].HoldItem._iCurs = ICURS_GOLD_SMALL;
> > 
> > 
> > This comes from the decompiler:
> > https://github.com/diasurgical/devilution/blob/dde68ff89e9a41d684d1bf533446ba11a2c321c6/Source/items.cpp#L1596
> > As the fn is marked as bin-exact, the bug (if real) is left by the original developers. How does it manifest if at all?
> 
> This is the function that creates the start equipment, all players start with a small pile of 100 gold pieces, so not a bug.

... ok so i guess the enum could get an added entry like GOLD_START and that 100 changed to it...

**Comment by Manuel-K** [comment] 2019-06-09 14:35
IMO just ignore it. The rest of the starting equipment is hard-coded as well.

**Comment by dalvim** [comment] 2019-06-09 15:23
First time doing a pull request :) I think everything is ok. Please let me know if there's any problem. :)

@Manuel-K I added the _LIMIT suffix as you suggested and left the 100 untouched

**Comment by Manuel-K** [comment] 2019-06-10 20:44
@dalvim Do you know how to move the patch to the other repo? 

If you don't want to do it yourself, I've prepared something on my fork.

**Comment by AJenbo** [comment] 2019-09-15 14:29
Closing as this would be something for a different mod, also Hellfire allows for 10k gold stacks and support is coming (83% done).

**Closed by AJenbo** 2019-09-15 14:29 UTC
Labels: enhancement, question

**Comment by Manuel-K** [comment] 2019-09-15 17:09
Actually we should have closed this when the PR was merged into devilution.
