### ISSUE TITLE
Fresh build on MSVC 2022 fails with 'DISCORD_LIB-NOTFOUND' missing

### ISSUE THREAD

**Issue by tsunamistate** [diasurgical/devilutionX#5694] opened 2023-01-21 12:54 UTC
### Operating System

Windows x64

### DevilutionX version

Custom build (please specify commit ID)

### Describe

Commit ID: bisected to f4a3b54fb9b14d90e711d568a380e56ccbee0e4a
MSVC 2022 v17.4.4

Trying to compile a fresh build (after clearing CMake cache or deleting build folder) fails with the following error:

```
>------ Build All started: Project: devxclone, Configuration: x64-Debug ------
D:\src\devxclone\build\x64-Debug\ninja : error : 'DISCORD_LIB-NOTFOUND', needed by 'devilutionx.exe', missing and no known rule to make it

Build All failed.
```

### To Reproduce

1. Delete build folder (e.g. `<project root>/build/x64-Debug`)
2. Open Visual Studio on DevilutionX project root
3. Choose any configuration for compiling (e.g. x64-Debug)
4. Wait until CMake configuration and generation is complete
5. Choose `Build -> Build All` from top menu or press `Ctrl+Shift+B` to start building

### Expected Behavior

Build is completed without errors

**Comment by glebm** [comment] 2023-01-21 12:55
This is likely caused by the recent SDK update in https://github.com/diasurgical/devilutionX/pull/5672.

**Comment by tsunamistate** [comment] 2023-01-21 12:57
I did bisect it to that commit: https://github.com/diasurgical/devilutionX/commit/f4a3b54fb9b14d90e711d568a380e56ccbee0e4a

**Comment by glebm** [comment] 2023-01-21 13:03
I've attempted a fix in https://github.com/diasurgical/devilutionX/pull/5695, can you please see if it works?

**Comment by tsunamistate** [comment] 2023-01-21 13:11
Unfortunately, PR breaks configuration of Discord SDK

```
1> [CMake] CMake Error at 3rdParty/discord/CMakeLists.txt:29 (find_library):
1> [CMake]   Could not find DISCORD_LIB using the following names: discord_game_sdk.dll,
1> [CMake]   D:/src/devxclone/build/x64-Debug/_deps/discordsrc-src/lib/x86_64
1> [CMake] 
1> [CMake] 
1> [CMake] -- Configuring incomplete, errors occurred!
1> [CMake] See also "D:/src/devxclone/build/x64-Debug/CMakeFiles/CMakeOutput.log".
1> [CMake] See also "D:/src/devxclone/build/x64-Debug/CMakeFiles/CMakeError.log".
```

Here's an error from CMakeError.log:

```
[1/2] Building CXX object CMakeFiles\cmTC_e40b9.dir\src.cxx.obj
FAILED: CMakeFiles/cmTC_e40b9.dir/src.cxx.obj 
C:\PROGRA~1\MIB055~1\2022\COMMUN~1\VC\Tools\MSVC\1434~1.319\bin\Hostx86\x64\cl.exe  /nologo /TP -DCOMPILER_HAS_DEPRECATED_ATTR  /DWIN32 /D_WINDOWS /GR /EHsc  /Zi /Ob0 /Od /RTC1 -MDd -std:c++20 /showIncludes /FoCMakeFiles\cmTC_e40b9.dir\src.cxx.obj /FdCMakeFiles\cmTC_e40b9.dir\ /FS -c D:\src\devxclone\build\x64-Debug\CMakeFiles\CMakeTmp\src.cxx
D:\src\devxclone\build\x64-Debug\CMakeFiles\CMakeTmp\src.cxx(1): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
D:\src\devxclone\build\x64-Debug\CMakeFiles\CMakeTmp\src.cxx(1): error C2065: '__deprecated__': undeclared identifier
D:\src\devxclone\build\x64-Debug\CMakeFiles\CMakeTmp\src.cxx(1): error C2062: type 'int' unexpected
D:\src\devxclone\build\x64-Debug\CMakeFiles\CMakeTmp\src.cxx(1): error C2143: syntax error: missing ';' before '{'
D:\src\devxclone\build\x64-Debug\CMakeFiles\CMakeTmp\src.cxx(1): error C2447: '{': missing function header (old-style formal list?)

D:\src\devxclone\build\x64-Debug\CMakeFiles\CMakeTmp\src.cxx(2): error C3861: 'somefunc': identifier not found

ninja: build stopped: subcommand failed.
```

**Comment by tsunamistate** [comment] 2023-01-21 13:27
@glebm Now it fails trying to apply your patch
[patcherror.txt](https://github.com/diasurgical/devilutionX/files/10472253/patcherror.txt)

**Comment by glebm** [comment] 2023-01-21 13:35
@tsunamistate I've fixed the patch application and now it builds for me locally using mingw64
Hopefully the MSVC build is also fixed

**Comment by tsunamistate** [comment] 2023-01-21 13:47
Build is now successful, but CMake no longer copies `discord_game_sdk.dll` into build root, you have to do that manually
This is a regression, since that file was copied before

**Comment by glebm** [comment] 2023-01-21 13:51
I've added the file copy back in but will need to do some additional patching to make it build on mingw x86 before merging the PR (probably tomorrow)

**Comment by tsunamistate** [comment] 2023-01-21 14:02
Fix confirmed for MSVC, both Debug and Release builds compile and run without errors.
Good luck on MinGW x86 issue!

**Comment by glebm** [comment] 2023-01-21 15:15
Thanks for testing! I've managed to fix the mingw builds so this will be merged to master shortly

**Closed** 2023-01-21 15:18 UTC
Labels: bug, build system
