### ISSUE TITLE
Farmer in hellfire repeatedly wonders about explosion

### ISSUE THREAD

**Issue by vladtepesch** [diasurgical/devilutionX#2590] opened 2021-08-12 20:08 UTC
mportant information
win 10 64bit self build based on commit 0e56e52

Describe
Clicking the farmer after getting reward always replays the last text.

Expected behavior
Originally he does nothing after finishing quest.

**Comment by AJenbo** [comment] 2021-08-12 20:14
Isn't this a duplicate of https://github.com/diasurgical/devilution/issues/2247 ?

**Comment by vladtepesch** [comment] 2021-08-12 20:57
the other one is a `devilution` bug (without X).
There is a bug in both.
here is the `case 10` missing and the `case 3` quest state assignment correct. but in the other the wrong quest state is assigned, so that the case cannot be reached (in contrast to the actual original game)

**Closed** 2021-08-15 15:02 UTC
