### ISSUE TITLE
SDL Policy error on Windows 10

### ISSUE THREAD

**Issue by donizettilorenzo** [diasurgical/devilutionX#1405] opened 2021-04-07 16:47 UTC
x86 and x64 builds

https://postimg.cc/bG2cZQ55

2 Win10 x64 20H2 tested, same fault.

**Comment by AJenbo** [comment] 2021-04-07 17:13
Please try the latest beta: https://26646-143324737-gh.circle-artifacts.com/0/devilutionx_x86.zip

Duplicate of #1391

**Closed by AJenbo** 2021-04-07 17:13 UTC

**Comment by donizettilorenzo** [comment] 2021-04-07 18:15
It doesn't even start.

**Comment by AJenbo** [comment] 2021-04-07 18:42
Ok, we expect to release a patch to correct this shortly

**Comment by donizettilorenzo** [comment] 2021-04-07 20:56
No need to hurry! Thanks!
