### ISSUE TITLE
Items often in the air when return to town

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#2149] opened 2021-06-13 15:07 UTC
I returned to town and there was the cleaver in the air.
Unfortunately, I was unable to reproduce it.
After reloading the game, it was back on the floor. 

![cleaver](https://user-images.githubusercontent.com/45902449/121812795-9944fe00-cc69-11eb-811c-eff8a4bc8c7e.png)
I'm really sorry I don't have any useful information. I can only attach the savegame when it already looks normal.
[single_0.hsv.zip](https://github.com/diasurgical/devilutionX/files/6644125/single_0.hsv.zip)

**Comment by AJenbo** [comment] 2021-06-13 15:50
It's not limited to the cleaver

Probably a duplicate of https://github.com/diasurgical/devilutionX/issues/2107

**Comment by sumyunggai** [comment] 2021-06-13 16:09
@Chance4us I had this same issue with other items left on the ground. Turns out that it was due to (1) not clearing my build directory and (2) not fully regenerating cmake cache before building (all on Windows) that gave me the error. I suggest trying that and seeing if you still have the issue.

**Comment by Chance4us** [comment] 2021-06-13 16:27
@AJenbo , @sumyunggai Thanks guys, both could be true. I will try as recommended. I think we can close this one.

**Comment by Chance4us** [comment] 2021-06-13 16:28
By the way, i'm on linux.

**Comment by Chance4us** [comment] 2021-06-13 18:59
I don't understand why it happens. Now the scroll is in the air. I cleared the build folder and compiled again.
![town](https://user-images.githubusercontent.com/45902449/121818845-108a8a00-cc8a-11eb-8ba6-64b740d41424.png)
Are you sure it's the same as # 2107?
Should I also delete the savegame and start a new game?

**Comment by qndel** [comment] 2021-06-13 19:43
I think we've found the bug but still aren't sure what causes it

**Closed** 2021-06-14 00:08 UTC
Labels: bug, savegame attached
